// Words for the "read whole words" and "spell it" drills: common, concrete,
// fully vowel-marked (content/STYLE.md). A word enters the drills once all its
// letters are unlocked. Includes the old app's 60 words, checked and corrected
// (بچّه bachche, مدرسه madrese, چای chây), plus words chosen for the letters
// that share a sound (ث س ص, ذ ز ض ظ, ت ط, ح ه, غ ق).

export interface DrillWord {
  fa: string;
  en: string;
}

export const DRILL_WORDS: DrillWord[] = [
  { fa: "آب", en: "water" },
  { fa: "باد", en: "wind" },
  { fa: "پا", en: "foot, leg" },
  { fa: "تاب", en: "swing" },
  { fa: "بابا", en: "dad" },
  { fa: "تاج", en: "crown" },
  { fa: "خانه", en: "house, home" },
  { fa: "دَسْت", en: "hand" },
  { fa: "سَر", en: "head" },
  { fa: "چِشْم", en: "eye" },
  { fa: "گُل", en: "flower" },
  { fa: "ماه", en: "moon, month" },
  { fa: "خُورْشید", en: "sun" },
  { fa: "کِتاب", en: "book" },
  { fa: "دَرْس", en: "lesson" },
  { fa: "نور", en: "light" },
  { fa: "شَب", en: "night" },
  { fa: "روز", en: "day" },
  { fa: "راه", en: "road, way" },
  { fa: "دِل", en: "heart (feelings)" },
  { fa: "زَبان", en: "language, tongue" },
  { fa: "نام", en: "name (formal)" },
  { fa: "مَرْد", en: "man" },
  { fa: "زَن", en: "woman" },
  { fa: "بَچّه", en: "child" },
  { fa: "دوسْت", en: "friend" },
  { fa: "پِدَر", en: "father" },
  { fa: "مادَر", en: "mother" },
  { fa: "نان", en: "bread" },
  { fa: "آش", en: "thick soup (âsh)" },
  { fa: "چای", en: "tea" },
  { fa: "میوه", en: "fruit" },
  { fa: "رَنْگ", en: "colour" },
  { fa: "زَمان", en: "time" },
  { fa: "دِرَخْت", en: "tree" },
  { fa: "کوه", en: "mountain" },
  { fa: "دَرْیا", en: "sea" },
  { fa: "آسْمان", en: "sky" },
  { fa: "زَمین", en: "ground, earth" },
  { fa: "آتَش", en: "fire" },
  { fa: "سَنْگ", en: "stone" },
  { fa: "مَدْرِسه", en: "school" },
  { fa: "شَهْر", en: "city" },
  { fa: "روسْتا", en: "village" },
  { fa: "قَلْب", en: "heart (organ)" },
  { fa: "عِشْق", en: "love" },
  { fa: "شادی", en: "joy" },
  { fa: "غَم", en: "sorrow" },
  { fa: "اُمید", en: "hope" },
  { fa: "صَبْر", en: "patience" },
  { fa: "خوب", en: "good" },
  { fa: "بَد", en: "bad" },
  { fa: "بُزُرْگ", en: "big" },
  { fa: "کوچَک", en: "small (said kuchik in Tehran)" },
  { fa: "سِفید", en: "white" },
  { fa: "سیاه", en: "black" },
  { fa: "سَبْز", en: "green" },
  { fa: "سُرْخ", en: "red" },
  { fa: "آبی", en: "blue" },
  { fa: "رَفْتَن", en: "to go" },
  { fa: "آمَدَن", en: "to come" },
  { fa: "خوانْدَن", en: "to read" },
  { fa: "نِوِشْتَن", en: "to write" },
  { fa: "دیدَن", en: "to see" },
  // Letters that share a sound
  { fa: "ثِرْوَت", en: "wealth" },
  { fa: "مِثال", en: "example" },
  { fa: "ثانیه", en: "second (of time)" },
  { fa: "صُبْح", en: "morning" },
  { fa: "صِدا", en: "sound, voice" },
  { fa: "صابون", en: "soap" },
  { fa: "صَنْدَلی", en: "chair" },
  { fa: "ضَعیف", en: "weak" },
  { fa: "ضَرَر", en: "harm" },
  { fa: "طَلا", en: "gold" },
  { fa: "طوطی", en: "parrot" },
  { fa: "ظَرْف", en: "dish, container" },
  { fa: "ظُهْر", en: "noon" },
  { fa: "ذُرَّت", en: "corn" },
  { fa: "غَذا", en: "food" },
  { fa: "غَریب", en: "stranger; strange" },
  { fa: "قَنْد", en: "sugar lump" },
  { fa: "قَهْوه", en: "coffee" },
  { fa: "حَرْف", en: "letter (of the alphabet); talk, what someone says" },
  { fa: "حال", en: "state, how one is" },
  { fa: "حَمّام", en: "bath, shower room" },
  { fa: "حَیاط", en: "courtyard" },
  { fa: "عَسَل", en: "honey" },
  { fa: "عَکْس", en: "photo" },
  { fa: "ساعَت", en: "hour; clock, watch" },
  // Persian-only letters and everyday words
  { fa: "ژاپُن", en: "Japan" },
  { fa: "ژاکَت", en: "cardigan (knitted)" },
  { fa: "پَنیر", en: "cheese" },
  { fa: "چِراغ", en: "lamp" },
  { fa: "گُرْبه", en: "cat" },
  { fa: "سَگ", en: "dog" },
  { fa: "اَسْب", en: "horse" },
  { fa: "ماهی", en: "fish" },
  { fa: "تَخْت", en: "bed" },
  { fa: "میز", en: "table, desk" },
  { fa: "پَنْجِره", en: "window" },
  { fa: "دَر", en: "door (the same letters also spell dar, in)" },
  { fa: "اُتاق", en: "room" },
  { fa: "شیر", en: "milk; lion; tap (faucet)" },
  { fa: "سیب", en: "apple" },
  { fa: "خیار", en: "cucumber" },
  { fa: "بَرْف", en: "snow" },
  { fa: "باران", en: "rain" },
  { fa: "اَبْر", en: "cloud" },
  { fa: "فارْسی", en: "Persian (language)" },
  { fa: "ایران", en: "Iran" },
  { fa: "کُجا", en: "where" },
  { fa: "چِرا", en: "why" },
  { fa: "سَلام", en: "hello" },
  { fa: "مِرْسی", en: "thanks (informal)" },
];
