// Words for the "read whole words" and "spell it" drills: common, concrete,
// fully vowel-marked (content/STYLE.md). A word enters the drills once all its
// letters are unlocked. Includes the old app's 60 words, checked and corrected
// (بچّه bachche, مدرسه madrese, چای chây), plus words chosen for the letters
// that share a sound (ث س ص, ذ ز ض ظ, ت ط, ح ه, غ ق).

import type { Topic } from "./topics";

export interface DrillWord {
  fa: string;
  en: string;
  topic: Topic;
}

export const DRILL_WORDS: DrillWord[] = [
  { fa: "آب", en: "water", topic: "nature" },
  { fa: "باد", en: "wind", topic: "weather" },
  { fa: "پا", en: "foot, leg", topic: "body" },
  { fa: "تاب", en: "swing", topic: "things" },
  { fa: "بابا", en: "dad", topic: "people" },
  { fa: "تاج", en: "crown", topic: "things" },
  { fa: "خانه", en: "house, home", topic: "home" },
  { fa: "دَسْت", en: "hand", topic: "body" },
  { fa: "سَر", en: "head", topic: "body" },
  { fa: "چِشْم", en: "eye", topic: "body" },
  { fa: "گُل", en: "flower", topic: "nature" },
  { fa: "ماه", en: "moon, month", topic: "time" },
  { fa: "خُورْشید", en: "sun", topic: "nature" },
  { fa: "کِتاب", en: "book", topic: "learning" },
  { fa: "دَرْس", en: "lesson", topic: "learning" },
  { fa: "نور", en: "light", topic: "nature" },
  { fa: "شَب", en: "night", topic: "time" },
  { fa: "روز", en: "day", topic: "time" },
  { fa: "راه", en: "road, way", topic: "places" },
  { fa: "دِل", en: "heart (feelings)", topic: "feelings" },
  { fa: "زَبان", en: "language, tongue", topic: "learning" },
  { fa: "نام", en: "name (formal)", topic: "everyday" },
  { fa: "مَرْد", en: "man", topic: "people" },
  { fa: "زَن", en: "woman", topic: "people" },
  { fa: "بَچّه", en: "child", topic: "people" },
  { fa: "دوسْت", en: "friend", topic: "people" },
  { fa: "پِدَر", en: "father", topic: "people" },
  { fa: "مادَر", en: "mother", topic: "people" },
  { fa: "نان", en: "bread", topic: "food" },
  { fa: "آش", en: "thick soup (âsh)", topic: "food" },
  { fa: "چای", en: "tea", topic: "food" },
  { fa: "میوه", en: "fruit", topic: "food" },
  { fa: "رَنْگ", en: "colour", topic: "colours" },
  { fa: "زَمان", en: "time", topic: "time" },
  { fa: "دِرَخْت", en: "tree", topic: "nature" },
  { fa: "کوه", en: "mountain", topic: "nature" },
  { fa: "دَرْیا", en: "sea", topic: "nature" },
  { fa: "آسْمان", en: "sky", topic: "nature" },
  { fa: "زَمین", en: "ground, earth", topic: "nature" },
  { fa: "آتَش", en: "fire", topic: "nature" },
  { fa: "سَنْگ", en: "stone", topic: "nature" },
  { fa: "مَدْرِسه", en: "school", topic: "places" },
  { fa: "شَهْر", en: "city", topic: "places" },
  { fa: "روسْتا", en: "village", topic: "places" },
  { fa: "قَلْب", en: "heart (organ)", topic: "body" },
  { fa: "عِشْق", en: "love", topic: "feelings" },
  { fa: "شادی", en: "joy", topic: "feelings" },
  { fa: "غَم", en: "sorrow", topic: "feelings" },
  { fa: "اُمید", en: "hope", topic: "feelings" },
  { fa: "صَبْر", en: "patience", topic: "feelings" },
  { fa: "خوب", en: "good", topic: "describing" },
  { fa: "بَد", en: "bad", topic: "describing" },
  { fa: "بُزُرْگ", en: "big", topic: "describing" },
  { fa: "کوچَک", en: "small (said kuchik in Tehran)", topic: "describing" },
  { fa: "سِفید", en: "white", topic: "colours" },
  { fa: "سیاه", en: "black", topic: "colours" },
  { fa: "سَبْز", en: "green", topic: "colours" },
  { fa: "سُرْخ", en: "red", topic: "colours" },
  { fa: "آبی", en: "blue", topic: "colours" },
  { fa: "رَفْتَن", en: "to go", topic: "verbs" },
  { fa: "آمَدَن", en: "to come", topic: "verbs" },
  { fa: "خوانْدَن", en: "to read", topic: "verbs" },
  { fa: "نِوِشْتَن", en: "to write", topic: "verbs" },
  { fa: "دیدَن", en: "to see", topic: "verbs" },
  // Letters that share a sound
  { fa: "ثِرْوَت", en: "wealth", topic: "everyday" },
  { fa: "مِثال", en: "example", topic: "learning" },
  { fa: "ثانیه", en: "second (of time)", topic: "time" },
  { fa: "صُبْح", en: "morning", topic: "time" },
  { fa: "صِدا", en: "sound, voice", topic: "everyday" },
  { fa: "صابون", en: "soap", topic: "home" },
  { fa: "صَنْدَلی", en: "chair", topic: "home" },
  { fa: "ضَعیف", en: "weak", topic: "describing" },
  { fa: "ضَرَر", en: "harm", topic: "everyday" },
  { fa: "طَلا", en: "gold", topic: "things" },
  { fa: "طوطی", en: "parrot", topic: "animals" },
  { fa: "ظَرْف", en: "dish, container", topic: "home" },
  { fa: "ظُهْر", en: "noon", topic: "time" },
  { fa: "ذُرَّت", en: "corn", topic: "food" },
  { fa: "غَذا", en: "food", topic: "food" },
  { fa: "غَریب", en: "stranger; strange", topic: "describing" },
  { fa: "قَنْد", en: "sugar lump", topic: "food" },
  { fa: "قَهْوه", en: "coffee", topic: "food" },
  { fa: "حَرْف", en: "letter (of the alphabet); talk, what someone says", topic: "learning" },
  { fa: "حال", en: "state, how one is", topic: "everyday" },
  { fa: "حَمّام", en: "bath, shower room", topic: "home" },
  { fa: "حَیاط", en: "courtyard", topic: "home" },
  { fa: "عَسَل", en: "honey", topic: "food" },
  { fa: "عَکْس", en: "photo", topic: "things" },
  { fa: "ساعَت", en: "hour; clock, watch", topic: "time" },
  // Persian-only letters and everyday words
  { fa: "ژاپُن", en: "Japan", topic: "places" },
  { fa: "ژاکَت", en: "cardigan (knitted)", topic: "things" },
  { fa: "پَنیر", en: "cheese", topic: "food" },
  { fa: "چِراغ", en: "lamp", topic: "home" },
  { fa: "گُرْبه", en: "cat", topic: "animals" },
  { fa: "سَگ", en: "dog", topic: "animals" },
  { fa: "اَسْب", en: "horse", topic: "animals" },
  { fa: "ماهی", en: "fish", topic: "animals" },
  { fa: "تَخْت", en: "bed", topic: "home" },
  { fa: "میز", en: "table, desk", topic: "home" },
  { fa: "پَنْجِره", en: "window", topic: "home" },
  { fa: "دَر", en: "door (the same letters also spell dar, in)", topic: "home" },
  { fa: "اُتاق", en: "room", topic: "home" },
  { fa: "شیر", en: "milk; lion; tap (faucet)", topic: "food" },
  { fa: "سیب", en: "apple", topic: "food" },
  { fa: "خیار", en: "cucumber", topic: "food" },
  { fa: "بَرْف", en: "snow", topic: "weather" },
  { fa: "باران", en: "rain", topic: "weather" },
  { fa: "اَبْر", en: "cloud", topic: "weather" },
  { fa: "فارْسی", en: "Persian (language)", topic: "learning" },
  { fa: "ایران", en: "Iran", topic: "places" },
  { fa: "کُجا", en: "where", topic: "everyday" },
  { fa: "چِرا", en: "why", topic: "everyday" },
  { fa: "سَلام", en: "hello", topic: "everyday" },
  { fa: "مِرْسی", en: "thanks (informal)", topic: "everyday" },
  // Key words from the letter pages
  { fa: "توپ", en: "ball", topic: "things" },
  { fa: "جَنْگَل", en: "forest", topic: "nature" },
  { fa: "لیوان", en: "glass (for drinking)", topic: "home" },
  { fa: "وَقْت", en: "time (an amount of it)", topic: "time" },
  { fa: "هَوا", en: "air, weather", topic: "weather" },
  { fa: "یَخ", en: "ice", topic: "weather" },
];
