import type { Lesson } from "../types";

// Unit 1: the 32 letters in alphabet order, in the drill groups, then the
// digits. Script lessons always show transliteration (the vowel marks come in
// Unit 2). Letter facts follow lib/persian/letters.ts; examples are original.

const SOURCE =
  "Thackston, An Introduction to Persian (the writing system); Shabani-Jadidi and Brookshaw, The Routledge Introductory Persian Course: Farsi Shirin Ast (Lesson 1, the alphabet); spelling after the Academy of Persian Language and Literature's rules.";

export const alphabet: Lesson[] = [
  {
    slug: "how-the-script-works",
    title: "How the script works",
    summary: "Right to left, joined up, no capitals, and four shapes for most letters depending on what they join.",
    register: "written",
    kinds: ["script"],
    showTranslit: true,
    source: SOURCE,
    vocab: [
      { fa: "بابا", en: "dad", topic: "people" },
      { fa: "سیب", en: "apple", topic: "food" },
      { fa: "دَرْد", en: "pain", topic: "body" },
      { fa: "سَبْز", en: "green", topic: "colours" },
      { fa: "دارو", en: "medicine", topic: "things" },
      { fa: "ایران", en: "Iran", topic: "places" },
      { fa: "تِهْران", en: "Tehran", topic: "places" },
    ],
    blocks: [
      {
        type: "idea",
        text: "Persian is written **right to left** in joined-up letters, and each letter takes a different **shape** depending on what it joins.",
      },
      {
        type: "text",
        text: "Persian uses the Arabic script with four extra letters: 32 in all. There are no capital letters. Most letters join the letter after them, so a word is written in one flowing line with a few breaks, and the short vowels usually aren't written at all (Unit 2 covers them). Numbers are the exception to right to left: ۱۴۰۵ still reads *1405*.",
      },
      { type: "heading", text: "One letter, four shapes" },
      {
        type: "table",
        caption: "ب in its four positions",
        headers: ["Isolated", "Initial", "Medial", "Final"],
        rows: [
          ["ب", "بـ", "ـبـ", "ـب"],
          ["on its own", "joined to the next letter", "joined on both sides", "joined to the letter before"],
        ],
      },
      {
        type: "text",
        text: "The four shapes share one skeleton, but the joined forms are shortened: at the start or in the middle of a word ب is just a small tooth with its dot, and the full boat appears only at the end or on its own. A few letters, such as ع and ه, change more (lessons 1.6 and 1.9). This course shows a joining form with a small line (ـ) where it connects: بـ joins the next letter on its left, ـب the letter before it on its right.",
      },
      { type: "heading", text: "Letters joining into words" },
      {
        type: "build",
        items: [
          { word: "بابا", en: "dad" },
          { word: "کِتاب", en: "book" },
          { word: "سیب", en: "apple" },
        ],
      },
      {
        type: "examples",
        items: [
          { fa: "ایران", en: "Iran" },
          { fa: "تِهْران", en: "Tehran" },
          { fa: "فارْسی", en: "Persian (the language)" },
          { fa: "سَلام", en: "hello" },
        ],
      },
      {
        type: "pair",
        title: "Letters that stop the chain",
        a: { fa: "دَرْد", en: "pain" },
        b: { fa: "سَبْز", en: "green" },
        diff: "In دَرْد (*dard*) no letter joins the next: د and ر never join forward, so the word is three separate pieces. In سَبْز (*sabz*) س and ب join forward, so only the last letter ends the chain.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "A gap is not a space",
        text: "After the seven letters that never join forward (ا د ذ ر ز ژ و), the next letter starts fresh and leaves a small gap. That gap is inside the word: دارو (*medicine*) is one word in four pieces, because none of its four letters joins forward.",
      },
      {
        type: "callout",
        kind: "culture",
        title: "Three styles of the same letters",
        text: "Books use Naskh, the style of this course's large letters. Screens and signs often use plain modern styles, like the smaller Persian text here. Poetry, calligraphy and many shop signs use Nastaliq, which slopes and seems to hang from the line. The letters are the same in each; only the style changes.",
      },
      {
        type: "quiz",
        questions: [
          {
            prompt: "Persian starts at which side of the line? Type left or right.",
            lang: "en",
            answers: ["right", "the right", "right to left", "from the right", "right side"],
            explain: "Persian runs right to left; only numbers read left to right.",
          },
          {
            prompt: "How many letters does the Persian alphabet have? Type the number.",
            lang: "en",
            answers: ["32", "thirty-two", "thirty two"],
            explain: "32: the 28 letters of the Arabic alphabet plus پ چ ژ گ.",
          },
          {
            prompt: "How many shapes can a joining letter take? Type the number.",
            lang: "en",
            answers: ["4", "four"],
            explain: "Four: isolated, initial, medial and final.",
          },
          {
            prompt: "Transliterate سَلام.",
            lang: "translit",
            answers: ["salam", "salâm"],
            explain: "سَلام, *salâm*: hello.",
          },
        ],
      },
    ],
  },
  {
    slug: "alef-and-be",
    title: "ا ب پ ت ث: alef and the boat letters",
    summary: "Alef stands tall and never joins forward; ب پ ت ث share one boat-shaped body and differ only in their dots.",
    register: "written",
    kinds: ["script"],
    showTranslit: true,
    source: SOURCE,
    vocab: [
      { fa: "آب", en: "water", topic: "nature" },
      { fa: "پا", en: "foot, leg", topic: "body" },
      { fa: "تاب", en: "swing", topic: "things" },
      { fa: "ثابِت", en: "fixed, steady", topic: "describing" },
      { fa: "پِدَر", en: "father", topic: "people" },
      { fa: "تار", en: "tar (a long-necked lute)", topic: "things" },
      { fa: "بار", en: "load; a time (as in “once”)", topic: "everyday" },
    ],
    blocks: [
      {
        type: "idea",
        text: "ب پ ت ث are **one shape with different dots**: one below is *b*, three below *p*, two above *t*, three above *s*.",
      },
      { type: "letters", chars: ["ا", "ب", "پ", "ت", "ث"] },
      {
        type: "text",
        text: "Alef (ا) is a single upright stroke that never joins the letter after it. In the middle or at the end of a word it spells the long vowel *â*; at the start of a word it only carries a vowel, which Unit 2 explains. آ, alef with a wavy *madde* on top, is *â* at the start of a word.",
      },
      { type: "heading", text: "Letters joining into words" },
      {
        type: "build",
        items: [
          { word: "بابا", en: "dad" },
          { word: "آب", en: "water" },
          { word: "تاب", en: "swing" },
          { word: "پا", en: "foot, leg" },
        ],
      },
      {
        type: "examples",
        items: [
          { fa: "آبی", en: "blue" },
          { fa: "پُل", en: "bridge" },
          { fa: "توت", en: "mulberry" },
          { fa: "ثابِت", en: "fixed, steady" },
          { fa: "پَنْج", en: "five" },
        ],
      },
      {
        type: "pair",
        title: "Only the dots differ",
        a: { fa: "تار", en: "tar, a long-necked lute" },
        b: { fa: "بار", en: "load; a time (as in “once”)" },
        diff: "Two dots above make ت (*t*); one dot below makes ب (*b*). The rest of the two words is the same.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "ث is not *th*",
        text: "In Arabic ث is the *th* of *think*. In Persian it is a plain *s*, the same sound as س: ثابِت is *sâbet*.",
      },
      {
        type: "callout",
        kind: "culture",
        title: "Persian's own letters",
        text: "پ is one of four letters Persian added to the Arabic alphabet for sounds Arabic lacks: پ (*p*), چ (*ch*), ژ (*zh*) and گ (*g*). To an Iranian they are simply part of the alphabet: پِدَر (*father*) is as Persian as a word gets.",
      },
      { type: "practice", group: 0 },
      {
        type: "quiz",
        questions: [
          { prompt: "Which of ب، پ، ت، ث has two dots above? Type it.", lang: "fa", answers: ["ت"], explain: "ت, *te*: two dots above." },
          { prompt: "How many dots does پ have? Type the number.", lang: "en", answers: ["3", "three"], explain: "Three, below: پ, *pe*." },
          {
            prompt: "Transliterate بابا.",
            lang: "translit",
            answers: ["baba", "bâbâ"],
            explain: "بابا, *bâbâ*: ا in the middle or at the end of a word is *â*.",
          },
          {
            prompt: "Which letter sounds like س and appears mostly in words from Arabic: ب، پ، ت or ث? Type it.",
            lang: "fa",
            answers: ["ث"],
            explain: "ث, *se*: an *s*, found mostly in Arabic loanwords like ثابِت.",
          },
        ],
      },
    ],
  },
  {
    slug: "jim-to-khe",
    title: "ج چ ح خ: one shape, four sounds",
    summary: "Four letters share one hooked shape; one dot below, three dots, no dot or a dot above decide the sound.",
    register: "both",
    kinds: ["script"],
    showTranslit: true,
    source: SOURCE,
    vocab: [
      { fa: "جا", en: "place", topic: "places" },
      { fa: "چای", en: "tea", topic: "food" },
      { fa: "حال", en: "state, how one is", topic: "everyday" },
      { fa: "خال", en: "mole, spot", topic: "body" },
      { fa: "خوب", en: "good", topic: "describing" },
      { fa: "چِرا", en: "why", topic: "everyday" },
    ],
    blocks: [
      {
        type: "idea",
        text: "ج چ ح خ share one shape: one dot below is *j*, three dots below *ch*, no dot *h*, and one dot above *kh*.",
      },
      { type: "letters", chars: ["ج", "چ", "ح", "خ"] },
      {
        type: "text",
        text: "The hook sits on the line and swings below it at the end of a word. خ is the rough *kh* of Scottish *loch*; ح is a plain *h*, the same sound as ه, used mostly in words from Arabic.",
      },
      { type: "heading", text: "Letters joining into words" },
      {
        type: "build",
        items: [
          { word: "چای", en: "tea" },
          { word: "حال", en: "state, how one is" },
          { word: "خانه", en: "house, home" },
          { word: "جا", en: "place" },
        ],
      },
      {
        type: "examples",
        items: [
          { fa: "جَوان", en: "young" },
          { fa: "چِرا", en: "why" },
          { fa: "حَرْف", en: "letter (of the alphabet); talk" },
          { fa: "خوب", en: "good" },
          { fa: "کوچه", en: "lane, alley" },
        ],
      },
      {
        type: "pair",
        title: "A dot changes the word",
        a: { fa: "حال", en: "state, how one is" },
        b: { fa: "خال", en: "mole, spot" },
        diff: "No dot: ح is *h*, and حال is *hâl*. One dot above: خ is *kh*, and خال is *khâl*.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "ح is not *kh*",
        text: "It is tempting to read every letter of this shape as *kh*. Only خ, with its dot above, is *kh*; ح, with no dot, is a plain *h*.",
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "How are you?",
        lines: [
          { who: "Ali", fa: "سَلام! {حالِت} چِطُوره؟", written: "سَلام! {حالِ} تُو چِطُور اَسْت؟", en: "Hi! How are you?" },
          { who: "Mina", fa: "{خوبَم}، مِرْسی. تُو چِطُوری؟", written: "{خوبَم}، مُتَشَکِّرَم. تُو چِطُوری؟", en: "I'm fine, thanks. How are you?" },
          { who: "Ali", fa: "مَنَم خوبَم. یه {چایی} می‌خُوری؟", written: "مَن هَم خوبَم. یِک {چای} می‌خُوری؟", en: "I'm fine too. Would you like a tea?" },
          { who: "Mina", fa: "آره، مِرْسی!", written: "بَله، مُتَشَکِّرَم!", en: "Yes, thanks!" },
        ],
        note: "خوبَم is *I'm fine* (خوب, *good*, plus ـَم, *I am*). مِرْسی, from French *merci*, is the everyday *thanks*; مُتَشَکِّرَم is the more formal one.",
      },
      { type: "practice", group: 1 },
      {
        type: "quiz",
        questions: [
          { prompt: "Type the letter for *kh*.", lang: "fa", answers: ["خ"], explain: "خ, *khe*: one dot above." },
          { prompt: "Transliterate چای.", lang: "translit", answers: ["chay", "chây"], explain: "چای, *chây*: a ی after a vowel is *y*." },
          { prompt: "Which of ج، چ، ح، خ has no dot? Type it.", lang: "fa", answers: ["ح"], explain: "ح, *he-ye jimi*: a plain *h*." },
        ],
      },
    ],
  },
  {
    slug: "dal-to-zhe",
    title: "د ذ ر ز ژ: letters that never join forward",
    summary: "Five letters that stop the chain: the word breaks after them and the next letter starts fresh.",
    register: "written",
    kinds: ["script"],
    showTranslit: true,
    source: SOURCE,
    vocab: [
      { fa: "روز", en: "day", topic: "time" },
      { fa: "دَر", en: "door", topic: "home" },
      { fa: "زَبان", en: "language, tongue", topic: "learning" },
      { fa: "ذُرَّت", en: "corn", topic: "food" },
      { fa: "ژاکَت", en: "cardigan (knitted)", topic: "things" },
      { fa: "دور", en: "far", topic: "describing" },
      { fa: "زور", en: "force, strength", topic: "everyday" },
      { fa: "زَرْد", en: "yellow", topic: "colours" },
      { fa: "مُژه", en: "eyelash", topic: "body" },
    ],
    blocks: [
      {
        type: "idea",
        text: "د ذ ر ز ژ **never join the letter after them**, so they only have two shapes: on their own, and joined from the right.",
      },
      { type: "letters", chars: ["د", "ذ", "ر", "ز", "ژ"] },
      {
        type: "text",
        text: "د and ذ sit on the line with a corner; ر ز ژ curve below it. With ا and و, that makes the seven letters that never join forward. ذ is *z*, the same sound as ز, and appears mostly in words from Arabic, plus a few common Persian ones like گُذَشْته (*past*).",
      },
      { type: "heading", text: "Letters joining into words" },
      {
        type: "build",
        items: [
          { word: "روز", en: "day" },
          { word: "دَر", en: "door" },
          { word: "زَرْد", en: "yellow" },
          { word: "ژاکَت", en: "cardigan" },
        ],
      },
      {
        type: "examples",
        items: [
          { fa: "زَبان", en: "language, tongue" },
          { fa: "ذُرَّت", en: "corn" },
          { fa: "دَرْس", en: "lesson" },
          { fa: "رَنْگ", en: "colour" },
          { fa: "مُژه", en: "eyelash" },
        ],
      },
      {
        type: "pair",
        title: "Far, or force",
        a: { fa: "دور", en: "far" },
        b: { fa: "زور", en: "force, strength" },
        diff: "Only the first letter differs: د with its corner, ز with its curve and dot. Nothing in either word joins forward, because د ز و ر never do.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "ز or ژ",
        text: "ژ has three dots, ز one. ژ is the *zh* of *measure* and fairly rare: it appears in some Persian words like مُژه (*eyelash*) and ویژه (*special*), and in words from French like ژاکَت.",
      },
      {
        type: "callout",
        kind: "culture",
        title: "Words from French",
        text: "Many everyday Persian words came from French: ژاکَت (from *jaquette*), مِرْسی (*merci*), آسانْسُور (*ascenseur*, a lift) and تاکْسی (*taxi*).",
      },
      { type: "practice", group: 2 },
      {
        type: "quiz",
        questions: [
          { prompt: "Type the letter for *zh* (as in *measure*).", lang: "fa", answers: ["ژ"], explain: "ژ, *zhe*: three dots." },
          { prompt: "Transliterate روز.", lang: "translit", answers: ["ruz"], explain: "روز, *ruz*: day." },
          {
            prompt: "Does د join the letter after it? Type yes or no.",
            lang: "en",
            answers: ["no"],
            explain: "No: د ذ ر ز ژ, like ا and و, never join forward.",
          },
        ],
      },
    ],
  },
  {
    slug: "sin-to-zad",
    title: "س ش ص ض: teeth and loops",
    summary: "س and ش are three small teeth; ص and ض are a loop with a tooth. Two of them share the sound s.",
    register: "written",
    kinds: ["script"],
    showTranslit: true,
    source: SOURCE,
    vocab: [
      { fa: "شیر", en: "milk; lion", topic: "food" },
      { fa: "صَد", en: "hundred", topic: "numbers" },
      { fa: "سَد", en: "dam", topic: "places" },
      { fa: "ضَعیف", en: "weak", topic: "describing" },
      { fa: "صُبْح", en: "morning", topic: "time" },
      { fa: "شَب", en: "night", topic: "time" },
    ],
    blocks: [
      {
        type: "idea",
        text: "س is *s* and ش (three dots) is *sh*; ص is also *s*, and ض (one dot) is *z*. ص and س, like ض and ز, differ only in **spelling**, not in sound.",
      },
      { type: "letters", chars: ["س", "ش", "ص", "ض"] },
      {
        type: "text",
        text: "Which *s* or *z* a word uses is part of its spelling and is learned with the word; Unit 3 gives the patterns that help. س is by far the most common *s*; ص and ض appear mostly in words from Arabic.",
      },
      { type: "heading", text: "Letters joining into words" },
      {
        type: "build",
        items: [
          { word: "سیب", en: "apple" },
          { word: "شَب", en: "night" },
          { word: "صُبْح", en: "morning" },
        ],
      },
      {
        type: "examples",
        items: [
          { fa: "سَلام", en: "hello" },
          { fa: "شیر", en: "milk; lion" },
          { fa: "صَد", en: "hundred" },
          { fa: "سَبْز", en: "green" },
          { fa: "ضَعیف", en: "weak" },
        ],
      },
      {
        type: "pair",
        title: "Same sound, different words",
        a: { fa: "صَد", en: "hundred" },
        b: { fa: "سَد", en: "dam" },
        diff: "Both are *sad*. Only the spelling tells a hundred (صَد) from a dam (سَد).",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "A hundred with the wrong s",
        text: "Because ص and س sound the same, it is easy to write سَد for *a hundred*. The word is صَد, and you will meet it constantly, as in صَد دَر صَد (*sad dar sad*, a hundred per cent).",
        wrong: { fa: "سَد تُومان", en: "meant: a hundred tomans" },
        right: { fa: "صَد تُومان", en: "a hundred tomans" },
      },
      {
        type: "callout",
        kind: "culture",
        title: "Morning and night",
        text: "Two greetings use these letters: صُبْح بِخَیر (*sobh bekheyr*, good morning) and شَب بِخَیر (*shab bekheyr*, good night).",
      },
      { type: "practice", group: 3 },
      {
        type: "quiz",
        questions: [
          { prompt: "Type the letter for *sh*.", lang: "fa", answers: ["ش"], explain: "ش, *shin*: three dots." },
          {
            prompt: "صَد (a hundred) and سَد (a dam) sound the same. Type the transliteration.",
            lang: "translit",
            answers: ["sad"],
            explain: "Both are *sad*.",
          },
          { prompt: "Which one says *z*: ص or ض? Type it.", lang: "fa", answers: ["ض"], explain: "ض, *zâd*: the one with a dot." },
        ],
      },
    ],
  },
  {
    slug: "ta-to-gheyn",
    title: "ط ظ ع غ: loops and hooks",
    summary: "ط and ظ are a loop with a tall stroke; ع and غ are an open hook that changes shape more than most letters.",
    register: "both",
    kinds: ["script"],
    showTranslit: true,
    source: SOURCE,
    vocab: [
      { fa: "طَلا", en: "gold", topic: "things" },
      { fa: "طوطی", en: "parrot", topic: "animals" },
      { fa: "ظُهْر", en: "noon", topic: "time" },
      { fa: "عَسَل", en: "honey", topic: "food" },
      { fa: "عِشْق", en: "love", topic: "feelings" },
      { fa: "غَذا", en: "food", topic: "food" },
      { fa: "عَرَب", en: "Arab", topic: "people" },
      { fa: "غَرْب", en: "west", topic: "places" },
      { fa: "ناهار", en: "lunch", topic: "food" },
    ],
    blocks: [
      {
        type: "idea",
        text: "ط is *t* and ظ is *z*; ع is a light catch in the throat, and غ is the throaty *gh*.",
      },
      { type: "letters", chars: ["ط", "ظ", "ع", "غ"] },
      {
        type: "text",
        text: "ط sounds like ت and ظ like ز; both appear mostly in words from Arabic. ع is often barely heard: عَسَل is simply *asal*, and inside a word it is a short break (ساعَت, *sâ'at*). غ and ق (next lesson) share one sound in Iranian Persian: a throaty *g*, softer between vowels, like a French *r*.",
      },
      { type: "heading", text: "Letters joining into words" },
      {
        type: "build",
        items: [
          { word: "طَلا", en: "gold" },
          { word: "عَسَل", en: "honey" },
          { word: "غَذا", en: "food" },
        ],
      },
      {
        type: "examples",
        items: [
          { fa: "طوطی", en: "parrot" },
          { fa: "ظُهْر", en: "noon" },
          { fa: "عِشْق", en: "love" },
          { fa: "غَم", en: "sorrow" },
          { fa: "ساعَت", en: "hour; clock, watch" },
        ],
      },
      {
        type: "pair",
        title: "One dot, a different word",
        a: { fa: "عَرَب", en: "Arab" },
        b: { fa: "غَرْب", en: "west" },
        diff: "Without the dot, ع at the start of a word is hardly heard: *arab*. With it, غ is *gh*: *gharb*.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "Overdoing ع",
        text: "In Arabic ع is a strong sound from deep in the throat. In Persian it is at most a short break, and often nothing at all: عَسَل is *asal*. Saying it the Arabic way sounds foreign.",
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "Lunchtime",
        lines: [
          { who: "Reza", fa: "{ساعَت} چَنْده؟", written: "{ساعَت} چَنْد اَسْت؟", en: "What time is it?" },
          { who: "Leila", fa: "{ظُهْره}. وَقْتِ ناهاره!", written: "{ظُهْر} اَسْت. وَقْتِ ناهار اَسْت!", en: "It's noon. Time for lunch!" },
          { who: "Reza", fa: "پَس بیا بِریم!", written: "پَس بیا بِرَویم!", en: "Then come on, let's go!" },
        ],
        note: "چَنْده, ظُهْره and ناهاره end in the spoken ـه, *is*; Unit 4 covers it.",
      },
      { type: "practice", group: 4 },
      {
        type: "quiz",
        questions: [
          { prompt: "ع with a dot above is which letter? Type it.", lang: "fa", answers: ["غ"], explain: "غ, *gheyn*." },
          { prompt: "Transliterate غَذا.", lang: "translit", answers: ["ghaza", "ghazâ"], explain: "غَذا, *ghazâ*: food." },
          {
            prompt: "Which means *west*: عَرَب or غَرْب? Type the Persian word.",
            lang: "fa",
            answers: ["غرب"],
            explain: "غَرْب, *gharb*. عَرَب is *arab*.",
          },
        ],
      },
    ],
  },
  {
    slug: "fe-to-gaf",
    title: "ف ق ک گ: loops and tall strokes",
    summary: "ف and ق share a loop (one dot or two); ک and گ share a tall slanting stroke, and گ has a second one.",
    register: "written",
    kinds: ["script"],
    showTranslit: true,
    source: SOURCE,
    vocab: [
      { fa: "کوه", en: "mountain", topic: "nature" },
      { fa: "گُرْبه", en: "cat", topic: "animals" },
      { fa: "فَرْدا", en: "tomorrow", topic: "time" },
      { fa: "قَهْوه", en: "coffee", topic: "food" },
      { fa: "قَنْد", en: "sugar lump", topic: "food" },
      { fa: "کُل", en: "all, the whole", topic: "describing" },
      { fa: "گُل", en: "flower", topic: "nature" },
    ],
    blocks: [
      {
        type: "idea",
        text: "ف is *f*, and ق (two dots; it dips below the line only at the end of a word) is written *q* but sounds like غ; ک is *k*, and گ, with its extra stroke, is *g*.",
      },
      { type: "letters", chars: ["ف", "ق", "ک", "گ"] },
      {
        type: "text",
        text: "ق sounds the same as غ in Iranian Persian; the course writes it *q* only to show the spelling. گ is one of the four Persian letters: the extra stroke turns *k* into *g*.",
      },
      { type: "heading", text: "Letters joining into words" },
      {
        type: "build",
        items: [
          { word: "فارْسی", en: "Persian (the language)" },
          { word: "قَنْد", en: "sugar lump" },
          { word: "کِتاب", en: "book" },
          { word: "گُل", en: "flower" },
        ],
      },
      {
        type: "examples",
        items: [
          { fa: "کوه", en: "mountain" },
          { fa: "گُرْبه", en: "cat" },
          { fa: "فَرْدا", en: "tomorrow" },
          { fa: "قَهْوه", en: "coffee" },
          { fa: "فیل", en: "elephant" },
        ],
      },
      {
        type: "pair",
        title: "One stroke more",
        a: { fa: "کُل", en: "all, the whole" },
        b: { fa: "گُل", en: "flower" },
        diff: "The second stroke over ک makes گ: *kol* becomes *gol*.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "Where ق sits",
        text: "At the start or in the middle of a word ف and ق have the same shape, and only the dots tell them apart: فـ has one, قـ two. At the end of a word ف sits on the line while ق dips below it; when you write by hand, keep the bowl of ق deep, or it reads as ف.",
      },
      {
        type: "callout",
        kind: "culture",
        title: "Tea with a sugar lump",
        text: "Many Iranians drink tea with قَنْد, a lump of sugar held in the mouth while sipping, instead of stirring sugar into the glass.",
      },
      { type: "practice", group: 5 },
      {
        type: "quiz",
        questions: [
          { prompt: "Type the letter for *g*.", lang: "fa", answers: ["گ"], explain: "گ, *gâf*: two slanting strokes." },
          { prompt: "Transliterate کِتاب.", lang: "translit", answers: ["ketab", "ketâb"], explain: "کِتاب, *ketâb*: book." },
          { prompt: "How many dots does ق have? Type the number.", lang: "en", answers: ["2", "two"], explain: "Two, above: ق, *qâf*." },
        ],
      },
    ],
  },
  {
    slug: "lam-to-vav",
    title: "ل م ن و: و is v, u or o",
    summary: "ل م ن join both ways; و never joins forward and does three jobs: the consonant v and the vowels u and o.",
    register: "written",
    kinds: ["script"],
    showTranslit: true,
    source: SOURCE,
    vocab: [
      { fa: "نان", en: "bread", topic: "food" },
      { fa: "مو", en: "hair", topic: "body" },
      { fa: "لیوان", en: "glass (for drinking)", topic: "home" },
      { fa: "وَقْت", en: "time", topic: "time" },
      { fa: "تُو", en: "you (to a friend)", topic: "people" },
      { fa: "شُما", en: "you (polite, or more than one)", topic: "people" },
      { fa: "نام", en: "name (formal)", topic: "everyday" },
    ],
    blocks: [
      {
        type: "idea",
        text: "و is *v* at the start of a word and between vowels, usually the vowel *u* after a consonant, and in some words *o*.",
      },
      { type: "letters", chars: ["ل", "م", "ن", "و"] },
      {
        type: "text",
        text: "ل is a tall stroke with a curved tail; م is a small round head; ن is a bowl with one dot above, like a deeper ب. و never joins the letter after it. One letter serving as a vowel and as a consonant is normal in Persian: ی works the same way (next lesson).",
      },
      { type: "heading", text: "Letters joining into words" },
      {
        type: "build",
        items: [
          { word: "نان", en: "bread" },
          { word: "مو", en: "hair" },
          { word: "لیوان", en: "glass (for drinking)" },
          { word: "مِهْمان", en: "guest" },
        ],
      },
      {
        type: "examples",
        items: [
          { fa: "وَقْت", en: "time", note: "*v*: و at the start of a word." },
          { fa: "روز", en: "day", note: "*u*: و after a consonant." },
          { fa: "تُو", en: "you (to a friend)", note: "*o*: one of a set of common words where و spells *o*." },
          { fa: "لَب", en: "lip" },
          { fa: "میوه", en: "fruit" },
        ],
      },
      {
        type: "pair",
        title: "The last letter",
        a: { fa: "نان", en: "bread" },
        b: { fa: "نام", en: "name (formal)" },
        diff: "The words differ only at the end: ن is a bowl with a dot, م a small loop with a tail.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "Reading every و as v",
        text: "At the start of a word و is *v* (وَقْت, *vaqt*), and between vowels too (لیوان, *livân*). After a consonant it is usually the vowel *u* (روز, *ruz*), and in some common words *o*: تُو, *you*, is *to*. The transliteration always tells you which.",
      },
      {
        type: "callout",
        kind: "culture",
        title: "Two words for “you”",
        text: "تُو (*to*) is for family, friends and children; شُما (*shomâ*) is for everyone else, and for more than one person. When unsure, use شُما.",
      },
      { type: "practice", group: 6 },
      {
        type: "quiz",
        questions: [
          { prompt: "Transliterate نان.", lang: "translit", answers: ["nan", "nân"], explain: "نان, *nân*: bread (spoken *nun*)." },
          { prompt: "Type the letter that can be *v*, *u* or *o*.", lang: "fa", answers: ["و"], explain: "و, *vâv*." },
          { prompt: "Transliterate لیوان.", lang: "translit", answers: ["livan", "livân"], explain: "لیوان, *livân*: between vowels و is *v*." },
        ],
      },
    ],
  },
  {
    slug: "he-and-ye",
    title: "ه ی: the shape-shifting he, and ye",
    summary: "ه changes shape more than any other letter and is usually silent at the end of a word; ی is y, the vowel i, or part of ey.",
    register: "written",
    kinds: ["script"],
    showTranslit: true,
    source: SOURCE,
    vocab: [
      { fa: "هَوا", en: "air, weather", topic: "weather" },
      { fa: "ماه", en: "moon, month", topic: "time" },
      { fa: "یَخ", en: "ice", topic: "weather" },
      { fa: "یِک", en: "one", topic: "numbers" },
      { fa: "کی", en: "who", topic: "everyday" },
      { fa: "کَی", en: "when", topic: "everyday" },
      { fa: "یَلْدا", en: "Yalda, the longest night", topic: "time" },
    ],
    blocks: [
      {
        type: "idea",
        text: "At the end of a word ه usually just shows the vowel *e*; ی is *y*, the long vowel *i*, or the second half of *ey*.",
      },
      { type: "letters", chars: ["ه", "ی"] },
      {
        type: "text",
        text: "ه looks very different in each position: a small loop on its own (ه); a double loop at the start of a joined group (هـ), which gives it the name *he-ye do-cheshm*, “two-eyed he”; a different looped shape in the middle (ـهـ); and a small loop hanging from the line at the end (ـه). ی has two dots below at the start and in the middle of a word, but in Persian none at the end.",
      },
      { type: "heading", text: "Letters joining into words" },
      {
        type: "build",
        items: [
          { word: "یَخ", en: "ice" },
          { word: "کوه", en: "mountain" },
          { word: "شَهْر", en: "city" },
          { word: "میوه", en: "fruit" },
        ],
      },
      {
        type: "examples",
        items: [
          { fa: "هَوا", en: "air, weather" },
          { fa: "خانه", en: "house, home", note: "A silent ه: *khâne*." },
          { fa: "ماه", en: "moon, month", note: "A real *h* after ا: *mâh*." },
          { fa: "سیب", en: "apple" },
          { fa: "یِک", en: "one" },
        ],
      },
      {
        type: "pair",
        title: "Who or when?",
        a: { fa: "کی", en: "who" },
        b: { fa: "کَی", en: "when" },
        diff: "Unmarked, both are written [کی|ki / key]. In *ki* the ی is the vowel *i*; in *key* a zabar before it makes the sound *ey*.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "Saying the final ه",
        text: "At the end of a word, after a consonant, ه is usually silent and only shows the vowel *e*: خانه is *khâne*, not *khâneh*, and میوه is *mive*. It is a real *h* after ا or the vowel و (ماه *mâh*, کوه *kuh*) and in a few words like دَهْ (*dah*, ten).",
      },
      {
        type: "callout",
        kind: "culture",
        title: "Yalda night",
        text: "شَبِ یَلْدا, the longest night of the year (around 21 December), is spent with family over watermelon and pomegranates, nuts, and readings from Hafez.",
      },
      { type: "practice", group: 7 },
      {
        type: "quiz",
        questions: [
          { prompt: "Transliterate خانه.", lang: "translit", answers: ["khane", "khâne"], explain: "خانه, *khâne*: the final ه is silent." },
          {
            prompt: "Is the ه in ماه (moon) pronounced? Type yes or no.",
            lang: "en",
            answers: ["yes"],
            explain: "Yes: after ا it is a real *h*, *mâh*.",
          },
          { prompt: "Type the letter for *y*.", lang: "fa", answers: ["ی"], explain: "ی, *ye*." },
        ],
      },
    ],
  },
  {
    slug: "digits",
    title: "Persian digits ۰ to ۹",
    summary: "Persian has its own digits, written left to right like Western ones, even inside a right-to-left line.",
    register: "written",
    kinds: ["script"],
    showTranslit: true,
    source: `${SOURCE} Number names after Thackston, An Introduction to Persian.`,
    vocab: [
      { fa: "صِفْر", en: "zero", topic: "numbers" },
      { fa: "یِک", en: "one", topic: "numbers" },
      { fa: "دُو", en: "two", topic: "numbers" },
      { fa: "سه", en: "three", topic: "numbers" },
      { fa: "چَهار", en: "four", topic: "numbers" },
      { fa: "پَنْج", en: "five", topic: "numbers" },
      { fa: "شِش", en: "six", topic: "numbers" },
      { fa: "هَفْت", en: "seven", topic: "numbers" },
      { fa: "هَشْت", en: "eight", topic: "numbers" },
      { fa: "نُهْ", en: "nine", topic: "numbers" },
      { fa: "دَهْ", en: "ten", topic: "numbers" },
    ],
    blocks: [
      {
        type: "idea",
        text: "Persian digits read **left to right**, even inside Persian text: ۱۴۰۵ is *1405*.",
      },
      {
        type: "table",
        headers: ["Digit", "Value", "In words"],
        rows: [
          ["۰", "0", "صِفْر"],
          ["۱", "1", "یِک"],
          ["۲", "2", "دُو"],
          ["۳", "3", "سه"],
          ["۴", "4", "چَهار"],
          ["۵", "5", "پَنْج"],
          ["۶", "6", "شِش"],
          ["۷", "7", "هَفْت"],
          ["۸", "8", "هَشْت"],
          ["۹", "9", "نُهْ"],
        ],
      },
      {
        type: "text",
        text: "In everyday speech *chahâr* (4) is often said *châr*. Persian also has its own decimal sign, ٫, so ۲٫۵ is *2.5*; by hand it is often written as a slash, ۲/۵.",
      },
      {
        type: "examples",
        items: [
          { fa: "۱۴۰۵", en: "1405, a year in the Persian calendar" },
          { fa: "۲۵", en: "25" },
          { fa: "۱۰۰", en: "100" },
          { fa: "۰۹۱۲", en: "0912, the start of many Iranian mobile numbers" },
        ],
      },
      {
        type: "pair",
        title: "Two digits that fool learners",
        a: { fa: "۵", en: "5 (it looks like a Western zero)" },
        b: { fa: "۰", en: "0 (just a dot)" },
        diff: "The Persian ۵ is round like a Western 0, and the Persian 0 is only a dot. So ۵۰ is *50*.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "Reading a number right to left",
        text: "The line runs right to left, but a number inside it still reads left to right: in «۱۲۰ تُومان» the number is *120*, not *021*.",
      },
      {
        type: "callout",
        kind: "culture",
        title: "The Persian calendar",
        text: "Iran uses a solar calendar whose year starts at Nowruz, the spring equinox, around 21 March. The year 1405 began in March 2026.",
      },
      { type: "practice", group: 8 },
      {
        type: "quiz",
        questions: [
          { prompt: "Type the Persian digit for 7.", lang: "fa", answers: ["۷"], explain: "۷, *haft*." },
          {
            prompt: "What number is ۱۴۰۵? Type it in Western digits.",
            lang: "en",
            answers: ["1405"],
            explain: "*1405*: the digits read left to right.",
          },
          { prompt: "What is ۰? Type the number.", lang: "en", answers: ["0", "zero"], explain: "۰ is zero: a single dot." },
        ],
      },
    ],
  },
];
