import type { Lesson } from "../types";

// Unit 4, the core sentence: the first of the Pareto-ordered grammar units.
// Spoken Tehrani first, written beneath. Examples are original.

const SOURCE =
  "Mahootian, Persian (Routledge Descriptive Grammars), on word order, the copula, negation and questions; Thackston, An Introduction to Persian; Stilo, Talattof and Clinton, Modern Persian: Spoken and Written, for the Tehrani forms.";

export const coreSentence: Lesson[] = [
  {
    slug: "verb-last",
    title: "The verb comes last, and its ending says who",
    summary: "Subject, object, verb: and because the verb's ending names the subject, the pronoun is usually left out.",
    register: "both",
    kinds: ["grammar", "word-order"],
    source: SOURCE,
    vocab: [
      { fa: "خَریدَن", en: "to buy", topic: "verbs" },
      { fa: "خُورْدَن", en: "to eat; to drink", topic: "verbs" },
      { fa: "حَرْف زَدَن", en: "to talk, to speak", topic: "verbs" },
      { fa: "ما", en: "we", topic: "people" },
      { fa: "اونا", written: "آن‌ها", en: "they", topic: "people" },
      { fa: "عَدَد", en: "number; piece (when counting)", topic: "numbers" },
    ],
    blocks: [
      {
        type: "idea",
        text: "The core Persian sentence is **subject – object – verb**, and the verb's **ending names the subject**, so a pronoun like *I* or *we* is usually left out.",
      },
      {
        type: "text",
        text: "Whatever else the sentence contains (when, where, with whom) normally comes before the verb too; the main exception in speech is a place you're going to (see below). The ending on the verb says who is acting, which is why Persian so often drops the subject: می‌خَرَم already means *I buy*. The endings, with the verb *to buy* in the present tense:",
      },
      {
        type: "table",
        headers: ["Who", "Ending", "Spoken", "Written"],
        rows: [
          ["I (مَن)", "-am", "می‌خَرَم", "می‌خَرَم"],
          ["you (تُو)", "-i", "می‌خَری", "می‌خَری"],
          ["he, she, it (اون; written او for people, آن for things)", "-e / written -ad", "می‌خَره", "می‌خَرَد"],
          ["we (ما)", "-im", "می‌خَریم", "می‌خَریم"],
          ["you (شُما)", "-in / written -id", "می‌خَرین", "می‌خَرید"],
          ["they (اونا, written آن‌ها)", "-an / written -and", "می‌خَرَن", "می‌خَرَنْد"],
        ],
      },
      { type: "heading", text: "Core examples" },
      {
        type: "examples",
        items: [
          { fa: "مَن نون {می‌خَرَم}.", written: "مَن نان {می‌خَرَم}.", en: "I buy bread. / I'm buying bread. / I'll buy bread." },
          { fa: "مَرْیَم قَهْوه {می‌خُوره}.", written: "مَرْیَم قَهْوه {می‌خُورَد}.", en: "Maryam drinks coffee." },
          { fa: "اونا فارْسی {حَرْف می‌زَنَن}.", written: "آن‌ها فارْسی {حَرْف می‌زَنَنْد}.", en: "They speak Persian." },
          {
            fa: "فَرْدا {می‌ریم}.",
            written: "فَرْدا {می‌رَویم}.",
            en: "We're going tomorrow.",
            note: "No *we* in sight: the ending ـیم says it.",
          },
        ],
      },
      { type: "heading", text: "Contrast pair" },
      {
        type: "pair",
        title: "The ending says who",
        a: { fa: "{می‌خَرَم}.", en: "I'll buy it." },
        b: { fa: "{می‌خَرَن}.", written: "{می‌خَرَنْد}.", en: "They'll buy it." },
        diff: "The pronoun can go because the ending carries it: *-am* is *I*, *-an* (written *-and*) is *they*.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "The object after the verb",
        text: "In a neutral sentence the object comes before the verb; English order sounds wrong. Speech does allow a place you're going to after the verb (می‌رَم خونه, *I'm going home*), but a plain object like نون stays before the verb.",
        wrong: { fa: "مَن {می‌خَرَم} نون.", written: "مَن {می‌خَرَم} نان.", en: "(English order)" },
        right: { fa: "مَن نون {می‌خَرَم}.", written: "مَن نان {می‌خَرَم}.", en: "I buy bread." },
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "At the bakery",
        lines: [
          { who: "Customer", fa: "سَلام، نون {دارین}؟", written: "سَلام، نان {دارید}؟", en: "Hello, do you have bread?" },
          { who: "Baker", fa: "بَله. چَنْد تا {می‌خوایین}؟", written: "بَله. چَنْد عَدَد {می‌خواهید}؟", en: "Yes. How many would you like?" },
          { who: "Customer", fa: "دُو تا، مِرْسی.", written: "دُو عَدَد، مُتَشَکِّرَم.", en: "Two, thanks." },
        ],
        note: "Not one subject pronoun: the endings do the work. دارین is *you have* and می‌خوایین *you want*, both in the polite plural *you*.",
      },
      {
        type: "quiz",
        questions: [
          {
            prompt: "Where does the verb go in a neutral Persian sentence? Type first or last.",
            lang: "en",
            answers: ["last", "at the end", "end", "the end"],
            explain: "Last: مَن نان می‌خَرَم, literally *I bread buy*.",
          },
          {
            prompt: "Write *we buy* (one word).",
            lang: "fa",
            answers: ["می‌خریم"],
            explain: "می‌خَریم: *-im* is *we*, in speech and writing.",
          },
          {
            prompt: "In speech, *they buy* is…? Type it in Persian script.",
            lang: "fa",
            answers: ["می‌خرن"],
            explain: "می‌خَرَن (*mikharan*); the written form is می‌خَرَنْد.",
          },
        ],
      },
    ],
  },
  {
    slug: "to-be",
    title: "Am, is, are: short endings and اَسْت",
    summary: "To be is usually a short ending on the word before it; the separate word اَسْت belongs to writing, and speech says ـه.",
    register: "both",
    kinds: ["grammar"],
    source: SOURCE,
    vocab: [
      { fa: "سَرْد", en: "cold", topic: "weather" },
      { fa: "خُوشْحال", en: "happy, glad", topic: "feelings" },
      { fa: "آفْتابی", en: "sunny", topic: "weather" },
      { fa: "بیرون", en: "outside", topic: "places" },
      { fa: "کَمی", en: "a little", topic: "describing" },
      { fa: "وَلی", en: "but", topic: "everyday" },
    ],
    blocks: [
      {
        type: "idea",
        text: "*To be* is usually a **short ending** on the word before it: خوبَم, *I'm fine*. For *is*, writing uses the separate word **اَسْت**; speech, after a consonant, uses the ending **ـه** (*-e*).",
      },
      {
        type: "table",
        caption: "خوب (good, fine) with *to be*",
        headers: ["", "Spoken", "Written"],
        rows: [
          ["I am", "خوبَم", "خوبَم"],
          ["you are (تُو)", "خوبی", "خوبی"],
          ["he, she, it is", "خوبه", "خوب اَسْت"],
          ["we are", "خوبیم", "خوبیم"],
          ["you are (شُما)", "خوبین", "خوبید"],
          ["they are", "خوبَن", "خوبَنْد"],
        ],
      },
      {
        type: "text",
        text: "After a vowel the spoken *is* changes: after ا it matches writing, کُجاسْت؟ (*kojâst?*, where is it?), and after ی it is *-ye*: آفْتابیه (*âftâbiye*, it's sunny). When the word before ends in a vowel, written Persian often uses the full verb instead: هَسْتَم، هَسْتی، هَسْت، هَسْتیم، هَسْتید، هَسْتَنْد, as in کُجا هَسْتید؟ (lesson 4.3 shows its negative, نیسْت).",
      },
      { type: "heading", text: "Core examples" },
      {
        type: "examples",
        items: [
          { fa: "مَن {مُعَلِّمَم}.", en: "I'm a teacher." },
          { fa: "هَوا {سَرْده}.", written: "هَوا {سَرْد اَسْت}.", en: "It's cold (the weather is cold)." },
          { fa: "{کُجایین}؟", written: "{کُجا هَسْتید}؟", en: "Where are you?" },
          { fa: "بَچّه‌ها {خُوشْحالَن}.", written: "بَچّه‌ها {خُوشْحالَنْد}.", en: "The children are happy." },
        ],
      },
      { type: "heading", text: "Contrast pair" },
      {
        type: "pair",
        title: "Written or spoken *is*",
        a: { fa: "هَوا {سَرْد اَسْت}.", en: "It's cold. (written)" },
        b: { fa: "هَوا {سَرْده}.", en: "It's cold. (spoken)" },
        diff: "Writing uses the separate word اَسْت; speech attaches ـه (*-e*) to the word before. Everything else stays the same.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "اَسْت in conversation",
        text: "Saying اَسْت in conversation sounds like reading a newspaper aloud. In speech, *is* after a consonant is the ending ـه.",
        wrong: { fa: "این {خوب اَسْت}.", en: "This is good. (in conversation)" },
        right: { fa: "این {خوبه}.", en: "This is good." },
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "How's the weather?",
        lines: [
          { who: "Sina", fa: "هَوا {چِطُوره}؟", written: "هَوا {چِطُور اَسْت}؟", en: "How's the weather?" },
          {
            who: "Parisa",
            fa: "یه کَم {سَرْده}، وَلی {آفْتابیه}.",
            written: "کَمی {سَرْد اَسْت}، وَلی {آفْتابی اَسْت}.",
            en: "It's a bit cold, but it's sunny.",
          },
          { who: "Sina", fa: "پَس بیرون می‌ریم؟", written: "پَس بیرون می‌رَویم؟", en: "So are we going out?" },
          { who: "Parisa", fa: "آره، بِریم!", written: "بَله، بِرَویم!", en: "Yes, let's go!" },
        ],
        note: "سَرْده and آفْتابیه (*âftâbiye*) both end in the spoken *is*.",
      },
      {
        type: "quiz",
        questions: [
          {
            prompt: "Write *It's cold* the spoken way.",
            lang: "fa",
            answers: ["سرده", "هوا سرده"],
            explain: "سَرْده: the spoken *is* is ـه.",
          },
          {
            prompt: "Write *It's cold* the written way, with اَسْت.",
            lang: "fa",
            answers: ["سرد است", "هوا سرد است"],
            explain: "سَرْد اَسْت.",
          },
          { prompt: "Translate: کُجایین؟", lang: "en", answers: ["where are you", "where are you?"], explain: "*kojâyin?*: the spoken form of کُجا هَسْتید." },
        ],
      },
    ],
  },
  {
    slug: "negation",
    title: "Not: نیسْت, and نـ on the verb",
    summary: "The negative of “is” is نیسْت; every other verb takes نـ at the front, said ne before می‌.",
    register: "both",
    kinds: ["grammar"],
    source: SOURCE,
    vocab: [
      { fa: "خَسْته", en: "tired", topic: "feelings" },
      { fa: "هیچ‌وَقْت", en: "never", topic: "time" },
      { fa: "مُشْکِل", en: "problem", topic: "everyday" },
      { fa: "سینِما", en: "cinema", topic: "places" },
      { fa: "تَوانِسْتَن", en: "to be able, can", topic: "verbs" },
    ],
    blocks: [
      {
        type: "idea",
        text: "Negation goes **on the verb**: *is not* is **نیسْت**, and every other verb takes **نـ** (*na-*) at the front, said *ne* before می.",
      },
      {
        type: "text",
        text: "نیسْت (*nist*) is the same in speech and writing, and takes the usual endings: نیسْتَم (*I'm not*), نیسْتی, نیسْت, نیسْتیم, نیسْتین (written نیسْتید), نیسْتَن (written نیسْتَنْد). Any other verb adds نـ (*na-*), with a ی before a vowel: نَیومَدی (*you didn't come*; written نَیامَدی). Before می it is said *ne*: نِمی‌خَرَم (*I don't buy*). In a compound verb it goes on the verb part: حَرْف نِمی‌زَنَم (*I don't speak*).",
      },
      { type: "heading", text: "Core examples" },
      {
        type: "examples",
        items: [
          { fa: "{خَسْته نیسْتَم}.", en: "I'm not tired." },
          { fa: "قَهْوه {نِمی‌خُورَم}.", en: "I don't drink coffee." },
          { fa: "دیروز {نَیومَد}.", written: "دیروز {نَیامَد}.", en: "He didn't come yesterday. / She didn't come yesterday." },
          { fa: "اینْجا {سَرْد نیسْت}.", en: "It isn't cold here." },
        ],
      },
      { type: "heading", text: "Contrast pair" },
      {
        type: "pair",
        title: "Yes and no",
        a: { fa: "{می‌خَرَم}.", en: "I'll buy it." },
        b: { fa: "{نِمی‌خَرَم}.", en: "I won't buy it." },
        diff: "Put نـ in front of the verb; before می it is said *ne*: *mikharam* → *nemikharam*.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "Never, with a positive verb",
        text: "In a statement, هیچ‌وَقْت (*never*) and the other هیچ words need a negative verb too: literally *never I-don't-go*. A positive verb there is a classic learner error.",
        wrong: { fa: "هیچ‌وَقْت {می‌رَم}.", written: "هیچ‌وَقْت {می‌رَوَم}.", en: "(meant: I never go)" },
        right: { fa: "هیچ‌وَقْت {نِمی‌رَم}.", written: "هیچ‌وَقْت {نِمی‌رَوَم}.", en: "I never go." },
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "Are you coming?",
        lines: [
          { who: "Arash", fa: "میای سینِما؟", written: "به سینِما می‌آیی؟", en: "Are you coming to the cinema?" },
          {
            who: "Leila",
            fa: "نَه، {نِمی‌تونَم}. کار دارَم.",
            written: "نَه، {نِمی‌تَوانَم}. کار دارَم.",
            en: "No, I can't. I've got things to do.",
          },
          { who: "Arash", fa: "فَرْدا چی؟", written: "فَرْدا چِطُور؟", en: "What about tomorrow?" },
          { who: "Leila", fa: "فَرْدا {مُشْکِلی نیسْت}!", en: "Tomorrow's no problem!" },
        ],
        note: "نِمی‌تونَم is the spoken *I can't*; مُشْکِلی نیسْت, *there's no problem*, is the same in writing.",
      },
      {
        type: "quiz",
        questions: [
          { prompt: "Write *I'm not* (the negative of هَسْتَم).", lang: "fa", answers: ["نیستم"], explain: "نیسْتَم, *nistam*." },
          {
            prompt: "Make it negative: می‌خَرَم (I buy).",
            lang: "fa",
            answers: ["نمی‌خرم"],
            explain: "نِمی‌خَرَم: the نـ before می is said *ne*.",
          },
          {
            prompt: "Write *I never go* the spoken way.",
            lang: "fa",
            answers: ["هیچ‌وقت نمی‌رم", "هیچ وقت نمی‌رم", "من هیچ‌وقت نمی‌رم"],
            explain: "هیچ‌وَقْت نِمی‌رَم: the verb stays negative after هیچ‌وَقْت.",
          },
        ],
      },
    ],
  },
  {
    slug: "questions",
    title: "Asking questions",
    summary: "A yes/no question is the statement with a rising voice; a question word goes where the answer would be.",
    register: "both",
    kinds: ["grammar", "word-order"],
    source: SOURCE,
    vocab: [
      { fa: "کُجا", en: "where", topic: "everyday" },
      { fa: "چِطُور", en: "how", topic: "everyday" },
      { fa: "چَنْد", en: "how many; how much (a price)", topic: "numbers" },
      { fa: "آیا", en: "(starts a formal yes/no question)", topic: "everyday" },
      { fa: "اَهْل", en: "from, native of", topic: "places" },
      { fa: "دیر", en: "late", topic: "time" },
    ],
    blocks: [
      {
        type: "idea",
        text: "A yes/no question is the **statement with a rising voice**; a **question word goes where the answer would be**, not to the front.",
      },
      {
        type: "text",
        text: "خَسْته‌ای (*you're tired*) becomes خَسْته‌ای؟ (*are you tired?*) just by raising the voice at the end. Formal writing can start such a question with آیا. A question word stays where the answer would go, usually just before the verb: *Where are you going?* is کُجا می‌ری؟, literally *where you-go?* Unmarked, کی (*ki*, who) and کَی (*key*, when) are spelled the same; the sentence tells you which.",
      },
      {
        type: "table",
        headers: ["Question word", "Meaning", "Example"],
        rows: [
          ["چی (written چه)", "what", "اِسْمِت چیه؟"],
          ["کی (written usually چه کَسی)", "who", "اون کیه؟"],
          ["کُجا", "where", "کُجا می‌ری؟"],
          ["کَی", "when", "کَی میای؟"],
          ["چِرا", "why", "چِرا نَیومَدی؟"],
          ["چِطُور (spoken also چِطُوری)", "how", "چِطُور رَفْتی؟"],
          ["چَنْد", "how many; how much (a price)", "چَنْد سالِته؟"],
        ],
      },
      { type: "heading", text: "Core examples" },
      {
        type: "examples",
        items: [
          { fa: "{کُجا} می‌ری؟", written: "{کُجا} می‌رَوی؟", en: "Where are you going?" },
          { fa: "خَسْته‌ای؟", written: "{آیا} خَسْته‌ای؟", en: "Are you tired?" },
          { fa: "{چِرا} اینْقَدْر دیر اومَدی؟", written: "{چِرا} اینْقَدْر دیر آمَدی؟", en: "Why did you come so late?" },
          { fa: "{چَنْد} سالِته؟", written: "{چَنْد} سال داری؟", en: "How old are you?" },
        ],
      },
      { type: "heading", text: "Contrast pair" },
      {
        type: "pair",
        title: "Statement or question",
        a: { fa: "خَسْته‌ای.", en: "You're tired." },
        b: { fa: "خَسْته‌ای؟", en: "Are you tired?" },
        diff: "The same words; only the voice rises at the end, and writing adds ؟.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "آیا in conversation",
        text: "آیا belongs to formal writing and the news. In conversation it sounds stiff: just raise your voice at the end.",
        wrong: { fa: "{آیا} خَسْته‌ای؟", en: "Are you tired? (in conversation)" },
        right: { fa: "خَسْته‌ای؟", en: "Are you tired?" },
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "Meeting someone new",
        lines: [
          { who: "Reza", fa: "اِسْمِتون {چیه}؟", written: "نامِ شُما {چیسْت}؟", en: "What's your name?" },
          { who: "Maryam", fa: "مَرْیَم. شُما {اَهْلِ کُجایین}؟", written: "مَرْیَم. شُما {اَهْلِ کُجا هَسْتید}؟", en: "Maryam. Where are you from?" },
          { who: "Reza", fa: "اَهْلِ شیرازَم. شُما چی؟", written: "اَهْلِ شیراز هَسْتَم. شُما چِطُور؟", en: "I'm from Shiraz. And you?" },
          { who: "Maryam", fa: "مَن اَهْلِ تِهْرونَم.", written: "مَن اَهْلِ تِهْران هَسْتَم.", en: "I'm from Tehran." },
        ],
        note: "اِسْمِتون and کُجایین are polite forms: *your* and *you are* to one person you address with شُما.",
      },
      {
        type: "quiz",
        questions: [
          {
            prompt: "Which question word means *when*: کی or کَی? Type its transliteration.",
            lang: "translit",
            answers: ["key"],
            explain: "کَی, *key*: when. کی, *ki*, is who.",
          },
          {
            prompt: "Translate: کُجا می‌ری؟",
            lang: "en",
            answers: ["where are you going", "where are you going?", "where do you go", "where are you off to"],
            explain: "*kojâ miri?*: the question word sits before the verb.",
          },
          {
            prompt: "Type the word that can start a formal yes/no question.",
            lang: "fa",
            answers: ["آیا"],
            explain: "آیا (*âyâ*): formal writing only.",
          },
        ],
      },
    ],
  },
  {
    slug: "possessive-endings",
    title: "My, your, his: the possessive endings",
    summary: "My, your and his are endings on the noun; speech and writing use slightly different vowels.",
    register: "both",
    kinds: ["grammar", "suffixes"],
    source: SOURCE,
    vocab: [
      { fa: "کیف", en: "bag", topic: "things" },
      { fa: "اِسْم", en: "name", topic: "everyday" },
      { fa: "ماشین", en: "car", topic: "things" },
      { fa: "اُتاق", en: "room", topic: "home" },
      { fa: "کوچیک", written: "کوچَک", en: "small", topic: "describing" },
      { fa: "گُم کَرْدَن", en: "to lose", topic: "verbs" },
    ],
    blocks: [
      {
        type: "idea",
        text: "*My*, *your* and *his* are **endings on the noun**: کِتابَم, *my book*; کِتابِت, *your book*; کِتابِش, *his* or *her book*.",
      },
      {
        type: "table",
        caption: "کِتاب (book) with each ending",
        headers: ["", "Spoken", "Written"],
        rows: [
          ["my", "کِتابَم", "کِتابَم"],
          ["your (تُو)", "کِتابِت", "کِتابَت"],
          ["his, her, its", "کِتابِش", "کِتابَش"],
          ["our", "کِتابِمون", "کِتابِمان"],
          ["your (شُما)", "کِتابِتون", "کِتابِتان"],
          ["their", "کِتابِشون", "کِتابِشان"],
        ],
      },
      {
        type: "text",
        text: "In writing, after ا or a vowel و the endings take a ی: پایَم (*my foot*). Speech drops the ending's vowel instead: پام (*pâm*), پات، پاش، پامون. One ending covers *his*, *her* and *its*, just as او covers *he* and *she*.",
      },
      { type: "heading", text: "Core examples" },
      {
        type: "examples",
        items: [
          { fa: "{کیفَم} کُجاسْت؟", en: "Where's my bag?" },
          { fa: "{اِسْمِش} چیه؟", written: "{نامَش} چیسْت؟", en: "What's his name? / What's her name?" },
          { fa: "{اُتاقِمون} کوچیکه.", written: "{اُتاقِمان} کوچَک اَسْت.", en: "Our room is small." },
          { fa: "{ماشینِتون} قَشَنْگه.", written: "{ماشینِتان} قَشَنْگ اَسْت.", en: "Your car is beautiful." },
        ],
      },
      { type: "heading", text: "Contrast pair" },
      {
        type: "pair",
        title: "Ending or separate word",
        a: { fa: "{کِتابَم}", en: "my book" },
        b: { fa: "کِتابِ {مَن}", en: "my book (with weight on *my*)" },
        diff: "In speech the ending is the everyday way, and the separate pronoun, joined with the ezafe (Unit 6), puts weight on *my*: کِتابِ مَن, *my book, not yours*. In writing both are common and neutral.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "Mixing the two sets",
        text: "Writing uses *-at*, *-ash*, *-emân* (کِتابَت، کِتابَش، کِتابِمان); speech says *-et*, *-esh*, *-emun* (کِتابِت، کِتابِش، کِتابِمون). Keep to one set within a text.",
        wrong: { fa: "{اُتاقِمون} کوچَک اَسْت.", en: "Our room is small. (spoken ending in a written sentence)" },
        right: { fa: "{اُتاقِمان} کوچَک اَسْت.", en: "Our room is small." },
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "Lost and found",
        lines: [
          { who: "Mina", fa: "{کیفِت} کو؟", written: "{کیفَت} کُجاسْت؟", en: "Where's your bag?" },
          {
            who: "Sam",
            fa: "نِمی‌دونَم! {کیفَم} رُو گُم کَرْدَم.",
            written: "نِمی‌دانَم! {کیفَم} را گُم کَرْدَم.",
            en: "I don't know! I've lost my bag.",
          },
          { who: "Mina", fa: "اینه؟", written: "هَمین اَسْت؟", en: "Is it this one?" },
          { who: "Sam", fa: "آره! مِرْسی.", written: "بَله! مُتَشَکِّرَم.", en: "Yes! Thanks." },
        ],
        note: "کو is the spoken *where is…?*. کیفَم رُو (said *kifamo*): the possessive ending, then the spoken object marker رُو (Unit 6).",
      },
      {
        type: "quiz",
        questions: [
          { prompt: "Write *my book* as one word.", lang: "fa", answers: ["کتابم"], explain: "کِتابَم: *-am* is *my*." },
          {
            prompt: "Write *your book* (to a friend) as one word.",
            lang: "fa",
            answers: ["کتابت"],
            explain: "کِتابِت (*ketâbet*) in speech, کِتابَت (*ketâbat*) in writing: the letters are the same.",
          },
          {
            prompt: "Translate: اِسْمِش چیه؟",
            lang: "en",
            answers: ["what is his name", "what's his name", "what is her name", "what's her name", "what's his or her name", "what is his or her name", "what's its name", "what is its name"],
            explain: "*esmesh chiye?*: *-esh* is *his* or *her*.",
          },
        ],
      },
    ],
  },
];
