import type { Lesson } from "../types";

// Unit 10, longer sentences: "the book that…", clauses with که, if, the
// linking words, object endings and word-building. Spoken Tehrani first,
// written beneath. Examples are original.

const SOURCE =
  "Mahootian, Persian (Routledge Descriptive Grammars), on relative and complement clauses, conditionals, conjunctions, pronominal clitics and derivation; Thackston, An Introduction to Persian; Lazard, A Grammar of Contemporary Persian; the Academy's دستورِ خَطِّ فارسی for the half-space before ای; Stilo, Talattof and Clinton, Modern Persian: Spoken and Written, for the Tehrani forms.";

export const longerSentences: Lesson[] = [
  {
    slug: "the-book-that",
    title: "“The book that…”: ـی + که",
    summary: "To describe a noun with a whole clause, Persian adds ـی to the noun, then که: کِتابی که خَریدَم, the book (that) I bought.",
    register: "both",
    kinds: ["grammar", "word-order"],
    source: SOURCE,
    vocab: [
      { fa: "که", en: "that, which, who (joins a clause)", topic: "everyday" },
      { fa: "چیز", en: "thing", topic: "things" },
      { fa: "کَس", en: "person, someone", topic: "people" },
      { fa: "مَرْد", en: "man", topic: "people" },
      { fa: "پارْک", en: "park", topic: "places" },
      { fa: "سِفارِش دادَن", en: "to order (food, goods)", topic: "verbs" },
      { fa: "گُم شُدَن", en: "to get lost, to go missing", topic: "verbs" },
    ],
    blocks: [
      {
        type: "idea",
        text: "To describe a noun with a whole clause, Persian adds **ـی** to the noun, then **که**, then the clause: کِتابی که خَریدَم, *the book (that) I bought*.",
      },
      {
        type: "text",
        text: "A clause that says which one (a **relative clause**) follows its noun, as in English. The noun takes the ending ـی, and که (*ke*) opens the clause. This ـی is not the *a* of lesson 6.5: here it marks the noun that the clause describes, and the noun can be *the* as well as *a*. که covers *that*, *which*, *who* and *where*, and it cannot be left out the way English often drops *that*. The clause keeps its own verb at its end, and the main verb comes after the whole clause. After a vowel, ـی is spelled as in lesson 6.5: غَذایی که, خانه‌ای که. With a describer, ـی goes on the describer: کِتابِ خوبی که خَریدَم, *the good book I bought*. A name, a pronoun, or a noun with *my* or *your* takes no ـی: عَلی که دیروز اومَد, *Ali, who came yesterday*. A few nouns with ـی + که do the work of English question words: چیزی که, *what* (*the thing that*); کَسی که, *the person who*; جایی که, *where* (*the place that*). Speech often puts اون (*that*) in front: اون کِتابی که خَریدی, *that book you bought*.",
      },
      {
        type: "text",
        text: "When the noun is the object of the main verb, writing puts را right after it, before که: کِتابی را که خَریدَم خوانْدَم, *I read the book I bought*. Speech often puts رُو after the whole clause instead: کِتابی که خَریدَم رُو خونْدَم.",
      },
      { type: "heading", text: "Core examples" },
      {
        type: "examples",
        items: [
          { fa: "{کِتابی که} دیروز خَریدَم خیلی خوبه.", written: "{کِتابی که} دیروز خَریدَم خیلی خوب اَسْت.", en: "The book I bought yesterday is very good." },
          {
            fa: "{دوسْتی که} تو شیراز زِنْدِگی می‌کُنه فَرْدا میاد.",
            written: "{دوسْتی که} دَر شیراز زِنْدِگی می‌کُنَد فَرْدا می‌آیَد.",
            en: "The friend who lives in Shiraz is coming tomorrow.",
          },
          {
            fa: "{چیزی که} گُفْتی دُرُسْته.",
            written: "{چیزی که} گُفْتی دُرُسْت اَسْت.",
            en: "What you said is right.",
            note: "چیزی که, *the thing that*, is the usual *what* when it isn't a question; writing also has آنْچه.",
          },
          { fa: "{جایی که} کار می‌کُنَم نَزْدیکه.", written: "{جایی که} کار می‌کُنَم نَزْدیک اَسْت.", en: "The place where I work is close by." },
        ],
      },
      { type: "heading", text: "Contrast pair" },
      {
        type: "pair",
        title: "Two jobs for ـی",
        a: { fa: "{کِتابی} خَریدَم.", en: "I bought a book. (written style)" },
        b: { fa: "{کِتابی که} خَریدَم گُم شُد.", en: "The book I bought has gone missing." },
        diff: "Without که, ـی is the *a* of lesson 6.5. Followed by که and a clause, it picks out the noun that the clause describes: *the book that I bought*.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "Leaving out که",
        text: "English can drop *that*: *the man I saw*. Persian cannot drop که. Without it, مَرْدی دیدَم is a sentence of its own: *I saw a man*.",
        wrong: { fa: "{مَرْدی} دیدَم ایرانی بود.", en: "(meant: The man I saw was Iranian)" },
        right: { fa: "{مَرْدی که} دیدَم ایرانی بود.", en: "The man I saw was Iranian." },
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "A night out",
        lines: [
          {
            who: "Ali",
            fa: "{رِسْتورانی که} دیشَب رَفْتی خوب بود؟",
            written: "{رِسْتورانی که} دیشَب به آنْجا رَفْتی خوب بود؟",
            en: "Was the restaurant you went to last night good?",
          },
          { who: "Sara", fa: "آره، {غَذایی که} سِفارِش دادَم عالی بود.", written: "بَله، {غَذایی که} سِفارِش دادَم عالی بود.", en: "Yes, the food I ordered was excellent." },
          { who: "Ali", fa: "اِسْمِ رِسْتوران چی بود؟", written: "اِسْمِ رِسْتوران چه بود؟", en: "What was the restaurant called?" },
          {
            who: "Sara",
            fa: "یادَم نیسْت. هَمون {جایی که} کِنارِ پارْکه.",
            written: "یادَم نیسْت. هَمان {جایی که} کِنارِ پارْک اَسْت.",
            en: "I don't remember. You know, the place next to the park.",
          },
        ],
        note: "غَذایی: after ا, ـی is written یی (lesson 6.5). یادَم نیسْت, *I don't remember*, is literally *it isn't in my memory*. هَمون, *that same*, points to something both speakers know. Writing points back to the place inside the clause (به آنْجا, *to there*); speech leaves it out.",
      },
      {
        type: "quiz",
        questions: [
          {
            prompt: "Write *the book that I bought* (three words).",
            lang: "fa",
            answers: ["کتابی که خریدم"],
            explain: "کِتابی که خَریدَم: ـی on the noun, then که, then the clause with its verb last.",
          },
          {
            prompt: "Type the missing word: مَرْدی ___ دیدَم ایرانی بود. (*The man I saw was Iranian.*)",
            lang: "fa",
            answers: ["که"],
            explain: "که: Persian never leaves it out. Without it, مَرْدی دیدَم means *I saw a man*.",
          },
          {
            prompt: "Spoken: *what you said*, as *the thing that you said* (three words).",
            lang: "fa",
            answers: ["چیزی که گفتی"],
            explain: "چیزی که گُفْتی (*chizi ke gofti*).",
          },
          {
            prompt: "Translate: جایی که کار می‌کُنَم نَزْدیکه.",
            lang: "en",
            answers: [
              "the place where i work is close",
              "the place where i work is near",
              "the place where i work is nearby",
              "the place where i work is close by",
              "the place i work is close",
              "the place i work is near",
              "the place i work is nearby",
              "the place i work is close by",
              "where i work is close",
              "where i work is near",
              "where i work is nearby",
              "where i work is close by",
              "the place that i work is close",
              "the place that i work is near",
              "the place that i work is nearby",
              "the place that i work is close by",
            ],
            explain: "*jâyi ke kâr mikonam nazdike*: جایی که, *the place where*.",
          },
        ],
      },
    ],
  },
  {
    slug: "that-clauses",
    title: "که clauses: I know that…, he said that…",
    summary: "After know, say, think and hope, a whole clause follows with که. Reported speech keeps the tense the speaker used: گُفْت که میاد, he said he was coming.",
    register: "both",
    kinds: ["grammar"],
    source: SOURCE,
    vocab: [
      { fa: "فِکْر کَرْدَن", en: "to think", topic: "verbs" },
      { fa: "شِنیدَن", en: "to hear", topic: "verbs" },
      { fa: "اُمیدْوار", en: "hopeful", topic: "feelings" },
      { fa: "خوب شُدَن", en: "to get well, to get better", topic: "verbs" },
      { fa: "حَتْماً", en: "certainly, surely", topic: "everyday" },
    ],
    blocks: [
      {
        type: "idea",
        text: "After *know*, *say*, *think* and *hope*, a whole clause follows with **که** (*that*): می‌دونَم که خَسْته‌ای, *I know (that) you're tired*.",
      },
      {
        type: "text",
        text: "In speech که is often left out: فِکْر می‌کُنَم دیر شُده, *I think it's late*. Writing usually keeps it. Two things work differently from English. First, reported speech keeps the tense the speaker used. If Ali says میام (*I'm coming*), you report عَلی گُفْت که میاد: the person changes to fit who is talking now, but the verb stays in the present, where English shifts it to *he was coming*. Speech also reports without که and keeps the speaker's own person, as if quoting: عَلی گُفْت فَرْدا میام. Second, after verbs of wanting and hoping the clause takes the subjunctive (lesson 8.1): اُمیدْوارَم که بیای, *I hope you come*.",
      },
      { type: "heading", text: "Core examples" },
      {
        type: "examples",
        items: [
          { fa: "{می‌دونَم که} خَسْته‌ای.", written: "{می‌دانَم که} خَسْته‌ای.", en: "I know you're tired." },
          {
            fa: "{فِکْر می‌کُنَم} فَرْدا بارون میاد.",
            written: "{فِکْر می‌کُنَم که} فَرْدا باران می‌آیَد.",
            en: "I think it'll rain tomorrow.",
            note: "Speech often leaves که out; writing keeps it.",
          },
          {
            fa: "عَلی {گُفْت که} دیر میاد.",
            written: "عَلی {گُفْت که} دیر می‌آیَد.",
            en: "Ali said he'd be late.",
            note: "Literally *Ali said that he comes late*: Persian keeps the tense Ali used.",
          },
          {
            fa: "{اُمیدْوارَم که} زود خوب شی.",
            written: "{اُمیدْوارَم که} زود خوب شَوی.",
            en: "I hope you get well soon.",
            note: "After *hope*, the subjunctive. A compound with شُدَن drops بـ (lesson 8.1): خوب شی.",
          },
        ],
      },
      { type: "heading", text: "Contrast pair" },
      {
        type: "pair",
        title: "Quoted, or reported",
        a: { fa: "عَلی گُفْت: «{میام}.»", written: "عَلی گُفْت: «{می‌آیَم}.»", en: "Ali said, “I'm coming.”" },
        b: { fa: "عَلی گُفْت که {میاد}.", written: "عَلی گُفْت که {می‌آیَد}.", en: "Ali said he was coming." },
        diff: "Quoted, the verb is Ali's own: میام, *I come*. Reported with که, only the person changes, to *he* (میاد); the tense stays present, where English shifts it to *was coming*.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "Shifting the tense back",
        text: "English moves a reported verb into the past: *he said he would come*. Persian keeps the tense of the words as they were said.",
        wrong: { fa: "گُفْت که فَرْدا {میومَد}.", en: "(meant: He said he would come tomorrow)" },
        right: { fa: "گُفْت که فَرْدا {میاد}.", written: "گُفْت که فَرْدا {می‌آیَد}.", en: "He said he would come tomorrow." },
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "News of Mina",
        lines: [
          { who: "Maryam", fa: "{شِنیدَم که} مینا ایرانه.", written: "{شِنیدَم که} مینا دَر ایران اَسْت.", en: "I heard Mina's in Iran." },
          {
            who: "Reza",
            fa: "آره، {گُفْت که} تا آخَرِ ماه می‌مونه.",
            written: "بَله، {گُفْت که} تا آخَرِ ماه می‌مانَد.",
            en: "Yes, she said she's staying until the end of the month.",
          },
          {
            who: "Maryam",
            fa: "{فِکْر می‌کُنی} وَقْت داره ما رُو بِبینه؟",
            written: "{فِکْر می‌کُنی که} وَقْت دارَد ما را بِبینَد؟",
            en: "Do you think she has time to see us?",
          },
          { who: "Reza", fa: "حَتْماً داره.", written: "حَتْماً دارَد.", en: "I'm sure she does." },
        ],
        note: "گُفْت که … می‌مونه keeps Mina's own present tense. After فِکْر می‌کُنی speech drops که; writing keeps it. Persian verbs don't show *he* or *she*: گُفْت is *she said* here because Mina is a woman's name.",
      },
      {
        type: "quiz",
        questions: [
          { prompt: "Written: *I know that…* (two words).", lang: "fa", answers: ["می‌دانم که"], explain: "می‌دانَم که; spoken می‌دونَم که." },
          {
            prompt: "Ali said «فَرْدا میام.» Report it: عَلی گُفْت که فَرْدا ___ (spoken; one word).",
            lang: "fa",
            answers: ["میاد", "می‌آد"],
            explain: "میاد: the person changes to *he*, and the tense stays present.",
          },
          {
            prompt: "In speech, can که be left out after فِکْر می‌کُنَم? Type yes or no.",
            lang: "en",
            answers: ["yes"],
            explain: "Yes: فِکْر می‌کُنَم دیر شُده, *I think it's late*. Writing usually keeps it.",
          },
          {
            prompt: "Spoken: *I hope you come* (to a friend).",
            lang: "fa",
            answers: ["امیدوارم که بیای", "امیدوارم بیای"],
            explain: "اُمیدْوارَم (که) بیای: after *hope*, the subjunctive.",
          },
          {
            prompt: "Translate: شِنیدَم که مینا ایرانه.",
            lang: "en",
            answers: [
              "i heard mina is in iran",
              "i heard that mina is in iran",
              "i heard mina was in iran",
              "i heard that mina was in iran",
              "i've heard that mina's in iran",
              "i have heard mina's in iran",
              "i heard mina's in iran",
              "i heard that mina's in iran",
              "i've heard mina is in iran",
              "i've heard that mina is in iran",
              "i've heard mina's in iran",
              "i have heard mina is in iran",
              "i have heard that mina is in iran",
            ],
            explain: "*shenidam ke minâ irâne*: speech says ایرانه, *is in Iran*, with no preposition.",
          },
        ],
      },
    ],
  },
  {
    slug: "if",
    title: "If: اَگه with real conditions",
    summary: "اَگه (written اَگَر) takes the subjunctive for something that may happen: اَگه بارون بیاد، خونه می‌مونیم, if it rains, we'll stay at home.",
    register: "both",
    kinds: ["grammar"],
    source: SOURCE,
    vocab: [
      { fa: "اَگه", written: "اَگَر", en: "if", topic: "everyday" },
      { fa: "چَتْر", en: "umbrella", topic: "things" },
      { fa: "بُرْدَن", en: "to take (away), to carry", topic: "verbs" },
      { fa: "بیدار شُدَن", en: "to wake up", topic: "verbs" },
      { fa: "زَنْگ زَدَن", en: "to phone, to call", topic: "verbs" },
    ],
    blocks: [
      {
        type: "idea",
        text: "**اَگه** (*age*, written **اَگَر**, *agar*) takes the **subjunctive** for something that may or may not happen: اَگه بارون بیاد، خونه می‌مونیم, *if it rains, we'll stay at home*.",
      },
      {
        type: "text",
        text: "The if-clause usually comes first, followed by a comma. For something that may happen, its verb is the subjunctive (lesson 8.1): اَگه بارون بیاد. The other half is a plain present, which also covers the future (lesson 8.6), or a command. Two other tenses are common after اَگه. Something that may already be so, taken as given, takes the ordinary present: اَگه خَسْته‌ای, *if you're tired*. And the simple past can look ahead, to a moment when something will have happened: اَگه زود رِسیدی, *if you get there early*. Conditions that are not real (*if I knew…*) come in lesson 11.3.",
      },
      { type: "heading", text: "Core examples" },
      {
        type: "examples",
        items: [
          { fa: "{اَگه} بارون بیاد، خونه می‌مونیم.", written: "{اَگَر} باران بیایَد، دَر خانه می‌مانیم.", en: "If it rains, we'll stay at home." },
          { fa: "{اَگه} بِخوای، فَرْدا میام.", written: "{اَگَر} بِخواهی، فَرْدا می‌آیَم.", en: "If you like, I'll come tomorrow." },
          { fa: "{اَگه} خَسْته‌ای، بُرُو بِخواب.", written: "{اَگَر} خَسْته‌ای، بُرُو بِخواب.", en: "If you're tired, go to bed." },
          {
            fa: "{اَگه} زود رِسیدی، زَنْگ بِزَن.",
            written: "{اَگَر} زود رِسیدی، زَنْگ بِزَن.",
            en: "If you get there early, call me.",
            note: "The simple past after اَگه looks ahead: *if (by then) you've got there early*.",
          },
        ],
      },
      { type: "heading", text: "Contrast pair" },
      {
        type: "pair",
        title: "It's raining, or it may rain",
        a: { fa: "اَگه بارون {میاد}، چَتْر بِبَر.", written: "اَگَر باران {می‌آیَد}، چَتْر بِبَر.", en: "If it's raining, take an umbrella." },
        b: { fa: "اَگه بارون {بیاد}، چَتْر بِبَر.", written: "اَگَر باران {بیایَد}، چَتْر بِبَر.", en: "If it rains, take an umbrella." },
        diff: "The ordinary present (میاد) treats the rain as a fact you may not know yet: it may be raining now. The subjunctive (بیاد) treats it as something that may or may not happen.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "*If* that means *whether*",
        text: "English *if* also means *whether*: *I don't know if he's coming*. اَگه never does. Speech puts یا نَه (*or not*) after the question; writing can also start it with آیا (lesson 4.4).",
        wrong: { fa: "نِمی‌دونَم {اَگه} میاد.", en: "(meant: I don't know if he's coming)" },
        right: { fa: "نِمی‌دونَم میاد {یا نَه}.", written: "نِمی‌دانَم {آیا} می‌آیَد {یا نَه}.", en: "I don't know if he's coming." },
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "Weekend plans",
        lines: [
          {
            who: "Sima",
            fa: "{اَگه} فَرْدا هَوا خوب باشه، بِریم کوه؟",
            written: "{اَگَر} فَرْدا هَوا خوب باشَد، به کوه بِرَویم؟",
            en: "If the weather's good tomorrow, shall we go hiking in the mountains?",
          },
          {
            who: "Kian",
            fa: "آره، وَلی {اَگه} بارون اومَد، می‌ریم سینِما.",
            written: "بَله، اَمّا {اَگَر} باران آمَد، به سینِما می‌رَویم.",
            en: "Yes, but if it rains, we'll go to the cinema.",
          },
          {
            who: "Sima",
            fa: "باشه. {اَگه} زودْتَر بیدار شُدی، زَنْگ بِزَن.",
            written: "باشَد. {اَگَر} زودْتَر بیدار شُدی، زَنْگ بِزَن.",
            en: "OK. If you're up early, call me.",
          },
        ],
        note: "باشه (the subjunctive of بودَن) also means *OK*. اَگه بارون اومَد uses the simple past for a day still to come, like اَگه زود رِسیدی. Tehran lies at the foot of the Alborz mountains, and a walk in them is a popular weekend outing.",
      },
      {
        type: "quiz",
        questions: [
          { prompt: "Type the written word for *if*.", lang: "fa", answers: ["اگر"], explain: "اَگَر (*agar*); speech says اَگه (*age*)." },
          {
            prompt: "Spoken: *if it rains*, with the subjunctive (three words).",
            lang: "fa",
            answers: ["اگه بارون بیاد"],
            explain: "اَگه بارون بیاد: بیاد is the spoken subjunctive of آمَدَن.",
          },
          {
            prompt: "Complete with the subjunctive (spoken): اَگه ___، فَرْدا میام. (*If you like, I'll come tomorrow.* One word.)",
            lang: "fa",
            answers: ["بخوای"],
            explain: "بِخوای, the subjunctive of خواسْتَن: *if you want*.",
          },
          {
            prompt: "*I don't know if he's coming*: is this *if* اَگه? Type yes or no.",
            lang: "en",
            answers: ["no"],
            explain: "No: this *if* means *whether*. Say نِمی‌دونَم میاد یا نَه.",
          },
          {
            prompt: "Translate: اَگه خَسْته‌ای، بُرُو بِخواب.",
            lang: "en",
            answers: [
              "if you're tired go to sleep",
              "if you are tired go to sleep",
              "if you're tired go to bed",
              "if you are tired go to bed",
              "if you're tired go and sleep",
              "if you are tired go and sleep",
              "if you're tired go and get some sleep",
              "if you're tired go get some sleep",
              "if you're tired go sleep",
              "if you are tired go sleep",
            ],
            explain: "*age khaste-i, boro bekhâb*: a fact that is already true takes the ordinary present.",
          },
        ],
      },
    ],
  },
  {
    slug: "linking-words",
    title: "Linking words: وَقْتی, چون, وَلی, پَس",
    summary: "When, because, but and so: each starts its own clause, and each clause keeps its verb at the end.",
    register: "both",
    kinds: ["grammar", "word-order"],
    source: SOURCE,
    vocab: [
      { fa: "وَقْتی", en: "when (at the time that)", topic: "time" },
      { fa: "چون", en: "because", topic: "everyday" },
      { fa: "وَلی", en: "but", topic: "everyday" },
      { fa: "اَمّا", en: "but (more formal)", topic: "everyday" },
      { fa: "پَس", en: "then, so", topic: "everyday" },
      { fa: "مَریض", en: "ill, sick", topic: "body" },
    ],
    blocks: [
      {
        type: "idea",
        text: "Four words join two clauses: **وَقْتی** (*when*), **چون** (*because*), **وَلی** (*but*) and **پَس** (*so*). Each starts its own clause, and each clause keeps its verb at the end.",
      },
      {
        type: "text",
        text: "وَقْتی (also وَقْتی که) is *when* for a time; the question *when?* is کَی (lesson 4.4). The وَقْتی clause usually comes first. چون gives the reason; it usually comes second, but it can come first. وَلی is the everyday *but*, in speech and in writing; writing often prefers اَمّا, which is a little more formal. پَس gives the result: *so*, *then*. Like اَگه, وَقْتی can take the simple past for something still to come: وَقْتی رِسیدی، زَنْگ بِزَن, *when you get there, call*.",
      },
      { type: "heading", text: "Core examples" },
      {
        type: "examples",
        items: [
          {
            fa: "{وَقْتی} بَچّه بودَم، تو شیراز زِنْدِگی می‌کَرْدیم.",
            written: "{وَقْتی} بَچّه بودَم، دَر شیراز زِنْدِگی می‌کَرْدیم.",
            en: "When I was a child, we lived in Shiraz.",
          },
          { fa: "اِمْروز نِمیام {چون} مَریضَم.", written: "اِمْروز نِمی‌آیَم {چون} مَریضَم.", en: "I'm not coming today because I'm ill." },
          { fa: "اُتاقَم کوچیکه {وَلی} قَشَنْگه.", written: "اُتاقَم کوچَک اَسْت {وَلی} قَشَنْگ اَسْت.", en: "My room is small but nice." },
          { fa: "دیر شُده، {پَس} بِریم.", written: "دیر شُده اَسْت، {پَس} بِرَویم.", en: "It's late, so let's go." },
        ],
      },
      { type: "heading", text: "Contrast pair" },
      {
        type: "pair",
        title: "The cause, or the result",
        a: { fa: "{چون} بارون میاد، خونه می‌مونیم.", written: "{چون} باران می‌آیَد، دَر خانه می‌مانیم.", en: "Because it's raining, we're staying at home." },
        b: { fa: "بارون میاد، {پَس} خونه می‌مونیم.", written: "باران می‌آیَد، {پَس} دَر خانه می‌مانیم.", en: "It's raining, so we're staying at home." },
        diff: "The same two facts, linked from either end: چون marks the cause, پَس the result. پَس fits a decision or a conclusion, as here.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "کَی is a question",
        text: "*When* in a question is کَی. *When* that joins two clauses is وَقْتی.",
        wrong: { fa: "{کَی} رِسیدَم، زَنْگ زَدَم.", en: "(meant: When I arrived, I called)" },
        right: { fa: "{وَقْتی} رِسیدَم، زَنْگ زَدَم.", en: "When I arrived, I called." },
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "A missed visit",
        lines: [
          { who: "Leila", fa: "دیروز چِرا نَیومَدی؟", written: "دیروز چِرا نَیامَدی؟", en: "Why didn't you come yesterday?" },
          { who: "Arash", fa: "{چون} کار داشْتَم. {وَلی} فَرْدا میام.", written: "{چون} کار داشْتَم. {اَمّا} فَرْدا می‌آیَم.", en: "Because I had things to do. But I'll come tomorrow." },
          { who: "Leila", fa: "باشه. {وَقْتی} رِسیدی، زَنْگ بِزَن.", written: "باشَد. {وَقْتی} رِسیدی، زَنْگ بِزَن.", en: "OK. When you get here, call me." },
          { who: "Arash", fa: "ساعَتِ هَشْت خوبه؟", written: "ساعَتِ هَشْت خوب اَسْت؟", en: "Is eight o'clock good?" },
          { who: "Leila", fa: "آره. {پَس} تا فَرْدا!", written: "بَله. {پَس} تا فَرْدا!", en: "Yes. Till tomorrow, then!" },
        ],
        note: "کار داشْتَم, *I had things to do*, is the everyday reason for not coming. وَقْتی رِسیدی uses the simple past for something still to come, as after اَگه. پَس at the start of a reply is *then, in that case*.",
      },
      {
        type: "quiz",
        questions: [
          { prompt: "Type the word for *because*.", lang: "fa", answers: ["چون"], explain: "چون (*chun*): it starts the clause that gives the reason." },
          { prompt: "Type the more formal word for *but*.", lang: "fa", answers: ["اما"], explain: "اَمّا (*ammâ*); وَلی is the everyday one, in speech and in writing." },
          {
            prompt: "*When* in *when I was a child*: کَی or وَقْتی? Type it.",
            lang: "fa",
            answers: ["وقتی"],
            explain: "وَقْتی joins two clauses; کَی asks *when?*.",
          },
          { prompt: "Spoken: *so let's go* (two words).", lang: "fa", answers: ["پس بریم"], explain: "پَس بِریم (*pas berim*): بِریم is the subjunctive, *let's go*." },
          {
            prompt: "Translate: اِمْروز نِمیام چون مَریضَم.",
            lang: "en",
            answers: [
              "i'm not coming today because i'm ill",
              "i'm not coming today because i'm sick",
              "i am not coming today because i am ill",
              "i am not coming today because i am sick",
              "i'm not coming today because i am ill",
              "i'm not coming today because i am sick",
              "i won't come today because i'm ill",
              "i won't come today because i'm sick",
              "i'm not coming in today because i'm ill",
              "i'm not coming in today because i'm sick",
              "i'm not coming today since i'm ill",
              "i'm not coming today since i'm sick",
              "i'm not coming today as i'm ill",
              "i'm not coming today as i'm sick",
            ],
            explain: "*emruz nemiyâm chun marizam*.",
          },
        ],
      },
    ],
  },
  {
    slug: "object-endings",
    title: "Object endings: دیدَمِش, بِهِش",
    summary: "The endings for my, your, his also mean me, you, him on a verb or a preposition: دیدَمِش, I saw him; بِهِش, to him. Speech uses them; writing prefers او را, به او.",
    register: "both",
    kinds: ["suffixes", "spoken", "grammar"],
    source: SOURCE,
    vocab: [
      { fa: "بِهِش", written: "به او", en: "to him, to her", topic: "everyday" },
      { fa: "باهاش", written: "با او", en: "with him, with her", topic: "everyday" },
      { fa: "دوسْت داشْتَن", en: "to like, to love", topic: "verbs" },
    ],
    blocks: [
      {
        type: "idea",
        text: "The endings for *my, your, his* (lesson 4.5) also mean *me, you, him* on a verb or after a preposition: **دیدَمِش**, *I saw him*; **بِهِش**, *to him*. Speech uses them every day; writing prefers a separate pronoun: او را دیدَم, به او.",
      },
      {
        type: "text",
        text: "The spoken endings are ـَم *me*, ـِت *you*, ـِش *him, her, it*, ـِمون *us*, ـِتون *you* (plural or polite) and ـِشون *them*. On a verb they come after the person ending: دیدَمِت, *I saw you*; دیدیمِشون, *we saw them*. After a vowel the ending loses its own vowel (دیدیش, *didish*, *you saw him*), and the spoken *-e* of *he/she* becomes *-at-* (می‌بینَتِش, *mibinatesh*, *he sees it*); this lesson keeps to verbs that end in a consonant. On a compound verb they go on the first part: دوسْتِت دارَم, *I love you*. Before them, به is said with its ه as a consonant, *beh-*: بِهِش, *to him*; and با becomes باها: باهاش, *with him*. Other prepositions work the same way: اَزَش, *from him*; بَرام, *for me*. In a که clause (lesson 10.1), the ending on a preposition points back to the noun: کَسی که باهاش حَرْف زَدَم, *the person I talked to*. Formal writing prefers a separate pronoun, with را for the object (او را دیدَم) and after a preposition (به او, کَسی که با او حَرْف زَدَم); for a thing it uses آن (آن را). Writing does put endings on a verb, with the written vowels of lesson 4.5 (دیدَمَش, دوسْتَت دارَم), but بِهِش and باهاش are speech only.",
      },
      {
        type: "table",
        caption: "به with each ending",
        headers: ["", "Spoken", "Written"],
        rows: [
          ["to me", "بِهَم", "به مَن"],
          ["to you (تُو)", "بِهِت", "به تُو"],
          ["to him, to her", "بِهِش", "به او"],
          ["to us", "بِهِمون", "به ما"],
          ["to you (شُما)", "بِهِتون", "به شُما"],
          ["to them", "بِهِشون", "به آن‌ها"],
        ],
      },
      { type: "heading", text: "Core examples" },
      {
        type: "examples",
        items: [
          { fa: "دیروز {دیدَمِش}.", written: "دیروز {او را دیدَم}.", en: "I saw him yesterday.", note: "Or *her*: ـِش, like او, doesn't show which." },
          { fa: "{بِهِش} بِگو فَرْدا بیاد.", written: "{به او} بِگو فَرْدا بیایَد.", en: "Tell her to come tomorrow." },
          { fa: "{دوسْتِت} دارَم.", written: "{دوسْتَت} دارَم.", en: "I love you.", note: "Writing has the ending here too, with its written vowel: *dustat*." },
          { fa: "این کِتاب خیلی خوبه، {بِخونِش}.", written: "این کِتاب خیلی خوب اَسْت، {آن را بِخوان}.", en: "This book is very good: read it." },
          { fa: "{باهاش} حَرْف زَدی؟", written: "{با او} حَرْف زَدی؟", en: "Did you talk to him?" },
        ],
      },
      { type: "heading", text: "Contrast pair" },
      {
        type: "pair",
        title: "Pronoun or ending",
        a: { fa: "{اونُو} دیدَم.", written: "{او را} دیدَم.", en: "I saw him. (with weight on *him*)" },
        b: { fa: "{دیدَمِش}.", written: "او را دیدَم.", en: "I saw him." },
        diff: "In speech the ending is the everyday way. The separate pronoun is heavier and puts weight on *him* (*him, not her*), as کِتابِ مَن does for *my* (lesson 4.5). Writing uses the pronoun either way.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "Endings in formal writing",
        text: "Formal prose prefers the separate pronoun, with را for the object or after a preposition; بِهِش and باهاش are speech only.",
        wrong: { fa: "{دیدَمِش} وُ {بِهِش} گُفْتَم.", en: "I saw him and told him. (in a formal letter)" },
        right: { fa: "{او را} دیدَم وَ {به او} گُفْتَم.", en: "I saw him and told him." },
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "A guest for dinner",
        lines: [
          { who: "Mother", fa: "عَلی رُو دیدی؟", written: "عَلی را دیدی؟", en: "Did you see Ali?" },
          { who: "Son", fa: "آره، تو مَدْرِسه {دیدَمِش}.", written: "بَله، دَر مَدْرِسه {او را دیدَم}.", en: "Yes, I saw him at school." },
          { who: "Mother", fa: "{بِهِش} گُفْتی واسهٔ شام بیاد؟", written: "{به او} گُفْتی بَرایِ شام بیایَد؟", en: "Did you tell him to come for dinner?" },
          { who: "Son", fa: "آره، {بِهِش} گُفْتَم. ساعَتِ هَشْت میاد.", written: "بَله، {به او} گُفْتَم. ساعَتِ هَشْت می‌آیَد.", en: "Yes, I told him. He's coming at eight." },
        ],
        note: "بِهِش is به with the ending ـِش; writing says به او. عَلی رُو is the spoken را after a name (lesson 6.7).",
      },
      {
        type: "quiz",
        questions: [
          { prompt: "Spoken: *to him* or *to her* (one word).", lang: "fa", answers: ["بهش"], explain: "بِهِش (*behesh*): به with ـِش." },
          { prompt: "Spoken: *I saw him* (one word).", lang: "fa", answers: ["دیدمش"], explain: "دیدَمِش (*didamesh*): دیدَم, then ـِش." },
          { prompt: "Written: *I saw him*, with را (three words).", lang: "fa", answers: ["او را دیدم"], explain: "او را دیدَم: writing uses the pronoun and را." },
          {
            prompt: "Spoken: *I love you* (two words).",
            lang: "fa",
            answers: ["دوستت دارم"],
            explain: "دوسْتِت دارَم (*dustet dâram*): the ending goes on دوسْت, the first part of the compound.",
          },
          {
            prompt: "Translate: باهاش حَرْف زَدی؟",
            lang: "en",
            answers: [
              "did you talk to him",
              "did you talk to her",
              "did you speak to him",
              "did you speak to her",
              "did you talk with him",
              "did you talk with her",
              "did you speak with him",
              "did you speak with her",
              "have you talked to him",
              "have you talked to her",
              "have you spoken to him",
              "have you spoken to her",
            ],
            explain: "*bâhâsh harf zadi?*: باهاش is با with ـِش.",
          },
        ],
      },
    ],
  },
  {
    slug: "word-building",
    title: "Word-building: ـی, ـگاه, ـچی, ـسْتان",
    summary: "A handful of endings build new words: ایرانی, Iranian; دانِشْگاه, university; پُسْتْچی, postman; بیمارِسْتان, hospital.",
    register: "both",
    kinds: ["suffixes", "spelling"],
    source: SOURCE,
    vocab: [
      { fa: "تِهْرانی", en: "from Tehran; a Tehrani", topic: "people" },
      { fa: "تَنْها", en: "alone", topic: "describing" },
      { fa: "تَنْهایی", en: "being alone, loneliness; on one's own", topic: "feelings" },
      { fa: "فُرودْگاه", en: "airport", topic: "places" },
      { fa: "پُسْت", en: "post, mail", topic: "things" },
      { fa: "پُسْتْچی", en: "postman, postwoman", topic: "people" },
      { fa: "تَماشاچی", en: "spectator", topic: "people" },
      { fa: "بیمارِسْتان", en: "hospital", topic: "places" },
      { fa: "قَهْوه‌ای", en: "brown", topic: "colours" },
      { fa: "سَخْت", en: "hard, difficult", topic: "describing" },
      { fa: "بُزُرْگ شُدَن", en: "to grow up", topic: "verbs" },
      { fa: "اِنْگِلیس", en: "England, Britain", topic: "places" },
      { fa: "آلْمان", en: "Germany", topic: "places" },
    ],
    blocks: [
      {
        type: "idea",
        text: "A handful of endings build new words from old ones: ایران → **ایرانی**, *Iranian*; دانِش → **دانِشْگاه**, *university*; پُسْت → **پُسْتْچی**, *postman*; بیمار → **بیمارِسْتان**, *hospital*.",
      },
      {
        type: "text",
        text: "Knowing a few endings lets you guess words you have never seen. ـی makes a describer from a noun: ایرانی, *Iranian*; تِهْرانی, *from Tehran*. On a describer it makes a noun for the quality: خوب → خوبی, *goodness*; تَنْها → تَنْهایی, *being alone*. This ـی is stressed (*irâní*), unlike the unstressed *a* of lesson 6.5 (*ketâbi*). After ا it is spelled یی. After a silent ه it is often ای after a half-space (قَهْوه → قَهْوه‌ای, *brown*), but often the ه becomes ـگی: خَسْته → خَسْتِگی, *tiredness*; هَفْته → هَفْتِگی, *weekly*. In speech تَنْهایی is also *on my own*: تَنْهایی رَفْتَم, *I went on my own*. ـگاه is *the place of*: دانِش (*knowledge*) → دانِشْگاه; فُرود (*landing*) → فُرودْگاه, *airport*. ـچی, from Turkish, is *a person who does or deals with* something: پُسْتْچی; تَماشا (*watching*) → تَماشاچی, *spectator*. ـسْتان is *the land* or *the place of*: بیمار (*sick*) → بیمارِسْتان, and many place names, such as کُرْدِسْتان and اَفْغانِسْتان.",
      },
      {
        type: "table",
        caption: "Four endings",
        headers: ["Ending", "Makes", "Examples"],
        rows: [
          ["ـی", "a describer: *of, from*", "ایرانی، تِهْرانی"],
          ["ـی", "a noun: *-ness*", "خوبی، تَنْهایی"],
          ["ـگاه", "the place of", "دانِشْگاه، فُرودْگاه"],
          ["ـچی", "a person who does or deals with", "پُسْتْچی، تَماشاچی"],
          ["ـسْتان", "the land or place of", "بیمارِسْتان، کُرْدِسْتان"],
        ],
      },
      { type: "heading", text: "Core examples" },
      {
        type: "examples",
        items: [
          {
            fa: "اون {ایرانیه}، وَلی تو آلْمان بُزُرْگ شُده.",
            written: "او {ایرانی} اَسْت، اَمّا دَر آلْمان بُزُرْگ شُده اَسْت.",
            en: "She's Iranian, but she grew up in Germany.",
          },
          { fa: "خواهَرَم تو {دانِشْگاه} دَرْس می‌خونه.", written: "خواهَرَم دَر {دانِشْگاه} دَرْس می‌خوانَد.", en: "My sister studies at university." },
          { fa: "مادَرَم تو {بیمارِسْتان} کار می‌کُنه.", written: "مادَرَم دَر {بیمارِسْتان} کار می‌کُنَد.", en: "My mother works at a hospital." },
          { fa: "{تَنْهایی} سَخْته.", written: "{تَنْهایی} سَخْت اَسْت.", en: "Being alone is hard." },
        ],
      },
      { type: "heading", text: "Contrast pair" },
      {
        type: "pair",
        title: "The thing, or the person",
        a: { fa: "{پُسْت} دیر اومَد.", written: "{پُسْت} دیر آمَد.", en: "The post came late." },
        b: { fa: "{پُسْتْچی} دیر اومَد.", written: "{پُسْتْچی} دیر آمَد.", en: "The postman came late." },
        diff: "ـچی turns the thing (پُسْت, *the post*) into the person who works with it (پُسْتْچی, *the postman*).",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "ـی after a silent ه",
        text: "Where a silent ه stays before the ending ـی, the ending is written ای after a half-space, as in lesson 6.5. A full space splits the word in two.",
        wrong: { fa: "کیفِ {قَهْوه ای}", en: "(a space before ای)" },
        right: { fa: "کیفِ {قَهْوه‌ای}", en: "a brown bag" },
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "In a taxi",
        lines: [
          { who: "Driver", fa: "شُما {ایرانی} هَسْتین؟", written: "شُما {ایرانی} هَسْتید؟", en: "Are you Iranian?" },
          {
            who: "Passenger",
            fa: "بَله، وَلی تو اِنْگِلیس بُزُرْگ شُدَم. مادَرَم {تِهْرانیه}.",
            written: "بَله، اَمّا دَر اِنْگِلیس بُزُرْگ شُدَم. مادَرَم {تِهْرانی} اَسْت.",
            en: "Yes, but I grew up in England. My mother is from Tehran.",
          },
          { who: "Driver", fa: "{فُرودْگاه} می‌رین یا {دانِشْگاه}؟", written: "به {فُرودْگاه} می‌رَوید یا به {دانِشْگاه}؟", en: "Are you going to the airport or the university?" },
          { who: "Passenger", fa: "{فُرودْگاه}، لُطْفاً.", en: "The airport, please." },
        ],
        note: "تِهْرانیه is تِهْرانی with the spoken *is*. Speech leaves out به before the place you are going to (lesson 9.1). The passenger says بَله, the polite *yes*, to a stranger.",
      },
      {
        type: "quiz",
        questions: [
          { prompt: "Make the describer *from Tehran* from تِهْران (one word).", lang: "fa", answers: ["تهرانی"], explain: "تِهْرانی (*tehrâni*), with the stressed ـی." },
          { prompt: "Type the ending that means *the place of*, as in دانِشْگاه.", lang: "fa", answers: ["گاه", "ـگاه"], explain: "ـگاه (*-gâh*): دانِشْگاه is *the place of knowledge*." },
          { prompt: "Write *hospital*: بیمار (*sick*) with ـسْتان (one word).", lang: "fa", answers: ["بیمارستان"], explain: "بیمارِسْتان (*bimârestân*), *the place of the sick*." },
          { prompt: "Write *brown*: قَهْوه with ـی (one word). Mind the half-space.", lang: "fa", answers: ["قهوه‌ای"], explain: "قَهْوه‌ای (*qahve-i*): after a silent ه, ای after a half-space." },
          {
            prompt: "Translate: پُسْتْچی دیر اومَد.",
            lang: "en",
            answers: ["the postman came late", "the postwoman came late", "the mailman came late", "the mail carrier came late", "the postman was late", "the mailman was late", "the postwoman was late", "the mail carrier was late"],
            explain: "*postchi dir umad*: پُسْت with ـچی.",
          },
        ],
      },
    ],
  },
];
