import type { Lesson } from "../types";

// Unit 6, nouns and links: the ezafe, plurals, "a", and را. Spoken Tehrani
// first, written beneath. Examples are original. The را lesson keeps its
// slug from Phase 1 (saved progress and links use it), now numbered 6.6.

const SOURCE =
  "Mahootian, Persian (Routledge Descriptive Grammars), on the ezafe, plurals and indefiniteness; Thackston, An Introduction to Persian; the Academy's دستورِ خَطِّ فارسی for ـهٔ and the half-space; Stilo, Talattof and Clinton, Modern Persian: Spoken and Written, for the Tehrani forms.";

export const nouns: Lesson[] = [
  {
    slug: "ezafe",
    title: "The ezafe: a noun and its describer",
    summary: "A short -e after the noun hooks a describer onto it, and the describer always comes after the noun: کِتابِ خوب, a good book.",
    register: "both",
    kinds: ["grammar", "word-order"],
    source: SOURCE,
    vocab: [
      { fa: "قِرْمِز", en: "red", topic: "colours" },
      { fa: "آبی", en: "blue", topic: "colours" },
      { fa: "ایرانی", en: "Iranian", topic: "people" },
      { fa: "اَرْزون", written: "اَرْزان", en: "cheap", topic: "describing" },
      { fa: "بُزُرْگ", en: "big", topic: "describing" },
      { fa: "پیرْهَن", written: "پیراهَن", en: "shirt", topic: "things" },
      { fa: "رُوشَن", en: "light, bright", topic: "colours" },
      { fa: "تیره", en: "dark (colour)", topic: "colours" },
    ],
    blocks: [
      {
        type: "idea",
        text: "The **ezafe**, a short *-e* after the noun, hooks a describer onto it: کِتابِ خوب, *a good book*. The describer always comes **after** the noun.",
      },
      {
        type: "text",
        text: "The ezafe (اِضافه, *ezâfe*, literally *addition*) is an unstressed *-e* between a noun and the word that describes it. Normal writing does not show it: the zir in کِتابِ is there only in vowel-marked text, and this course's transliteration writes it with a hyphen: *ketâb-e khub*. With more than one describer, every word but the last takes the ezafe: کِتابِ خوبِ اَرْزون, *a good, cheap book*. Pointing words (این *this*, آن *that*) and numbers (سه *three*) are not describers: they go before the noun, with no ezafe.",
      },
      { type: "heading", text: "Core examples" },
      {
        type: "examples",
        items: [
          { fa: "یه {ماشینِ} قِرْمِز خَریدَم.", written: "یِک {ماشینِ} قِرْمِز خَریدَم.", en: "I bought a red car." },
          { fa: "یه {دوسْتِ} ایرانی دارَم.", written: "یِک {دوسْتِ} ایرانی دارَم.", en: "I have an Iranian friend." },
          { fa: "تو یه {اُتاقِ} کوچیک کار می‌کُنَم.", written: "دَر یِک {اُتاقِ} کوچَک کار می‌کُنَم.", en: "I work in a small room." },
          {
            fa: "یه {کِتابِ خوبِ} اَرْزون می‌خوام.",
            written: "یِک {کِتابِ خوبِ} اَرْزان می‌خواهَم.",
            en: "I'd like a good, cheap book.",
            note: "Two describers: the ezafe goes on the noun and on every describer but the last.",
          },
        ],
      },
      { type: "heading", text: "Contrast pair" },
      {
        type: "pair",
        title: "A good book, or the book is good",
        a: { fa: "{کِتابِ} خوب", en: "a good book (a phrase)" },
        b: { fa: "کِتاب {خوبه}.", written: "کِتاب {خوب اَسْت}.", en: "The book is good." },
        diff: "With the ezafe, خوب is part of the noun phrase. Without it, and with *is*, it makes a statement about the book. One short *-e* makes the difference.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "The describer first, in English order",
        text: "A describer never goes before the noun, as it does in English. The common exceptions are the superlative and the ordinals in ـمین, which come before the noun with no ezafe: بِهْتَرین کِتاب (*the best book*, Unit 9), اَوَّلین بار (*the first time*).",
        wrong: { fa: "{خوب} کِتاب", en: "(meant: a good book; English order)" },
        right: { fa: "کِتابِ {خوب}", en: "a good book" },
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "Buying a shirt",
        lines: [
          { who: "Customer", fa: "یه {پیرْهَنِ} آبی می‌خوام.", written: "یِک {پیراهَنِ} آبی می‌خواهَم.", en: "I'd like a blue shirt." },
          { who: "Seller", fa: "رُوشَن یا تیره؟", en: "Light or dark?" },
          { who: "Customer", fa: "رُوشَن. {سایْزِ} مُتَوَسِّط، لُطْفاً.", en: "Light. Medium size, please." },
          { who: "Seller", fa: "بِفَرْمایین.", written: "بِفَرْمایید.", en: "Here you are." },
        ],
        note: "پیرْهَنِ آبی and سایْزِ مُتَوَسِّط: noun, ezafe, describer. پیرْهَن is the everyday spoken form of پیراهَن.",
      },
      {
        type: "quiz",
        questions: [
          {
            prompt: "Write *a red car* without یه: car is ماشین, red is قِرْمِز (two words).",
            lang: "fa",
            answers: ["ماشین قرمز"],
            explain: "ماشینِ قِرْمِز (*mâshin-e qermez*): the noun first, then the describer. The ezafe is not written.",
          },
          {
            prompt: "In *the book is good* (کِتاب خوبه), does کِتاب take the ezafe? Type yes or no.",
            lang: "en",
            answers: ["no"],
            explain: "No: *is* makes it a statement. کِتابِ خوب, with the ezafe, is the phrase *a good book*.",
          },
          {
            prompt: "Transliterate کِتابِ خوب.",
            lang: "translit",
            answers: ["ketâb-e khub"],
            explain: "*ketâb-e khub*: the ezafe is an unstressed *-e*.",
          },
          {
            prompt: "Translate: یه دوسْتِ ایرانی دارَم.",
            lang: "en",
            answers: ["i have an iranian friend", "i've got an iranian friend"],
            explain: "*ye dust-e irâni dâram*: دوسْتِ ایرانی, noun + ezafe + describer.",
          },
        ],
      },
    ],
  },
  {
    slug: "ezafe-of",
    title: "The ezafe for “of” and possession",
    summary: "The same ezafe links a noun to its owner or to what it belongs to: کِتابِ مَرْیَم, Maryam's book.",
    register: "both",
    kinds: ["grammar", "word-order"],
    source: SOURCE,
    vocab: [
      { fa: "بابا", written: "پِدَر", en: "dad; father", topic: "people" },
      { fa: "خیابون", written: "خیابان", en: "street", topic: "places" },
      { fa: "کِلید", en: "key", topic: "things" },
      { fa: "جَدید", en: "new", topic: "describing" },
      { fa: "خَراب", en: "broken, out of order", topic: "describing" },
      { fa: "دَسْت", en: "hand", topic: "body" },
    ],
    blocks: [
      {
        type: "idea",
        text: "The same ezafe links a noun to its **owner**, or to what it belongs to: کِتابِ مَرْیَم, *Maryam's book*; دَرِ خونه, *the door of the house*.",
      },
      {
        type: "text",
        text: "Persian has no *'s*, and for most English *of* it uses the ezafe: the owner simply follows the noun, linked by it. A pronoun works the same way: کِتابِ مَن is *my book*, with weight on *my* (the everyday form is the ending, کِتابَم, from lesson 4.5). Chains run in the opposite order to English *'s*: دوسْتِ بَرادَرِ مَرْیَم is *Maryam's brother's friend*, literally *friend of brother of Maryam*. When a noun has both a describer and an owner, the describer comes first: کِتابِ جَدیدِ سارا, *Sara's new book*.",
      },
      { type: "heading", text: "Core examples" },
      {
        type: "examples",
        items: [
          { fa: "{ماشینِ} بابام خَرابه.", written: "{ماشینِ} پِدَرَم خَراب اَسْت.", en: "My dad's car has broken down." },
          { fa: "{اِسْمِ} این خیابون چیه؟", written: "{نامِ} این خیابان چیسْت؟", en: "What's the name of this street?" },
          { fa: "{دَرِ} خونه بازه.", written: "{دَرِ} خانه باز اَسْت.", en: "The front door is open.", note: "Literally *the door of the house*." },
          {
            fa: "{کِتابِ جَدیدِ} سارا رُو خونْدی؟",
            written: "{کِتابِ جَدیدِ} سارا را خوانْدی؟",
            en: "Have you read Sara's new book?",
            note: "The describer (*new*) comes before the owner (*Sara*).",
          },
        ],
      },
      { type: "heading", text: "Contrast pair" },
      {
        type: "pair",
        title: "Owner or describer",
        a: { fa: "کیفِ {مَرْیَم}", en: "Maryam's bag" },
        b: { fa: "کیفِ {قَشَنْگ}", en: "a beautiful bag" },
        diff: "The same link does both jobs: the word after the ezafe can own the noun or describe it.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "The owner first, in English order",
        text: "English puts the owner first (*Maryam's book*). In Persian the owner comes after the noun, and there is no *'s* to add.",
        wrong: { fa: "مَرْیَم کِتاب", en: "(meant: Maryam's book)" },
        right: { fa: "{کِتابِ} مَرْیَم", en: "Maryam's book" },
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "Whose bag?",
        lines: [
          { who: "Reza", fa: "این {کیفِ} کیه؟", written: "این {کیفِ} کیسْت؟", en: "Whose bag is this?" },
          { who: "Sima", fa: "{کیفِ} مَرْیَمه.", written: "{کیفِ} مَرْیَم اَسْت.", en: "It's Maryam's bag." },
          { who: "Reza", fa: "{کِلیدِ} خونه کُجاسْت؟", written: "{کِلیدِ} خانه کُجاسْت؟", en: "Where's the house key?" },
          { who: "Sima", fa: "{دَسْتِ} مَرْیَمه.", written: "{دَسْتِ} مَرْیَم اَسْت.", en: "Maryam has it." },
        ],
        note: "کیفِ کیه؟ is literally *the bag of who is it?*. دَسْتِ مَرْیَمه, literally *(it is in) Maryam's hand*, is the everyday way to say *Maryam has it*. *It's Maryam's* can also be مالِ مَرْیَمه.",
      },
      {
        type: "quiz",
        questions: [
          { prompt: "Write *Maryam's book* (two words).", lang: "fa", answers: ["کتاب مریم"], explain: "کِتابِ مَرْیَم: the book first, then the owner." },
          {
            prompt: "Written: *the door of the house* (two words).",
            lang: "fa",
            answers: ["در خانه"],
            explain: "دَرِ خانه (*dar-e khâne*); spoken دَرِ خونه.",
          },
          {
            prompt: "A noun with a describer and an owner: which comes first after the noun? Type describer or owner.",
            lang: "en",
            answers: ["describer", "the describer"],
            explain: "The describer: کِتابِ جَدیدِ سارا, *Sara's new book*.",
          },
          {
            prompt: "Translate: اِسْمِ این خیابون چیه؟",
            lang: "en",
            answers: [
              "what's the name of this street",
              "what is the name of this street",
              "what is this street called",
              "what's this street called",
            ],
            explain: "*esm-e in khiyâbun chiye?*: literally *name of this street is what?*",
          },
        ],
      },
    ],
  },
  {
    slug: "ezafe-after-vowels",
    title: "The ezafe after a vowel: ـیِ and ـهٔ",
    summary: "After ا and و the ezafe is written ی; after a silent ه it is [ـهٔ|-ye]. Both are said -ye.",
    register: "both",
    kinds: ["grammar", "spelling"],
    source: SOURCE,
    vocab: [
      { fa: "هَوا", en: "weather; air", topic: "weather" },
      { fa: "دانِشْجو", en: "student (university)", topic: "learning" },
      { fa: "صَنْدَلی", en: "chair", topic: "home" },
      { fa: "راحَت", en: "comfortable; easy", topic: "describing" },
      { fa: "دانِشْگاه", en: "university", topic: "learning" },
      { fa: "نَزْدیک", en: "near", topic: "places" },
      { fa: "کوچه", en: "lane, side street", topic: "places" },
      { fa: "دِرَخْت", en: "tree", topic: "nature" },
    ],
    blocks: [
      {
        type: "idea",
        text: "After a vowel the ezafe is *-ye*. After ا and و it is written with a **ی** (هَوایِ خوب); after a silent ه it is written **[ـهٔ|-ye]** (خانهٔ مَن).",
      },
      {
        type: "text",
        text: "Two vowels can't meet, so after a vowel the ezafe gets a *y*: *havâ-ye*, *khâne-ye*. How that is written depends on the letter the word ends in. After ا and a vowel و (*u*) a ی is added, and it stays in unmarked text: هَوایِ تِهْران. After a silent ه (said *e*) the Academy writes a small hamze on the ه: خانهٔ. Many writers type [ـه‌ی|-ye] instead, as in [خانه‌ی|khâne-ye], or leave it out altogether; the course writes [ـهٔ|-ye], and the trainer accepts [ـه‌ی|-ye]. After the vowel ی (*i*) nothing is added, only said: صَنْدَلیِ راحَت, *sandali-ye râhat*. A ه that is a real *h* (دانِشْگاه, ماه, کوه) is a consonant, so it takes the plain *-e*.",
      },
      {
        type: "table",
        caption: "The ezafe by the noun's last letter",
        headers: ["The noun ends in", "Example", "Said"],
        rows: [
          ["a consonant", "کِتابِ خوب", "*ketâb-e khub*"],
          ["ا", "هَوایِ خوب", "*havâ-ye khub*"],
          ["و (*u*)", "دانِشْجویِ خوب", "*dâneshju-ye khub*"],
          ["a silent ه (*e*)", "خانهٔ خوب", "*khâne-ye khub*"],
          ["ی (*i*)", "صَنْدَلیِ خوب", "*sandali-ye khub*"],
        ],
      },
      { type: "heading", text: "Core examples" },
      {
        type: "examples",
        items: [
          { fa: "{خونهٔ} ما نَزْدیکه.", written: "{خانهٔ} ما نَزْدیک اَسْت.", en: "Our house is close by." },
          { fa: "{هَوایِ} تِهْرون سَرْده.", written: "{هَوایِ} تِهْران سَرْد اَسْت.", en: "The weather in Tehran is cold." },
          { fa: "{دانِشْجویِ} پِزِشْکیه.", written: "{دانِشْجویِ} پِزِشْکی اَسْت.", en: "She's a medical student. / He's a medical student." },
          { fa: "یه {صَنْدَلیِ} راحَت می‌خوام.", written: "یِک {صَنْدَلیِ} راحَت می‌خواهَم.", en: "I want a comfortable chair." },
        ],
      },
      { type: "heading", text: "Contrast pair" },
      {
        type: "pair",
        title: "After a consonant, after a vowel",
        a: { fa: "{کِتابِ} مَن", en: "my book (*ketâb-e man*)" },
        b: { fa: "{خانهٔ} مَن", en: "my house (*khâne-ye man*)" },
        diff: "After the consonant ب the ezafe is a plain *-e* and is not written. After the vowel of خانه it is *-ye*, written [ـهٔ|-ye].",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "No ی after ا or و",
        text: "Leaving out the ی after ا or و runs the two words together. The ی is part of the spelling: write it, and say *-ye*.",
        wrong: { fa: "[هوا خوب|havâ-e khub]", en: "(meant: good weather)" },
        right: { fa: "{هَوایِ} خوب", en: "good weather" },
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "Where do you live?",
        lines: [
          { who: "Arman", fa: "{خونهٔ} شُما کُجاسْت؟", written: "{خانهٔ} شُما کُجاسْت؟", en: "Where's your house?" },
          { who: "Shirin", fa: "نَزْدیکِ {دانِشْگاهِ} تِهْرون.", written: "نَزْدیکِ {دانِشْگاهِ} تِهْران.", en: "Near Tehran University." },
          { who: "Arman", fa: "{هَوایِ} اونْجا چِطُوره؟", written: "{هَوایِ} آنْجا چِطُور اَسْت؟", en: "What's the air like there?" },
          { who: "Shirin", fa: "خوبه. {کوچهٔ} ما پُرِ دِرَخْته.", written: "خوب اَسْت. {کوچهٔ} ما پُر اَز دِرَخْت اَسْت.", en: "Good. Our lane is full of trees." },
        ],
        note: "دانِشْگاهِ takes a plain *-e*: its ه is the consonant *h*, after ا. خونهٔ and کوچهٔ end in a silent ه, so their ezafe is *-ye*.",
      },
      {
        type: "quiz",
        questions: [
          { prompt: "Transliterate خانهٔ مَن.", lang: "translit", answers: ["khâne-ye man"], explain: "*khâne-ye man*: after a silent ه the ezafe is *-ye*, written [ـهٔ|-ye]." },
          { prompt: "Write *good weather* (written; two words).", lang: "fa", answers: ["هوای خوب"], explain: "هَوایِ خوب: after ا the ezafe is written with ی." },
          {
            prompt: "Write *a student's book*, with دانِشْجو: book first (two words).",
            lang: "fa",
            answers: ["کتاب دانشجو"],
            explain: "کِتابِ دانِشْجو: the ezafe goes on کِتاب, which ends in a consonant, so nothing is added.",
          },
          {
            prompt: "Transliterate دانِشْگاهِ تِهْران (its ه is a consonant).",
            lang: "translit",
            answers: ["dâneshgâh-e tehrân"],
            explain: "*dâneshgâh-e tehrân*: a consonant ه takes the plain *-e*.",
          },
        ],
      },
    ],
  },
  {
    slug: "plurals",
    title: "Plurals: ـها (spoken ـا) and ـان",
    summary: "The everyday plural is ـها, said -â after a consonant in speech; writing also uses ـان for people. After a number, the noun stays singular.",
    register: "both",
    kinds: ["grammar", "suffixes"],
    source: SOURCE,
    vocab: [
      { fa: "روز", en: "day", topic: "time" },
      { fa: "اُسْتاد", en: "lecturer, professor; master", topic: "people" },
      { fa: "اِمْتِحان", en: "exam", topic: "learning" },
      { fa: "بِسیار", en: "very (written)", topic: "describing" },
      { fa: "شام", en: "dinner", topic: "food" },
    ],
    blocks: [
      {
        type: "idea",
        text: "The everyday plural is **ـها** (*-hâ*), said **ـا** (*-â*) after a consonant in speech. Writing also uses **ـان** (*-ân*), mainly for people.",
      },
      {
        type: "text",
        text: "ـها works with any noun. After a joining letter it is written with a half-space (کِتاب‌ها); after a non-joining letter it simply follows (روزْها), as lesson 3.2 showed. In speech the *h* drops after a consonant: کِتابا (*ketâbâ*), روزا; after a vowel it usually stays: بَچّه‌ها (*bachche-hâ*). The written plural ـان is mainly for people, and also for some animals, plants, body parts and a few other words: دوسْتان, اُسْتادان, دِرَخْتان, چِشْمان. After ا it becomes ـیان (آقایان, *gentlemen*); after و usually ـیان too (دانِشْجویان), though a few words take ـان ([بانوان|bânovân], *ladies*); after a silent ه it is ـگان: نِویسَنْده → نِویسَنْدِگان (*writers*). Persian does not use the plural after a number: سه کِتاب, *three books*.",
      },
      {
        type: "table",
        caption: "Plurals, spoken and written",
        headers: ["Noun", "Spoken", "Written"],
        rows: [
          ["کِتاب, book", "کِتابا", "کِتاب‌ها"],
          ["روز, day", "روزا", "روزْها"],
          ["دوسْت, friend", "دوسْتا", "دوسْت‌ها, دوسْتان"],
          ["بَچّه, child", "بَچّه‌ها", "بَچّه‌ها"],
          ["دانِشْجو, student", "دانِشْجوها", "دانِشْجوها, دانِشْجویان"],
        ],
      },
      { type: "heading", text: "Core examples" },
      {
        type: "examples",
        items: [
          { fa: "{بَچّه‌ها} کُجان؟", written: "{بَچّه‌ها} کُجا هَسْتَنْد؟", en: "Where are the kids?" },
          { fa: "{دوسْتام} اِمْشَب میان.", written: "{دوسْتانَم} اِمْشَب می‌آیَنْد.", en: "My friends are coming tonight.", note: "The plural, then *my*: دوسْتا + ـم." },
          { fa: "این {روزا} خَیلی کار دارَم.", written: "این {روزْها} خَیلی کار دارَم.", en: "I'm very busy these days." },
          {
            fa: "{دانِشْجوها} اِمْروز اِمْتِحان دارَن.",
            written: "{دانِشْجویان} اِمْروز اِمْتِحان دارَنْد.",
            en: "The students have an exam today.",
          },
        ],
      },
      { type: "heading", text: "Contrast pair" },
      {
        type: "pair",
        title: "Three books, the books",
        a: { fa: "سه تا {کِتاب} خَریدَم.", written: "سه {کِتاب} خَریدَم.", en: "I bought three books." },
        b: { fa: "{کِتابا} رُو خَریدَم.", written: "{کِتاب‌ها} را خَریدَم.", en: "I bought the books." },
        diff: "After a number the noun stays singular: سه کِتاب. Without a number, the plural ending shows *more than one*. Speech adds the counting word تا after the number (Unit 9).",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "The plural after a number",
        text: "English says *three books*; Persian keeps the noun singular after any number or چَنْد (*how many, a few*), because the number already says how many.",
        wrong: { fa: "سه {کِتاب‌ها}", en: "(meant: three books)" },
        right: { fa: "سه {کِتاب}", en: "three books" },
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "A new class",
        lines: [
          {
            who: "Parisa",
            fa: "کِلاسِتون چَنْد تا {دانِشْجو} داره؟",
            written: "کِلاسِ شُما چَنْد {دانِشْجو} دارَد؟",
            en: "How many students are in your class?",
          },
          {
            who: "Hamed",
            fa: "بیسْت تا. بیشْتَرِ {دانِشْجوها} ایرانی‌اَن.",
            written: "بیسْت نَفَر. بیشْتَرِ {دانِشْجویان} ایرانی هَسْتَنْد.",
            en: "Twenty. Most of the students are Iranian.",
          },
          { who: "Parisa", fa: "{اُسْتادا} چی؟", written: "{اُسْتادان} چِطُور؟", en: "What about the lecturers?" },
          { who: "Hamed", fa: "{اُسْتادا} هَم خَیلی خوبَن.", written: "{اُسْتادان} هَم بِسیار خوب هَسْتَنْد.", en: "The lecturers are really good too." },
        ],
        note: "After چَنْد تا the noun stays singular. بیشْتَرِ (*most of*) comes before the noun and takes the ezafe itself. The written lines use ـان for people: دانِشْجویان, اُسْتادان. Written Persian counts people with نَفَر (*person*); speech also uses نَفَر, or simply تا.",
      },
      {
        type: "quiz",
        questions: [
          { prompt: "Written plural of کِتاب (mind the half-space).", lang: "fa", answers: ["کتاب‌ها", "کتابها"], explain: "کِتاب‌ها: a half-space after the joining ب. The Academy also allows کِتابْها, joined." },
          { prompt: "Spoken plural of کِتاب.", lang: "fa", answers: ["کتابا"], explain: "کِتابا (*ketâbâ*): speech drops the *h* after a consonant." },
          { prompt: "Written: *three books* (two words).", lang: "fa", answers: ["سه کتاب"], explain: "سه کِتاب: no plural after a number." },
          {
            prompt: "Written plural of روز (day). Type it; think about the half-space.",
            lang: "fa",
            answers: ["روزها"],
            explain: "روزْها: ز never joins forward, so no half-space is needed.",
          },
        ],
      },
    ],
  },
  {
    slug: "indefinite",
    title: "“A, one”: یه and the ending ـی",
    summary: "Speech says یه before the noun (written یِک); writing often adds the ending ـی instead: یه کِتاب, کِتابی.",
    register: "both",
    kinds: ["grammar", "suffixes"],
    source: SOURCE,
    vocab: [
      { fa: "سُؤال", en: "question", topic: "learning" },
      { fa: "تاکْسی", en: "taxi", topic: "places" },
      { fa: "رِسْتوران", en: "restaurant", topic: "places" },
      { fa: "داروخونه", written: "داروخانه", en: "pharmacy", topic: "places" },
      { fa: "مَغازه", en: "shop", topic: "places" },
      { fa: "جا", en: "place; room, space", topic: "places" },
    ],
    blocks: [
      {
        type: "idea",
        text: "*A* is **یه** (*ye*) before the noun in speech, written **یِک** (*yek*); writing often uses the ending **ـی** (*-i*) instead: یه کِتاب, کِتابی.",
      },
      {
        type: "text",
        text: "Persian has no word that only means *a*: یه / یِک is the number *one* used for *a*. The unstressed ending ـی also marks *a* or *some*: کِتابی, *a book*. It is common in writing, especially in formal and literary style, and speech uses it too, often together with یه: یه جایی, *somewhere*. With a describer, ـی goes on the describer at the end of the phrase: یه رِسْتورانِ خوبی, *a good restaurant*. After a vowel it changes its spelling: after ا or و it is یی (جایی, دانِشْجویی); after a silent ه or ی it is written ای after a half-space (خانه‌ای, *khâne-i*; صَنْدَلی‌ای, *sandali-i*). A noun with neither یه nor ـی is either definite (*the book*) or a kind of thing (*books, book-buying*), which lesson 6.6 picks up.",
      },
      { type: "heading", text: "Core examples" },
      {
        type: "examples",
        items: [
          { fa: "{یه} سُؤال دارَم.", written: "{یِک} سُؤال دارَم.", en: "I have a question." },
          { fa: "{یه} تاکْسی گِرِفْتیم.", written: "{یِک} تاکْسی گِرِفْتیم.", en: "We took a taxi." },
          { fa: "{جایی} می‌ری؟", written: "{جایی} می‌رَوی؟", en: "Are you going somewhere?", note: "جا (*place*) + ـی: *some place*." },
          {
            fa: "{یه} رِسْتورانِ {خوبی} می‌شِناسَم.",
            written: "رِسْتورانِ {خوبی} می‌شِناسَم.",
            en: "I know a good restaurant.",
            note: "With a describer, ـی goes on the describer: خوبی.",
          },
        ],
      },
      { type: "heading", text: "Contrast pair" },
      {
        type: "pair",
        title: "Two ways to say “a”",
        a: { fa: "{یه} کِتاب خَریدَم.", written: "{یِک} کِتاب خَریدَم.", en: "I bought a book." },
        b: { fa: "{کِتابی} خَریدَم.", en: "I bought a book. (written style)" },
        diff: "Both mean *a book*. یه before the noun is the everyday way; the ending ـی on the noun is common in writing, especially in formal style.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "یه with a plural",
        text: "یه means *a, one*, so the noun after it stays singular. For *a few books*, use چَنْد تا (written چَنْد) with a singular noun. Speech does say یه with a plural that ends in ـی, for a vague *some*: یه چیزایی شِنیدَم, *I heard a few things*; یه never goes with a bare plural.",
        wrong: { fa: "{یه} کِتابا خَریدَم.", en: "(meant: I bought some books)" },
        right: { fa: "{چَنْد تا} کِتاب خَریدَم.", written: "{چَنْد} کِتاب خَریدَم.", en: "I bought a few books." },
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "Asking the way",
        lines: [
          {
            who: "Visitor",
            fa: "بِبَخْشید، این نَزْدیکی {یه} داروخونه هَسْت؟",
            written: "بِبَخْشید، این نَزْدیکی {یِک} داروخانه هَسْت؟",
            en: "Excuse me, is there a pharmacy near here?",
          },
          {
            who: "Passer-by",
            fa: "آره، {یه} داروخونه سَرِ خیابونه.",
            written: "بَله، سَرِ خیابان {یِک} داروخانه هَسْت.",
            en: "Yes, there's a pharmacy at the end of the street.",
          },
          { who: "Visitor", fa: "{یه} سوپِرْمارْکِت هَم هَسْت؟", written: "{یِک} سوپِرْمارْکِت هَم هَسْت؟", en: "Is there a supermarket too?" },
          {
            who: "Passer-by",
            fa: "نَه، وَلی کِنارِ داروخونه {یه} مَغازه هَسْت.",
            written: "نَه، وَلی کِنارِ داروخانه {مَغازه‌ای} هَسْت.",
            en: "No, but there's a shop next to the pharmacy.",
          },
        ],
        note: "هَسْت is *there is*. The last written line uses مَغازه‌ای: after a silent ه the ending ـی is written ای after a half-space.",
      },
      {
        type: "quiz",
        questions: [
          { prompt: "Type the spoken word for *a* that goes before a noun.", lang: "fa", answers: ["یه"], explain: "یه (*ye*); written یِک (*yek*)." },
          { prompt: "Written style: *a book* with the ending ـی (one word).", lang: "fa", answers: ["کتابی"], explain: "کِتابی (*ketâbi*): the ending ـی is unstressed." },
          {
            prompt: "Add the ending ـی to خانه (house). Mind the half-space.",
            lang: "fa",
            answers: ["خانه‌ای"],
            explain: "خانه‌ای (*khâne-i*): after a silent ه it is written ای after a half-space.",
          },
          { prompt: "Translate: یه سُؤال دارَم.", lang: "en", answers: ["i have a question", "i've got a question"], explain: "*ye so'âl dâram*." },
        ],
      },
    ],
  },
  {
    slug: "ra-specific-object",
    title: "را marks a specific direct object",
    summary: "Put را after a direct object that is a particular one (the book, this song, Maryam), not just any book.",
    register: "both",
    kinds: ["grammar", "prepositions"],
    source:
      "Mahootian, Persian (Routledge Descriptive Grammars), on را and specificity; Lazard, A Grammar of Contemporary Persian, on را and definiteness; Stilo, Talattof and Clinton, Modern Persian: Spoken and Written, on spoken رُو / -o.",
    vocab: [
      { fa: "کِتاب", en: "book", topic: "learning" },
      { fa: "خَریدَن", en: "to buy", topic: "verbs" },
      { fa: "دیدَن", en: "to see", topic: "verbs" },
      { fa: "دَر", en: "door", topic: "home" },
      { fa: "بَسْتَن", en: "to close", topic: "verbs" },
      { fa: "آهَنْگ", en: "song", topic: "everyday" },
      { fa: "نامه", en: "letter (mail)", topic: "everyday" },
      { fa: "مُعَلِّم", en: "teacher", topic: "people" },
      { fa: "نون", written: "نان", en: "bread", topic: "food" },
      { fa: "چایی", written: "چای", en: "tea", topic: "food" },
      { fa: "آشْپَزْخونه", written: "آشْپَزْخانه", en: "kitchen", topic: "home" },
    ],
    blocks: [
      {
        type: "idea",
        text: "{را} tags a **specific** direct object: the particular thing the verb acts on.",
      },
      {
        type: "text",
        text: "In the core Persian sentence the verb comes last, and the words before it need to show what role they play. The **direct object** (مَفْعولِ صَریح, the thing the action is done to) gets its tag, را, when it is **specific**: a particular one the speaker has in mind, usually one the listener can identify too, because it is named, pointed at, owned, or already mentioned. A non-specific object (any bread, some book) gets no tag. In speech را is رُو, and after a consonant it is usually said *-o*: Iranians often type کِتاب رُو but say *ketâbo* (more in “را in speech”, later in this unit).",
      },
      { type: "heading", text: "Core examples" },
      {
        type: "examples",
        items: [
          {
            fa: "کِتاب {رُو} خَریدَم.",
            written: "کِتاب {را} خَریدَم.",
            en: "I bought the book.",
            note: "The book you and I both know about.",
          },
          {
            fa: "مَرْیَم {رُو} دیدی؟",
            written: "مَرْیَم {را} دیدی؟",
            en: "Did you see Maryam?",
            note: "A name always points to one person, so it takes را.",
          },
          {
            fa: "دَر {رُو} بِبَنْد.",
            written: "دَر {را} بِبَنْد.",
            en: "Close the door.",
          },
          {
            fa: "این آهَنْگ {رُو} دوسْت دارَم.",
            written: "این آهَنْگ {را} دوسْت دارَم.",
            en: "I like this song.",
            note: "این (this) makes the object specific.",
          },
          {
            fa: "روزْنامهٔ اِمْروز {رُو} خونْدی؟",
            written: "روزْنامهٔ اِمْروز {را} خوانْدی؟",
            en: "Did you read today's paper?",
            note: "را comes after the whole object phrase, ezafe and all.",
          },
        ],
      },
      { type: "heading", text: "Contrast pairs" },
      {
        type: "pair",
        title: "A book or the book",
        a: { fa: "{یه} کِتاب خَریدَم.", written: "{یِک} کِتاب خَریدَم.", en: "I bought a book." },
        b: { fa: "کِتاب {رُو} خَریدَم.", written: "کِتاب {را} خَریدَم.", en: "I bought the book." },
        diff: "With یه (a, one) the book is new to the listener: no را. With را it is a particular book the listener knows.",
      },
      {
        type: "pair",
        title: "Letter-writing or the letter",
        a: { fa: "نامه نِوِشْتَم.", en: "I wrote a letter or letters. (I did some letter-writing.)" },
        b: { fa: "نامه {رُو} نِوِشْتَم.", written: "نامه {را} نِوِشْتَم.", en: "I wrote the letter." },
        diff: "A bare noun with no را and no یه names a kind of thing, not a particular one, and leaves the number open. Adding را picks out one letter.",
      },
      {
        type: "pair",
        title: "Any tea or the tea",
        a: {
          fa: "چایی می‌خُوری؟",
          written: "چای می‌خُوری؟",
          en: "Will you have some tea?",
          note: "The same words can also ask about a habit: *Do you drink tea?*",
        },
        b: { fa: "چایی {رُو} خُورْدی؟", written: "چای {را} خُورْدی؟", en: "Did you drink the tea?" },
        diff: "The offer is about any tea, not a particular glass, so there is no را. The question is about the tea that was poured for you.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "را is not the word for “the”",
        text: "English marks most definite common nouns with *the*, so it is tempting to read را as *the*. It is not. Written Persian has no word for *the* (spoken Tehrani has a definite ending, ـه as in کِتابه, which comes later), and را goes only on a specific **direct object**, never on the subject, however definite the subject is. The opposite slip matters too: leaving out را after a specific object (این آهَنْگ دوسْت دارَم) sounds wrong to a native ear.",
        wrong: { fa: "مُعَلِّم رُو اومَد.", written: "مُعَلِّم را آمَد.", en: "The teacher came." },
        right: { fa: "مُعَلِّم اومَد.", written: "مُعَلِّم آمَد.", en: "The teacher came." },
      },
      {
        type: "callout",
        kind: "tip",
        title: "Specific but still “a”",
        text: "An object can be indefinite and still specific: *a certain book*, one the speaker has in mind but the listener does not know. Persian can mark that with را too, usually with یه and often a که clause: یه کِتابی رُو که دیروز دیدَم خَریدَم (I bought a book I had seen yesterday). Unit 10 covers the pattern.",
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "Back from the shop",
        lines: [
          { who: "Sara", fa: "نون خَریدی؟", written: "نان خَریدی؟", en: "Did you buy bread?" },
          { who: "Ali", fa: "آره، خَریدَم.", written: "بَله، خَریدَم.", en: "Yes, I did." },
          { who: "Sara", fa: "نون {رُو} کُجا گُذاشْتی؟", written: "نان {را} کُجا گُذاشْتی؟", en: "Where did you put the bread?" },
          { who: "Ali", fa: "تو آشْپَزْخونه.", written: "دَر آشْپَزْخانه.", en: "In the kitchen." },
        ],
        note: "In the first question the bread is non-specific (any bread), so there is no را. Once both speakers mean the bread just bought, it takes را. In the last written line دَر means *in*, the written counterpart of spoken تو; the same letters also spell *door*.",
      },
      {
        type: "quiz",
        questions: [
          {
            prompt: "Type the written object marker that follows a specific direct object.",
            lang: "fa",
            answers: ["را"],
            explain: "را in writing; رُو (*ro*) in speech, usually said *-o* after a consonant.",
          },
          {
            prompt: "Does «یه کِتاب خَریدَم» (I bought a book) need را? Type yes or no.",
            lang: "en",
            answers: ["no"],
            explain: "The book is new to the listener, marked by یه, so there is no را.",
          },
          {
            prompt: "Write in Persian (written form): I saw Maryam.",
            lang: "fa",
            answers: ["مریم را دیدم", "من مریم را دیدم"],
            explain: "A name is specific, so it takes را: مَرْیَم را دیدَم.",
          },
          {
            prompt: "Type the transliteration of the spoken marker رُو.",
            lang: "translit",
            answers: ["ro"],
            explain: "رُو is *ro*; the و spells the vowel o here.",
          },
        ],
      },
    ],
  },
  {
    slug: "ra-spoken",
    title: "را in speech: رُو and ـو",
    summary: "Spoken را is رُو (ro), and after a consonant it shrinks to -o: کِتابُو, ketâbo. After a vowel it keeps its r.",
    register: "spoken",
    kinds: ["grammar", "spoken"],
    source: SOURCE,
    vocab: [
      { fa: "مَرا", en: "me (as the object; written)", topic: "people" },
      { fa: "جُمْعه", en: "Friday", topic: "time" },
      { fa: "تَمیز کَرْدَن", en: "to clean", topic: "verbs" },
      { fa: "کُدوم", written: "کُدام", en: "which", topic: "everyday" },
    ],
    blocks: [
      {
        type: "idea",
        text: "In speech را is **رُو** (*ro*), and after a consonant it usually shrinks to **[ـو|-o]**, joined to the word: کِتابُو (*ketâbo*), *the book*.",
      },
      {
        type: "text",
        text: "Written را is a separate word; the one exception is مَرا (*me*). In Tehrani speech it becomes *ro*, and after a consonant the *r* drops, so the *-o* runs into the word before: کِتاب رُو is said *ketâbo*. After a vowel the *r* stays: خونه رُو (*khune ro*), ما رُو. In chat, Iranians type it either way: کِتاب رُو, or as it is said, کِتابُو. A few everyday objects are nearly always said and typed as one word: مَنُو (*mano*, me; written مَرا), اینُو (*ino*, this one), اونُو (*uno*, that one; him, her).",
      },
      {
        type: "table",
        caption: "را, written and spoken",
        headers: ["Written", "Spoken (typed)", "Said"],
        rows: [
          ["کِتاب را", "کِتاب رُو, کِتابُو", "*ketâbo*"],
          ["خانه را", "خونه رُو", "*khune ro*"],
          ["مَرا", "مَنُو", "*mano*"],
          ["این را", "اینُو", "*ino*"],
          ["آن را, او را", "اونُو", "*uno*"],
          ["ما را", "ما رُو", "*mâ ro*"],
        ],
      },
      { type: "heading", text: "Core examples" },
      {
        type: "examples",
        items: [
          { fa: "{اینُو} می‌خوام.", written: "{این را} می‌خواهَم.", en: "I want this one." },
          { fa: "{مَنُو} می‌شِناسی؟", written: "{مَرا} می‌شِناسی؟", en: "Do you know me?" },
          { fa: "{اونُو} نِمی‌شِناسَم.", written: "{او را} نِمی‌شِناسَم.", en: "I don't know him. / I don't know her." },
          {
            fa: "جُمْعه‌ها {خونه رُو} تَمیز می‌کُنیم.",
            written: "جُمْعه‌ها {خانه را} تَمیز می‌کُنیم.",
            en: "We clean the house on Fridays.",
            note: "After the vowel of خونه, رُو keeps its *r*.",
          },
        ],
      },
      { type: "heading", text: "Contrast pair" },
      {
        type: "pair",
        title: "Typed apart, typed as said",
        a: { fa: "{کِتاب رُو} خونْدَم.", en: "I read the book. (typed with رُو)" },
        b: { fa: "{کِتابُو} خونْدَم.", en: "I read the book. (typed as said)" },
        diff: "Both are usually said *ketâbo khundam*, and chat uses either spelling. Formal writing has only one: کِتاب را خوانْدَم.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "ـو in writing",
        text: "رُو and [ـو|-o] belong to speech and chat. In anything formal, write را as a separate word.",
        wrong: { fa: "{کِتابُو} خوانْدَم.", en: "I read the book. (in an essay)" },
        right: { fa: "{کِتاب را} خوانْدَم.", en: "I read the book." },
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "The keys",
        lines: [
          { who: "Mother", fa: "{کِلیدا رُو} نَدیدی؟", written: "{کِلیدْها را} نَدیدی؟", en: "Have you seen the keys?" },
          { who: "Son", fa: "کُدوم کِلیدا؟", written: "کُدام کِلیدْها؟", en: "Which keys?" },
          { who: "Mother", fa: "{کِلیدِ ماشینُو}!", written: "{کِلیدِ ماشین را}!", en: "The car key!" },
          { who: "Son", fa: "آهان، {اونُو} گُذاشْتَم رو میز.", written: "آهان، {آن را} رویِ میز گُذاشْتَم.", en: "Oh, I put it on the table." },
        ],
        note: "کِلیدا رُو keeps its *r* after the vowel *â*. After a consonant it shrinks: ماشینُو (*mâshino*), اونُو (*uno*). نَدیدی (*didn't you see?*) is the negative past, Unit 7. In رو میز, رو is *ru*, short for رویِ (*on*), not را.",
      },
      {
        type: "quiz",
        questions: [
          {
            prompt: "Spoken, typed as said: *this one* as the object (one word).",
            lang: "fa",
            answers: ["اینو"],
            explain: "اینُو (*ino*); written این را.",
          },
          {
            prompt: "Type the written form of spoken مَنُو (me, as the object; one word).",
            lang: "fa",
            answers: ["مرا", "من را"],
            explain: "مَرا (*marâ*), the written form of مَن را.",
          },
          {
            prompt: "After a vowel, is spoken را said *ro* or *-o*? Type ro or o.",
            lang: "translit",
            answers: ["ro"],
            explain: "*ro*: خونه رُو (*khune ro*). Only after a consonant does it shrink to *-o*.",
          },
          {
            prompt: "Transliterate how کِتاب رُو is usually said.",
            lang: "translit",
            answers: ["ketâbo"],
            explain: "*ketâbo*: after a consonant the *r* drops.",
          },
        ],
      },
    ],
  },
];
