import type { Lesson } from "../types";

// Unit 2: the vowels and the marks that show them, the letters that double as
// vowels, and stress. Transliteration always shows (the marks are what is
// being taught). Examples are original.

const SOURCE =
  "Thackston, An Introduction to Persian (sounds and the vowel marks); Mahootian, Persian (Routledge Descriptive Grammars), on the vowel system and stress; vowel marks after Dehkhoda and Sokhan.";

export const sounds: Lesson[] = [
  {
    slug: "short-vowels",
    title: "Three short vowels: zabar, zir, pish",
    summary: "The short vowels a, e and o are small marks above or below a letter, and everyday Persian leaves them out.",
    register: "written",
    kinds: ["pronunciation"],
    showTranslit: true,
    showMarks: true,
    source: SOURCE,
    vocab: [
      { fa: "دَر", en: "door", topic: "home" },
      { fa: "دِل", en: "heart (feelings)", topic: "feelings" },
      { fa: "کَم", en: "little, few", topic: "describing" },
      { fa: "پُر", en: "full", topic: "describing" },
      { fa: "کِشْتی", en: "ship", topic: "things" },
      { fa: "کُشْتی", en: "wrestling", topic: "everyday" },
      { fa: "کار", en: "work", topic: "everyday" },
      { fa: "کَر", en: "deaf", topic: "body" },
    ],
    blocks: [
      {
        type: "idea",
        text: "Persian has three short vowels, *a*, *e* and *o*, written as small marks: **zabar** ([ـَ|]) above, **zir** ([ـِ|]) below, and **pish** ([ـُ|]) above.",
      },
      {
        type: "text",
        text: "A mark sits on the consonant it follows: [بَ|ba] is *ba*, [بِ|be] is *be*, [بُ|bo] is *bo*. The *a* is short and bright, close to the *a* in *cat*; the *e* is the *e* of *bed*; the *o* is like the *o* of *go*, but short and without the glide.",
      },
      {
        type: "syllables",
        consonants: ["ب", "د", "ک", "م"],
        vowels: ["a", "e", "o"],
        caption: "Each consonant with zabar, zir and pish",
      },
      {
        type: "examples",
        items: [
          { fa: "دَر", en: "door" },
          { fa: "دِل", en: "heart (feelings)" },
          { fa: "گُل", en: "flower" },
          { fa: "کَم", en: "little, few" },
          { fa: "پُر", en: "full" },
        ],
      },
      {
        type: "pair",
        title: "Same letters, different vowel",
        a: { fa: "کِشْتی", en: "ship" },
        b: { fa: "کُشْتی", en: "wrestling" },
        diff: "The same four letters: with a zir, *keshti* is a ship; with a pish, *koshti* is wrestling, one of Iran's best-loved sports. Unmarked text leaves you to tell them apart from the sentence.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "Saying the short *a* like *father*",
        text: "The zabar *a* is short and bright. The long *â*, like the *a* of *father*, is written with ا (next lesson). Mixing them changes words: کَر (*kar*) is *deaf*, کار (*kâr*) is *work*.",
      },
      {
        type: "callout",
        kind: "culture",
        title: "Why the marks disappear",
        text: "Iranian readers know the words, so the short vowels are left out, much as English readers don't need help to tell *read* (now) from *read* (yesterday). Children's first books, the Quran and some poetry print them in full.",
      },
      {
        type: "quiz",
        questions: [
          {
            prompt: "Which mark is the vowel *e*: zabar, zir or pish? Type its name.",
            lang: "en",
            answers: ["zir"],
            explain: "Zir ([ـِ|]), under the letter: [بِ|be] is *be*.",
          },
          { prompt: "Transliterate دِل.", lang: "translit", answers: ["del"], explain: "دِل, *del*: heart." },
          {
            prompt: "Write *door* in Persian script.",
            lang: "fa",
            answers: ["در"],
            explain: "دَر, *dar*. Everyday writing leaves out the zabar: [در|dar].",
          },
        ],
      },
    ],
  },
  {
    slug: "long-vowels",
    title: "Long vowels: ا و ی as â, u and i",
    summary: "The long vowels are written with letters, so they are the anchors you can always see, even in unmarked text.",
    register: "written",
    kinds: ["pronunciation"],
    showTranslit: true,
    showMarks: true,
    source: SOURCE,
    vocab: [
      { fa: "باد", en: "wind", topic: "weather" },
      { fa: "بَد", en: "bad", topic: "describing" },
      { fa: "سیب", en: "apple", topic: "food" },
      { fa: "پیر", en: "old (of people)", topic: "describing" },
      { fa: "دور", en: "far", topic: "describing" },
      { fa: "نان", en: "bread", topic: "food" },
    ],
    blocks: [
      {
        type: "idea",
        text: "The long vowels are **letters**: ا is *â*, و is *u*, ی is *i*. Unlike the short vowels, they are always written.",
      },
      {
        type: "text",
        text: "*â* is a deep *a*, like the *a* of *father* said with slightly rounded lips; *u* is the *oo* of *food*; *i* is the *ee* of *see*. Because they are always written, the long vowels are your anchors when you read text without marks.",
      },
      {
        type: "syllables",
        consonants: ["ب", "د", "س", "ن"],
        vowels: ["â", "i", "u"],
        caption: "The long vowels are letters after the consonant",
      },
      {
        type: "examples",
        items: [
          { fa: "باد", en: "wind" },
          { fa: "سیب", en: "apple" },
          { fa: "دور", en: "far" },
          { fa: "نان", en: "bread" },
          { fa: "پیر", en: "old (of people)" },
        ],
      },
      {
        type: "pair",
        title: "Short or long",
        a: { fa: "بَد", en: "bad" },
        b: { fa: "باد", en: "wind" },
        diff: "A zabar gives a short *a*: *bad*. The letter ا gives a long *â*: *bâd*. In unmarked text only the long vowel is visible: [بد|bad] against باد.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "Reading ا as a short *a*",
        text: "Inside a word, ا is almost always the long *â*: باد is *bâd*, never *bad*.",
      },
      {
        type: "callout",
        kind: "culture",
        title: "Names to practise on",
        text: "Iranian names are good reading practice for the long vowels: سارا (*Sârâ*), مینا (*Minâ*), ناهید (*Nâhid*).",
      },
      {
        type: "quiz",
        questions: [
          { prompt: "Which letter spells the long vowel *u*? Type it.", lang: "fa", answers: ["و"], explain: "و: دور is *dur*." },
          {
            prompt: "Transliterate باد (type â, or aa).",
            lang: "translit",
            answers: ["bâd"],
            explain: "باد, *bâd*: wind. *bad* would be بَد.",
          },
          { prompt: "Transliterate سیب.", lang: "translit", answers: ["sib"], explain: "سیب, *sib*: apple." },
        ],
      },
    ],
  },
  {
    slug: "consonant-or-vowel",
    title: "و and ی: consonant or vowel?",
    summary: "Three rules decide whether و and ی are v and y, the vowels u and i, or part of the diphthongs ow and ey.",
    register: "written",
    kinds: ["pronunciation"],
    showTranslit: true,
    showMarks: true,
    source: SOURCE,
    vocab: [
      { fa: "وَرْزِش", en: "sport, exercise", topic: "everyday" },
      { fa: "یاد", en: "memory, remembering", topic: "feelings" },
      { fa: "میوه", en: "fruit", topic: "food" },
      { fa: "نَوروز", en: "Nowruz, the Persian New Year", topic: "time" },
      { fa: "رَوان", en: "fluent; flowing", topic: "describing" },
      { fa: "خَیلی", en: "very, a lot", topic: "describing" },
      { fa: "پاییز", en: "autumn", topic: "time" },
    ],
    blocks: [
      {
        type: "idea",
        text: "و and ی are **consonants** at the start of a word, before a vowel, or after a long vowel; **long vowels** after a bare consonant; and after a zabar, with no vowel following, they make the diphthongs *ow* and *ey*.",
      },
      {
        type: "table",
        headers: ["Where", "و", "ی"],
        rows: [
          ["At the start of a word", "وَقْت *vaqt*", "یاد *yâd*"],
          ["With a vowel after it", "هَوا *havâ*", "پاییز *pâyiz*"],
          ["After a long vowel", "گاو *gâv*", "چای *chây*"],
          ["After a bare consonant", "روز *ruz*", "سیب *sib*"],
          ["After a zabar", "نَو *now*", "کَی *key*"],
        ],
      },
      {
        type: "examples",
        items: [
          { fa: "وَرْزِش", en: "sport, exercise" },
          { fa: "یاد", en: "memory" },
          { fa: "میوه", en: "fruit" },
          { fa: "نَوروز", en: "Nowruz" },
          { fa: "خَیلی", en: "very" },
        ],
      },
      {
        type: "pair",
        title: "A vowel after it, or not",
        a: { fa: "روز", en: "day" },
        b: { fa: "رَوان", en: "fluent; flowing" },
        diff: "In روز the و follows a bare ر and is the vowel *u*: *ruz*. In رَوان a vowel (ا) follows it, so it is the consonant *v*: *ravân*.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "*ey*, not *ay*",
        text: "Zabar + ی sounds like the *ey* of *they*, said short: کَی is *key*, خَیلی is *kheyli*. Zabar + و is like the *ow* of *low* (not of *now*): نَوروز is *nowruz*.",
      },
      {
        type: "callout",
        kind: "culture",
        title: "Nowruz",
        text: "نَوروز (*nowruz*, “new day”) is the Persian New Year, at the spring equinox around 21 March. Families visit each other and lay the هَفْت‌سین, a table of seven things whose names start with س.",
      },
      {
        type: "quiz",
        questions: [
          {
            prompt: "Transliterate نَوروز.",
            lang: "translit",
            answers: ["nowruz"],
            explain: "نَوروز, *nowruz*: zabar before و makes *ow*.",
          },
          {
            prompt: "In [هَوا|] (air), is و a consonant or a vowel? Type consonant or vowel.",
            lang: "en",
            answers: ["consonant", "a consonant"],
            explain: "A vowel (ا) follows it, so it is the consonant *v*: *havâ*.",
          },
          { prompt: "Transliterate کَی (when).", lang: "translit", answers: ["key"], explain: "کَی, *key*." },
        ],
      },
    ],
  },
  {
    slug: "vowel-carriers",
    title: "Words that start with a vowel: ا and آ",
    summary: "No Persian word is written with a bare vowel at the start: alef carries it, and آ is the long â.",
    register: "written",
    kinds: ["pronunciation", "spelling"],
    showTranslit: true,
    showMarks: true,
    source: SOURCE,
    vocab: [
      { fa: "اَسْب", en: "horse", topic: "animals" },
      { fa: "اِمْروز", en: "today", topic: "time" },
      { fa: "اُسْتاد", en: "master; professor", topic: "people" },
      { fa: "اَبْرو", en: "eyebrow", topic: "body" },
      { fa: "آبِرو", en: "honour, good name", topic: "feelings" },
      { fa: "اَلُو", en: "hello (on the phone)", topic: "everyday" },
      { fa: "آره", en: "yes (everyday)", topic: "everyday" },
      { fa: "بَله", en: "yes (polite)", topic: "everyday" },
    ],
    blocks: [
      {
        type: "idea",
        text: "In writing, a Persian word never starts with a bare vowel: **alef carries it** ([اَ|a] *a*, [اِ|e] *e*, [اُ|o] *o*, [ای|i] *i*, [او|u] *u*), and آ is *â*.",
      },
      {
        type: "text",
        text: "A vowel mark can't stand on its own, so a word that starts with a vowel begins with alef, which carries it. Its mark, or the letter after it, gives the vowel. آ, alef with a madde, is the long *â*. In some words from Arabic, ع carries the vowel instead: عَلی *ali* (lesson 2.7).",
      },
      { type: "syllables", consonants: ["ا"], vowels: ["a", "e", "o", "â", "i", "u"], caption: "Alef carrying each vowel" },
      {
        type: "examples",
        items: [
          { fa: "اَسْب", en: "horse" },
          { fa: "اِمْروز", en: "today" },
          { fa: "اُسْتاد", en: "master; professor" },
          { fa: "ایران", en: "Iran" },
          { fa: "آب", en: "water" },
        ],
      },
      {
        type: "pair",
        title: "The madde changes the word",
        a: { fa: "اَبْرو", en: "eyebrow" },
        b: { fa: "آبِرو", en: "honour, one's good name" },
        diff: "With a zabar, اَبْرو (*abru*) is an eyebrow; with a madde and an extra *e*, آبِرو (*âberu*) is honour, literally the “water of the face”. To lose your آبِرو is to lose face.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "A plain alef for *â*",
        text: "A word that starts with *â* takes the madde: آب, not [اب|ab]. Without it the word reads with a short vowel.",
      },
      {
        type: "callout",
        kind: "culture",
        title: "Yes and hello",
        text: "On the phone Iranians answer اَلُو (*alo*, from French *allô*). *Yes* is بَله (*bale*) when polite and آره (*âre*) with friends.",
      },
      {
        type: "quiz",
        questions: [
          {
            prompt: "Type the letter that starts a word with the long *â*.",
            lang: "fa",
            answers: ["آ"],
            explain: "آ, alef with a madde: آب, *âb*.",
          },
          { prompt: "Transliterate اِمْروز.", lang: "translit", answers: ["emruz"], explain: "اِمْروز, *emruz*: today; alef carries the zir." },
          {
            prompt: "How is ای at the start of a word said? Type the vowel.",
            lang: "translit",
            answers: ["i"],
            explain: "*i*: ایران is *irân*.",
          },
        ],
      },
    ],
  },
  {
    slug: "vowel-letters",
    title: "Letters that spell a vowel: final ه, the o in تو, the silent و",
    summary: "A final ه that is only an e, a و that is o in a few words, and a و after خ that isn't said at all.",
    register: "both",
    kinds: ["pronunciation", "spelling"],
    showTranslit: true,
    showMarks: true,
    source: SOURCE,
    vocab: [
      { fa: "مَدْرِسه", en: "school", topic: "places" },
      { fa: "خُود", en: "self; own", topic: "everyday" },
      { fa: "خواهَر", en: "sister", topic: "people" },
      { fa: "خواب", en: "sleep", topic: "everyday" },
      { fa: "دُو", en: "two", topic: "numbers" },
      { fa: "ماه", en: "moon; month", topic: "time" },
      { fa: "کوه", en: "mountain", topic: "nature" },
      { fa: "بَعْداً", en: "later", topic: "time" },
    ],
    blocks: [
      {
        type: "idea",
        text: "Three spellings mislead readers: a final **ه** that is only an *e*, a **و** that is *o* in a few words, and a **و after خ** that isn't said at all.",
      },
      {
        type: "text",
        text: "After a consonant, a word-final ه is usually silent and only shows *e*: خانه *khâne*, مَدْرِسه *madrese*. After ا or و it is a real *h*: ماه *mâh* (moon, month), کوه *kuh* (mountain). A few short words say it too: دَهْ *dah* (ten) and نُهْ *noh* (nine), but سه is *se* (three). A handful of common words spell *o* with و: تُو (*to*, you), خُود (*khod*, self), دُو (*do*, two). And after خ, a و before ا or ی is silent: خواهَر is *khâhar* (sister), خواب *khâb* (sleep), خویشاوَنْد *khishâvand* (relative).",
      },
      {
        type: "examples",
        items: [
          { fa: "مَدْرِسه", en: "school" },
          { fa: "خُود", en: "self; own" },
          { fa: "خواهَر", en: "sister" },
          { fa: "خواب", en: "sleep" },
          { fa: "دُو", en: "two" },
        ],
      },
      {
        type: "pair",
        title: "Same letters, different sound",
        a: { fa: "تو", en: "in, inside (spoken)" },
        b: { fa: "تُو", en: "you (to a friend)" },
        diff: "Both are written تو: *tu* (in) and *to* (you). The sentence tells them apart; the transliteration here shows which is which.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "Saying the و in خواهَر",
        text: "خواهَر is *khâhar*, not *khvâhar*: the و after خ is silent (it was said centuries ago). The same goes for خواسْتَن (*khâstan*, to want) and خوانْدَن (*khândan*, to read).",
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "Where's your sister?",
        lines: [
          { who: "Ali", fa: "{خواهَرِت} کُجاسْت؟", written: "{خواهَرَت} کُجاسْت؟", en: "Where's your sister?" },
          { who: "Sara", fa: "{خوابه}.", written: "{خواب} اَسْت.", en: "She's asleep." },
          { who: "Ali", fa: "باشه، پَس بَعْداً میام.", written: "باشَد، پَس بَعْداً می‌آیَم.", en: "OK, then I'll come later." },
        ],
        note: "خواهَر and خواب both have the silent و. خوابه ends in the spoken ـه, *is*.",
      },
      {
        type: "quiz",
        questions: [
          { prompt: "Transliterate خواب.", lang: "translit", answers: ["khab", "khâb"], explain: "خواب, *khâb*: the و is silent." },
          {
            prompt: "Transliterate مَدْرِسه.",
            lang: "translit",
            answers: ["madrese"],
            explain: "مَدْرِسه, *madrese*: the final ه only shows *e*.",
          },
          {
            prompt: "Transliterate ماه.",
            lang: "translit",
            answers: ["mâh", "mah"],
            explain: "ماه, *mâh*: moon, month. After ا, a final ه is a real *h*.",
          },
          {
            prompt: "دو (two) is said…? Type the transliteration.",
            lang: "translit",
            answers: ["do"],
            explain: "*do*: one of the few words where و spells *o*.",
          },
        ],
      },
    ],
  },
  {
    slug: "tashdid-sukun-tanvin",
    title: "Tashdid, sokun and tanvin",
    summary: "Tashdid doubles a consonant, sokun shows no vowel follows, and tanvin adds -an to some words from Arabic.",
    register: "written",
    kinds: ["pronunciation", "spelling"],
    showTranslit: true,
    showMarks: true,
    source: SOURCE,
    vocab: [
      { fa: "بَچّه", en: "child", topic: "people" },
      { fa: "اَوَّل", en: "first", topic: "numbers" },
      { fa: "دَسْت", en: "hand", topic: "body" },
      { fa: "لُطْفاً", en: "please", topic: "everyday" },
      { fa: "مَثَلاً", en: "for example", topic: "everyday" },
      { fa: "فَوراً", en: "at once, immediately", topic: "time" },
      { fa: "بَنا", en: "building (formal)", topic: "places" },
      { fa: "بَنّا", en: "builder, mason", topic: "people" },
    ],
    blocks: [
      {
        type: "idea",
        text: "**Tashdid** (ـّ) doubles a consonant, **sokun** (ـْ) shows that no vowel follows it, and **tanvin** ([ـاً|]) adds *-an* to some words from Arabic.",
      },
      {
        type: "text",
        text: "A tashdid means the consonant is held longer, as if written twice: بَچّه is *bachche*. A sokun marks a consonant that ends a syllable: دَسْت is *dast*, with no vowel after the *s*. The last letter of a word doesn't need one: the ت of دَسْت has none. Tanvin sits on an alef at the end of certain words from Arabic, mostly adverbs: لُطْفاً (*lotfan*, please), مَثَلاً (*masalan*, for example), فَوراً (*fowran*, at once).",
      },
      {
        type: "examples",
        items: [
          { fa: "بَچّه", en: "child" },
          { fa: "اَوَّل", en: "first" },
          { fa: "دَسْت", en: "hand" },
          { fa: "لُطْفاً", en: "please" },
          { fa: "مَثَلاً", en: "for example" },
        ],
      },
      {
        type: "pair",
        title: "One consonant or two",
        a: { fa: "بَنا", en: "building (formal)" },
        b: { fa: "بَنّا", en: "builder, mason" },
        diff: "The tashdid holds the *n*: *banâ* (a building) becomes *bannâ* (a builder).",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "Dropping the doubled consonant",
        text: "Everyday writing leaves out the tashdid, but it is still pronounced: بَچّه is *bachche*, with a held *ch*.",
      },
      {
        type: "callout",
        kind: "culture",
        title: "Asking politely",
        text: "لُطْفاً is the polite *please* of requests and signs. In conversation Iranians often say بی‌زَحْمَت (*bizahmat*, literally “without trouble”) instead. خواهِش می‌کُنَم (*khâhesh mikonam*) is both an earnest *please* and the usual reply to thanks: *you're welcome*.",
      },
      {
        type: "quiz",
        questions: [
          {
            prompt: "Which mark doubles a consonant? Type its name.",
            lang: "en",
            answers: ["tashdid", "tashdeed", "shadda", "shaddah"],
            explain: "Tashdid (ـّ): بَچّه, *bachche*.",
          },
          {
            prompt: "Transliterate لُطْفاً.",
            lang: "translit",
            answers: ["lotfan"],
            explain: "لُطْفاً, *lotfan*: the tanvin on the alef is *-an*.",
          },
          { prompt: "Transliterate بَنّا.", lang: "translit", answers: ["banna", "bannâ"], explain: "بَنّا, *bannâ*: a builder." },
        ],
      },
    ],
  },
  {
    slug: "hamze-and-eyn",
    title: "Hamze and eyn: the catch in the throat",
    summary: "ء and ع are one sound in Persian: a light catch in the throat, silent at the start of a word.",
    register: "written",
    kinds: ["pronunciation", "spelling"],
    showTranslit: true,
    showMarks: true,
    source: SOURCE,
    vocab: [
      { fa: "رَئیس", en: "boss, head", topic: "people" },
      { fa: "سُؤال", en: "question", topic: "learning" },
      { fa: "مَسْئَله", en: "problem, issue", topic: "everyday" },
      { fa: "جُمْعه", en: "Friday", topic: "time" },
      { fa: "شَنْبه", en: "Saturday", topic: "time" },
      { fa: "مَعْنی", en: "meaning", topic: "learning" },
      { fa: "بَعْد", en: "after", topic: "time" },
    ],
    blocks: [
      {
        type: "idea",
        text: "ء (hamze) and ع (eyn) are **one sound** in Persian: a light catch in the throat. It is silent at the start of a word; inside a word it is a small break, or just a longer vowel.",
      },
      {
        type: "text",
        text: "Hamze has several seats: on its own (ء), on alef (أ), on و (ؤ) and on a dotless ی (ئ). Which seat a word uses is spelling, not sound. At the start of a word neither ع nor hamze is heard: عَلی is *ali*. Between vowels they make a small break: رَئیس *ra'is*, سُؤال *so'âl*, ساعَت *sâ'at*. Before a consonant the break is often just a longer vowel: بَعْد *ba'd*, مَعْنی *ma'ni*.",
      },
      {
        type: "examples",
        items: [
          { fa: "رَئیس", en: "boss, head" },
          { fa: "سُؤال", en: "question" },
          { fa: "مَسْئَله", en: "problem, issue" },
          { fa: "جُمْعه", en: "Friday" },
          { fa: "مَعْنی", en: "meaning" },
        ],
      },
      {
        type: "pair",
        title: "A break, or none",
        a: { fa: "بَعْد", en: "after" },
        b: { fa: "بَد", en: "bad" },
        diff: "بَعْد has an ع after the zabar: a small break, *ba'd*, often said with a longer *a*. بَد (*bad*) has none.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "Losing the hamze seat",
        text: "مَسْئَله takes ئ, a hamze on a dotless ی. The standard spelling is مَسْئَله; an older one, مَسْأَله, still appears. Writing it without the hamze, or with a plain ی, is a spelling mistake.",
      },
      {
        type: "callout",
        kind: "culture",
        title: "The Iranian week",
        text: "The week starts on شَنْبه (*shanbe*, Saturday), and جُمْعه (*jom'e*, Friday) is the main weekly day off.",
      },
      {
        type: "quiz",
        questions: [
          {
            prompt: "Transliterate سُؤال.",
            lang: "translit",
            answers: ["so'al", "so'âl"],
            explain: "سُؤال, *so'âl*: question; the hamze is a short break.",
          },
          {
            prompt: "Is the ع in [عَلی|] heard at the start of the word? Type yes or no.",
            lang: "en",
            answers: ["no"],
            explain: "No: at the start of a word ع is silent, *ali*.",
          },
          {
            prompt: "Write *question* in Persian.",
            lang: "fa",
            answers: ["سؤال"],
            explain: "سُؤال is the standard spelling; [سوال|so'âl], without the hamze, is common in informal typing but not standard.",
          },
        ],
      },
    ],
  },
  {
    slug: "stress",
    title: "Stress: where the beat falls",
    summary: "Nouns are stressed at the end, endings like “my” and “is” never take the stress, and verb prefixes pull it to the front.",
    register: "written",
    kinds: ["pronunciation"],
    showTranslit: true,
    showMarks: true,
    source: `${SOURCE} Stress rules after Mahootian, Persian, and Windfuhr, “Persian”, in The World's Major Languages.`,
    vocab: [
      { fa: "کِتابی", en: "bookish, formal (of language)", topic: "describing" },
      { fa: "رَفْتَن", en: "to go", topic: "verbs" },
    ],
    blocks: [
      {
        type: "idea",
        text: "Persian stresses the **last syllable** of nouns and adjectives; endings like *my* and *is* never take the stress, and verb prefixes pull it to the front.",
      },
      {
        type: "text",
        text: "In the transliteration below, the accent (´) marks the stressed vowel; it is not part of the spelling. Stress is not dramatic in Persian, but putting it in the wrong place is one of the clearest signs of a foreign accent.",
      },
      {
        type: "examples",
        items: [
          { fa: "کِتاب", en: "book", note: "*ketấb*: nouns stress the last syllable." },
          { fa: "کِتاب‌ها", en: "books", note: "*ketâbhấ*: the plural ending takes the stress." },
          { fa: "کِتابَم", en: "my book", note: "*ketấbam*: the ending for *my* is never stressed." },
          { fa: "می‌رَوَم", en: "I go", note: "*míravam*: verbs stress the prefix می‌." },
          { fa: "نَرَفْتَم", en: "I didn't go", note: "*náraftam*: the negative prefix *na-* takes the stress." },
          { fa: "نِمی‌رَوَم", en: "I don't go", note: "*némiravam*: with both prefixes, the negative wins." },
        ],
      },
      {
        type: "pair",
        title: "Same spelling, different stress",
        a: { fa: "کِتابی", en: "a book (*ketấbi*)" },
        b: { fa: "کِتابی", en: "bookish, formal (*ketâbí*)" },
        diff: "The ـی meaning *a* is never stressed: *ketấbi*, a book. The ـی that makes an adjective is: *ketâbí*, bookish, as in bookish Persian.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "Stressing the ending",
        text: "In کِتابَم (*my book*) and خوبَم (*I'm fine*) the ending is unstressed: *ketấbam*, *khúbam*. Stressing it sounds foreign.",
      },
      {
        type: "callout",
        kind: "culture",
        title: "Calling someone",
        text: "Names follow the noun pattern, with the stress at the end: *Maryám*, *Rezấ*. But when you call out to someone, the stress moves to the front: *Máryam!*",
      },
      {
        type: "quiz",
        questions: [
          {
            prompt: "Where is the stress in کِتاب: on the first or the last syllable?",
            lang: "en",
            answers: [
              "last",
              "the last",
              "last syllable",
              "the last syllable",
              "on the last",
              "on the last syllable",
              "final",
              "the final",
              "the final syllable",
              "second",
              "the second",
              "the second syllable",
            ],
            explain: "*ketấb*: nouns are stressed on the last syllable.",
          },
          {
            prompt: "In می‌رَوَم (I go), which part takes the stress? Type it in Persian.",
            lang: "fa",
            answers: ["می", "می‌"],
            explain: "The prefix می‌: *míravam*.",
          },
          {
            prompt: "Is the ending ـَم in کِتابَم (my book) stressed? Type yes or no.",
            lang: "en",
            answers: ["no"],
            explain: "No: *ketấbam*.",
          },
        ],
      },
    ],
  },
];
