import type { Lesson } from "../types";

// Unit 9, where, when, how much: prepositions, place words, this and that,
// numbers, time and prices, and comparing. Spoken Tehrani first, written
// beneath. Examples are original.

const SOURCE =
  "Mahootian, Persian (Routledge Descriptive Grammars), on prepositions, demonstratives, numerals and comparison; Thackston, An Introduction to Persian; Lazard, A Grammar of Contemporary Persian; the Academy's دستورِ خَطِّ فارسی for the half-space before ـتَر; Stilo, Talattof and Clinton, Modern Persian: Spoken and Written, for the Tehrani forms.";

export const whereWhen: Lesson[] = [
  {
    slug: "prepositions",
    title: "The core prepositions: به, اَز, با, دَر, بَرایِ, تا",
    summary: "Prepositions come before the noun, as in English, and the simple ones take no ezafe: به تِهْران, to Tehran. Speech says تو for دَر.",
    register: "both",
    kinds: ["prepositions", "grammar"],
    source: SOURCE,
    vocab: [
      { fa: "به", en: "to", topic: "everyday" },
      { fa: "اَز", en: "from; than", topic: "everyday" },
      { fa: "با", en: "with; by (a vehicle)", topic: "everyday" },
      { fa: "تو", en: "in, at, inside (spoken)", topic: "everyday" },
      { fa: "دَر", en: "in, at (written)", topic: "everyday" },
      { fa: "واسهٔ", written: "بَرایِ", en: "for", topic: "everyday" },
      { fa: "تا", en: "until; as far as; (counting word)", topic: "everyday" },
      { fa: "اُتُوبوس", en: "bus", topic: "things" },
      { fa: "مِتْرُو", en: "metro, underground", topic: "places" },
      { fa: "ایسْتْگاه", en: "station, stop", topic: "places" },
      { fa: "مَیدون", written: "مَیدان", en: "square (in a town)", topic: "places" },
      { fa: "هِدیه", en: "present, gift", topic: "things" },
      { fa: "دَقیقه", en: "minute", topic: "time" },
      { fa: "پیاده", en: "on foot", topic: "everyday" },
      { fa: "چِقَدْر", en: "how much", topic: "everyday" },
      { fa: "مامان", en: "mum", topic: "people" },
      { fa: "بِبَخْشید", en: "excuse me; sorry", topic: "everyday" },
    ],
    blocks: [
      {
        type: "idea",
        text: "Persian prepositions come **before** the noun, as in English, and the simple ones take **no ezafe**: به تِهْران, *to Tehran*; اَز تِهْران, *from Tehran*.",
      },
      {
        type: "text",
        text: "A preposition (حَرْفِ اِضافه, *harf-e ezâfe*) ties a noun to the rest of the sentence. Six cover most needs. Speech changes two of them: دَر (*in*) is mostly a written word, and speech says تو (*tu*); بَرایِ (*for*) is often واسهٔ. بَرایِ and واسهٔ are the two here that do carry an ezafe. تو is the everyday short form of تویِ (next lesson), said without its ezafe. Speech also drops به when the place you are going to follows the verb: می‌رَم مَدْرِسه, *I'm going to school*.",
      },
      {
        type: "table",
        caption: "The core prepositions",
        headers: ["Word", "Meaning", "Example"],
        rows: [
          ["به", "to", "به مَدْرِسه (*to school*)"],
          ["اَز", "from; than", "اَز ایران (*from Iran*)"],
          ["با", "with; by (a vehicle)", "با دوسْتَم (*with my friend*)"],
          ["دَر", "in, at (written)", "دَر خانه (*at home*)"],
          ["تو", "in, at (spoken)", "تو خونه (*at home*)"],
          ["بَرایِ", "for", "بَرایِ شُما (*for you*)"],
          ["واسهٔ", "for (spoken)", "واسهٔ شُما (*for you*)"],
          ["تا", "until; as far as", "تا فَرْدا (*until tomorrow*)"],
        ],
      },
      {
        type: "text",
        text: "Each verb picks its own preposition, and it is not always the one English uses. *To tell* someone is به with گُفْتَن. *To ask* someone is اَز with پُرْسیدَن, literally *to ask from*. *To talk to* someone is با with حَرْف زَدَن, *to talk with*. Learn the preposition with the verb.",
      },
      { type: "heading", text: "Core examples" },
      {
        type: "examples",
        items: [
          {
            fa: "{اَز} تِهْرون رَفْتیم شیراز.",
            written: "{اَز} تِهْران {به} شیراز رَفْتیم.",
            en: "We went from Tehran to Shiraz.",
            note: "Speech puts the destination after the verb and drops به.",
          },
          { fa: "{با} اُتُوبوس میام.", written: "{با} اُتُوبوس می‌آیَم.", en: "I'm coming by bus." },
          { fa: "{تو} آشْپَزْخونه‌اَم.", written: "{دَر} آشْپَزْخانه هَسْتَم.", en: "I'm in the kitchen." },
          { fa: "این هِدیه {واسهٔ} مامانَمه.", written: "این هِدیه {بَرایِ} مادَرَم اَسْت.", en: "This present is for my mum." },
          { fa: "{اَز} ساعَتِ نُهْ {تا} پَنْج کار می‌کُنَم.", en: "I work from nine to five." },
        ],
      },
      { type: "heading", text: "Contrast pair" },
      {
        type: "pair",
        title: "To, and from",
        a: { fa: "می‌رَم ایران.", written: "{به} ایران می‌رَوَم.", en: "I'm going to Iran." },
        b: { fa: "{اَز} ایران میام.", written: "{اَز} ایران می‌آیَم.", en: "I'm coming from Iran." },
        diff: "به marks where to, اَز where from. Speech can leave به out when the place follows the verb; اَز is never left out.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "The English preposition with a Persian verb",
        text: "English *ask* takes no preposition, and learners who add one reach for به, *to*. پُرْسیدَن takes اَز: you ask *from* someone. Making the person the object does not work either: عَلی را پُرْسیدَم means *I asked about Ali*.",
        wrong: { fa: "{به} عَلی پُرْسیدَم.", en: "(meant: I asked Ali)" },
        right: { fa: "{اَز} عَلی پُرْسیدَم.", en: "I asked Ali." },
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "Finding the way",
        lines: [
          {
            who: "Visitor",
            fa: "بِبَخْشید، این اُتُوبوس {به} مَیدونِ آزادی می‌ره؟",
            written: "بِبَخْشید، این اُتُوبوس {به} مَیدانِ آزادی می‌رَوَد؟",
            en: "Excuse me, does this bus go to Azadi Square?",
          },
          { who: "Passer-by", fa: "نَه، بایَد {با} مِتْرُو بِرین.", written: "نَه، بایَد {با} مِتْرُو بِرَوید.", en: "No, you have to go by metro." },
          {
            who: "Visitor",
            fa: "{اَز} اینْجا {تا} ایسْتْگاه چِقَدْر راهه؟",
            written: "{اَز} اینْجا {تا} ایسْتْگاه چِقَدْر راه اَسْت؟",
            en: "How far is it from here to the station?",
          },
          { who: "Passer-by", fa: "پَنْج دَقیقه پیاده.", en: "Five minutes on foot." },
        ],
        note: "چِقَدْر راهه؟ is literally *how much road is it?*. A vehicle takes با: با اُتُوبوس, با مِتْرُو, با ماشین. Azadi Square, with its tower, is the western gateway of Tehran.",
      },
      {
        type: "quiz",
        questions: [
          { prompt: "Type the preposition *with*.", lang: "fa", answers: ["با"], explain: "با: *with* a person, and *by* a vehicle (با اُتُوبوس)." },
          { prompt: "Spoken: *at home* (two words).", lang: "fa", answers: ["تو خونه", "توی خونه"], explain: "تو خونه (*tu khune*); written دَر خانه." },
          { prompt: "Written: *at home* (two words).", lang: "fa", answers: ["در خانه"], explain: "دَر خانه: دَر is the written word for *in, at*." },
          {
            prompt: "Which preposition goes with پُرْسیدَن, *to ask* someone? Type it.",
            lang: "fa",
            answers: ["از"],
            explain: "اَز: اَز عَلی پُرْسیدَم, *I asked Ali*, literally *I asked from Ali*.",
          },
          {
            prompt: "Translate: با اُتُوبوس میام.",
            lang: "en",
            answers: ["i'm coming by bus", "i am coming by bus", "i'll come by bus", "i will come by bus", "i come by bus", "i'm coming on the bus", "i'll come on the bus"],
            explain: "*bâ otobus miyâm*: با with a vehicle is *by*.",
          },
        ],
      },
    ],
  },
  {
    slug: "place-words",
    title: "Place words with the ezafe: رویِ, زیرِ, کِنارِ, پیشِ",
    summary: "On, under, beside and behind are nouns linked by the ezafe: رویِ میز, on the table, is literally “the top of the table”.",
    register: "both",
    kinds: ["prepositions", "grammar"],
    source: SOURCE,
    vocab: [
      { fa: "رو", en: "on; the top, the surface", topic: "places" },
      { fa: "زیر", en: "under; the underside", topic: "places" },
      { fa: "کِنار", en: "beside; the side, the edge", topic: "places" },
      { fa: "پیش", en: "with, at (a person's place); before", topic: "places" },
      { fa: "جِلُو", en: "in front of; the front; forward", topic: "places" },
      { fa: "پُشْت", en: "behind; the back", topic: "places" },
      { fa: "بالا", en: "above; up; the top", topic: "places" },
      { fa: "بَین", en: "between; the space between", topic: "places" },
      { fa: "دُکْتُر", en: "doctor", topic: "people" },
      { fa: "مُبْل", en: "sofa, armchair", topic: "home" },
      { fa: "ساخْتِمون", written: "ساخْتِمان", en: "building", topic: "places" },
      { fa: "عَینَک", en: "glasses", topic: "things" },
    ],
    blocks: [
      {
        type: "idea",
        text: "Most *where* words are **nouns that take the ezafe**: رویِ میز is literally *the top of the table*, and means *on the table*.",
      },
      {
        type: "text",
        text: "Unlike the simple prepositions of the last lesson, these words are linked to what follows by the ezafe (lesson 6.1): زیرِ میز, کِنارِ دَر. After a vowel the ezafe is written ی (lesson 6.3): رویِ, تویِ, جِلُویِ, بالایِ. In speech the ezafe usually drops after رو and تو: رو میز, تو کیف. For *in*, writing has both تویِ and دَر; دَر is the more formal. Because they are nouns, another preposition can stand in front: اَز زیرِ میز, *from under the table*. پیشِ is for people: پیشِ مَن is *with me* or *at my place*, and you go پیشِ دُکْتُر, *to the doctor*.",
      },
      {
        type: "table",
        caption: "Place words",
        headers: ["Word", "Literally", "Means", "Example"],
        rows: [
          ["رویِ", "the face of, the surface of", "on", "رویِ میز"],
          ["زیرِ", "the underside of", "under", "زیرِ میز"],
          ["تویِ", "the inside of", "in, inside", "تویِ کیف"],
          ["کِنارِ", "the side of", "beside, next to", "کِنارِ دَر"],
          ["جِلُویِ", "the front of", "in front of", "جِلُویِ خانه"],
          ["پُشْتِ", "the back of", "behind", "پُشْتِ خانه"],
          ["بالایِ", "the top part of", "above, over", "بالایِ دَر"],
          ["بَینِ", "the space between", "between", "بَینِ ما"],
          ["پیشِ", "the front of, before", "with, at (a person)", "پیشِ مَن"],
        ],
      },
      { type: "heading", text: "Core examples" },
      {
        type: "examples",
        items: [
          { fa: "کِتاب {رو} میزه.", written: "کِتاب {رویِ} میز اَسْت.", en: "The book is on the table." },
          { fa: "گُرْبه {زیرِ} تَخْته.", written: "گُرْبه {زیرِ} تَخْت اَسْت.", en: "The cat is under the bed." },
          { fa: "{کِنارِ} مَن بِشین.", written: "{کِنارِ} مَن بِنِشین.", en: "Sit next to me." },
          { fa: "دیشَب {پیشِ} مادَرْبُزُرْگَم بودَم.", en: "I was at my grandmother's last night." },
          { fa: "بانْک {پُشْتِ} اون ساخْتِمونه.", written: "بانْک {پُشْتِ} آن ساخْتِمان اَسْت.", en: "The bank is behind that building." },
        ],
      },
      { type: "heading", text: "Contrast pair" },
      {
        type: "pair",
        title: "In it, or on it",
        a: { fa: "کِلید {تو} کیفه.", written: "کِلید {تویِ} کیف اَسْت.", en: "The key is in the bag." },
        b: { fa: "کِلید {رو} کیفه.", written: "کِلید {رویِ} کیف اَسْت.", en: "The key is on the bag." },
        diff: "تو is the inside, رو the top surface. In speech neither needs its ezafe; in writing both take it.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "English “on” is not always رو",
        text: "رو is the top surface of something. On a bus, a train or a plane you are inside it, so Persian says تو. The same goes for *on the street*: تو خیابون.",
        wrong: { fa: "{رو} اُتُوبوسَم.", written: "{رویِ} اُتُوبوس هَسْتَم.", en: "(meant: I'm on the bus; this says: on its roof)" },
        right: { fa: "{تو} اُتُوبوسَم.", written: "{دَر} اُتُوبوس هَسْتَم.", en: "I'm on the bus." },
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "Lost glasses",
        lines: [
          { who: "Pari", fa: "عَینَکَم کُجاسْت؟", en: "Where are my glasses?" },
          { who: "Saeed", fa: "{رو} میز نیسْت؟", written: "{رویِ} میز نیسْت؟", en: "Aren't they on the table?" },
          { who: "Pari", fa: "نَه. {زیرِ} مُبْل هَم نیسْت.", en: "No. They aren't under the sofa either." },
          { who: "Saeed", fa: "{تو} کیفِت نیسْت؟", written: "{دَر} کیفَت نیسْت؟", en: "Aren't they in your bag?" },
          { who: "Pari", fa: "آهان، پَیدا شُد! {کِنارِ} تِلِفُن بود.", en: "Ah, found them! They were next to the phone." },
        ],
        note: "عَینَک is singular in Persian, so the verbs are too: کُجاسْت, نیسْت, بود. پَیدا شُد is *it was found*: the شُدَن partner of پَیدا کَرْدَن.",
      },
      {
        type: "quiz",
        questions: [
          { prompt: "Written: *on the table* (two words).", lang: "fa", answers: ["روی میز"], explain: "رویِ میز (*ru-ye miz*): after the vowel of رو the ezafe is written ی." },
          {
            prompt: "Spoken, without the ezafe: *on the bed* (two words).",
            lang: "fa",
            answers: ["رو تخت"],
            explain: "رو تَخْت (*ru takht*): speech usually drops the ezafe after رو. رویِ تَخْت is said too.",
          },
          { prompt: "Write *under the bed* (two words).", lang: "fa", answers: ["زیر تخت", "زیر تختخواب"], explain: "زیرِ تَخْت (*zir-e takht*): the ezafe is said but not written." },
          {
            prompt: "Which place word means *with a person, at their place*? Type it.",
            lang: "fa",
            answers: ["پیش"],
            explain: "پیش: پیشِ مَن, *with me*; پیشِ مادَرْبُزُرْگَم, *at my grandmother's*.",
          },
          {
            prompt: "Translate: بانْک پُشْتِ اون ساخْتِمونه.",
            lang: "en",
            answers: ["the bank is behind that building", "the bank's behind that building", "the bank is at the back of that building"],
            explain: "*bânk posht-e un sâkhtemune*: پُشْتِ, literally *the back of*.",
          },
        ],
      },
    ],
  },
  {
    slug: "this-and-that",
    title: "This and that: این, آن, اینْجا, آنْجا",
    summary: "این is this and آن, spoken اون, is that. Before a noun they take no ezafe and never change: این کِتاب, this book.",
    register: "both",
    kinds: ["grammar", "word-order"],
    source: SOURCE,
    vocab: [
      { fa: "این", en: "this", topic: "everyday" },
      { fa: "اون", written: "آن", en: "that", topic: "everyday" },
      { fa: "اینا", written: "این‌ها", en: "these", topic: "everyday" },
      { fa: "اینْجا", en: "here", topic: "places" },
      { fa: "اونْجا", written: "آنْجا", en: "there", topic: "places" },
      { fa: "هَمین", en: "this very, this same", topic: "everyday" },
      { fa: "یِکی", en: "one (of them); someone", topic: "everyday" },
      { fa: "مال", en: "property; مالِ: belonging to, from", topic: "everyday" },
      { fa: "خانُم", en: "lady; Mrs, Ms", topic: "people" },
      { fa: "شُلوغ", en: "crowded, busy", topic: "describing" },
      { fa: "شیرین", en: "sweet", topic: "describing" },
      { fa: "کیلو", en: "kilo", topic: "numbers" },
    ],
    blocks: [
      {
        type: "idea",
        text: "این is *this* and آن (spoken اون) is *that*. Before a noun they take **no ezafe** and never change, whatever the noun does: این کِتاب, *this book*; این کِتاب‌ها, *these books*.",
      },
      {
        type: "text",
        text: "Pointing words come **before** the noun, unlike describers (lesson 6.1), and with no link. Before a noun they are called صِفَتِ اِشاره (*sefat-e eshâre*); standing alone, ضَمیرِ اِشاره (*zamir-e eshâre*). Standing alone, without a noun, they take the plural themselves: اینا (written این‌ها) is *these*, and اونا (written آن‌ها) is *those*, which is also the word for *they*. For places, اینْجا is *here* and اونْجا (written آنْجا) is *there*, each written as one word. *This one* and *that one* are این یِکی and اون یِکی. هَمین is *this very*: هَمین اَلان, *right now*; هَمین جا, *right here*.",
      },
      {
        type: "table",
        caption: "Pointing words",
        headers: ["", "Spoken", "Written"],
        rows: [
          ["this", "این", "این"],
          ["that", "اون", "آن"],
          ["these", "اینا", "این‌ها"],
          ["those", "اونا", "آن‌ها"],
          ["here", "اینْجا", "اینْجا"],
          ["there", "اونْجا", "آنْجا"],
        ],
      },
      { type: "heading", text: "Core examples" },
      {
        type: "examples",
        items: [
          { fa: "{این} چیه؟", written: "{این} چیسْت؟", en: "What's this?" },
          { fa: "{اون} خانُم مُعَلِّمِ مَنه.", written: "{آن} خانُم مُعَلِّمِ مَن اَسْت.", en: "That lady is my teacher." },
          { fa: "{اینا} مالِ کیه؟", written: "{این‌ها} مالِ کیسْت؟", en: "Whose are these?" },
          { fa: "{اینْجا} خَیلی شُلوغه.", written: "{اینْجا} خَیلی شُلوغ اَسْت.", en: "It's very crowded here." },
          {
            fa: "{اون یِکی} رُو می‌خوام.",
            written: "{آن یِکی} را می‌خواهَم.",
            en: "I want that one.",
            note: "رُو here is *ro*, the spoken را (lesson 6.7), not رو (*ru*), *on*.",
          },
        ],
      },
      { type: "heading", text: "Contrast pair" },
      {
        type: "pair",
        title: "This book, or this is a book",
        a: { fa: "{این} کِتاب", en: "this book (a phrase)" },
        b: { fa: "{این} کِتابه.", written: "{این} کِتاب اَسْت.", en: "This is a book." },
        diff: "No ezafe in either. Here, with *is* at the end, این is the subject and the words make a sentence; without it, این just points at the noun.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "A plural pointing word before a noun",
        text: "English says *these books*, with both words plural. In Persian only the noun takes the plural; the pointing word before it stays as it is. اینا is used only when it stands alone.",
        wrong: { fa: "{اینا} کِتابا", written: "{این‌ها} کِتاب‌ها", en: "(meant: these books)" },
        right: { fa: "{این} کِتابا", written: "{این} کِتاب‌ها", en: "these books" },
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "At the fruit stall",
        lines: [
          { who: "Customer", fa: "بِبَخْشید، {اینا} چَنْده؟", written: "بِبَخْشید، {این‌ها} چَنْد اَسْت؟", en: "Excuse me, how much are these?" },
          {
            who: "Seller",
            fa: "{اون} سیبا؟ کیلویی صَد هِزار تُومَن.",
            written: "{آن} سیب‌ها؟ کیلویی صَد هِزار تُومان.",
            en: "Those apples? A hundred thousand tomans a kilo.",
          },
          { who: "Customer", fa: "{اینا} چی؟", written: "{این‌ها} چِطُور؟", en: "What about these?" },
          {
            who: "Seller",
            fa: "{اینا} مالِ شُمالَن. خَیلی شیرینَن.",
            written: "{این‌ها} مالِ شُمالَنْد وَ خَیلی شیرینَنْد.",
            en: "These are from the north. They're very sweet.",
          },
          { who: "Customer", fa: "پَس اَز {هَمینا} دُو کیلو بِدین.", written: "پَس اَز {هَمین‌ها} دُو کیلو بِدَهید.", en: "Then give me two kilos of these." },
        ],
        note: "کیلویی is *per kilo*: the ending ـی on a measure means *each*. مالِ is *belonging to*, and of produce, *from*. هَمینا is *these very ones*.",
      },
      {
        type: "quiz",
        questions: [
          { prompt: "Spoken: *that* (one word).", lang: "fa", answers: ["اون"], explain: "اون (*un*); written آن." },
          {
            prompt: "Written: *those*, which is also *they* (one word).",
            lang: "fa",
            answers: ["آن‌ها", "آنها", "آنان"],
            explain: "آن‌ها, with a half-space before ـها; spoken اونا.",
          },
          { prompt: "Write *this book* (two words).", lang: "fa", answers: ["این کتاب"], explain: "این کِتاب: the pointing word first, and no ezafe." },
          { prompt: "Spoken: *there* (one word).", lang: "fa", answers: ["اونجا"], explain: "اونْجا (*unjâ*); written آنْجا." },
          {
            prompt: "Translate: اینْجا خَیلی شُلوغه.",
            lang: "en",
            answers: [
              "it's very crowded here",
              "it is very crowded here",
              "it's very busy here",
              "it is very busy here",
              "it's really crowded here",
              "it's really busy here",
              "here is very crowded",
              "this place is very crowded",
              "this place is very busy",
            ],
            explain: "*injâ kheyli sholughe*: اینْجا, *here*, is the subject.",
          },
        ],
      },
    ],
  },
  {
    slug: "numbers",
    title: "Numbers and the counting words تا and نَفَر",
    summary: "After a number the noun stays singular, and speech adds the counting word تا: سه تا کِتاب, three books.",
    register: "both",
    kinds: ["grammar", "spoken"],
    source: SOURCE,
    vocab: [
      { fa: "یازْدَهْ", en: "eleven", topic: "numbers" },
      { fa: "دَوازْدَهْ", en: "twelve", topic: "numbers" },
      { fa: "سیزْدَهْ", en: "thirteen", topic: "numbers" },
      { fa: "چَهارْدَهْ", en: "fourteen", topic: "numbers" },
      { fa: "پانْزْدَهْ", en: "fifteen", topic: "numbers" },
      { fa: "شانْزْدَهْ", en: "sixteen", topic: "numbers" },
      { fa: "هِفْدَهْ", en: "seventeen", topic: "numbers" },
      { fa: "هِجْدَهْ", en: "eighteen", topic: "numbers" },
      { fa: "نوزْدَهْ", en: "nineteen", topic: "numbers" },
      { fa: "سی", en: "thirty", topic: "numbers" },
      { fa: "چِهِل", en: "forty", topic: "numbers" },
      { fa: "پَنْجاه", en: "fifty", topic: "numbers" },
      { fa: "هَفْتاد", en: "seventy", topic: "numbers" },
      { fa: "هَشْتاد", en: "eighty", topic: "numbers" },
      { fa: "نَوَد", en: "ninety", topic: "numbers" },
      { fa: "دِویسْت", en: "two hundred", topic: "numbers" },
      { fa: "پانْصَد", en: "five hundred", topic: "numbers" },
      { fa: "نَفَر", en: "person (when counting people)", topic: "numbers" },
      { fa: "سال", en: "year", topic: "time" },
      { fa: "جوجه", en: "chick; chicken kebab", topic: "food" },
      { fa: "کَباب", en: "kebab", topic: "food" },
      { fa: "نوشابه", en: "soft drink", topic: "food" },
    ],
    blocks: [
      {
        type: "idea",
        text: "After a number the noun stays **singular**, and speech puts the counting word **تا** between them: سه تا کِتاب, *three books*; written سه کِتاب.",
      },
      {
        type: "text",
        text: "You know the numbers up to ten from lesson 1.10. Eleven to nineteen end in دَهْ (*ten*), and the tens have their own words. Three of the hundreds are irregular: دِویسْت, سیصَد and پانْصَد. The others are the number and صَد as one word: چَهارْصَد, شِشْصَد, هَفْتْصَد, هَشْتْصَد, نُهْصَد. Larger numbers are built from the biggest part down, joined by وُ (*o*, *and*): بیسْت وُ پَنْج is 25, and صَد وُ بیسْت وُ پَنْج is 125.",
      },
      {
        type: "table",
        caption: "Eleven to nineteen",
        headers: ["Number", "Persian"],
        rows: [
          ["۱۱", "یازْدَهْ"],
          ["۱۲", "دَوازْدَهْ"],
          ["۱۳", "سیزْدَهْ"],
          ["۱۴", "چَهارْدَهْ"],
          ["۱۵", "پانْزْدَهْ"],
          ["۱۶", "شانْزْدَهْ"],
          ["۱۷", "هِفْدَهْ"],
          ["۱۸", "هِجْدَهْ"],
          ["۱۹", "نوزْدَهْ"],
        ],
      },
      {
        type: "table",
        caption: "Tens, hundreds, a thousand",
        headers: ["Number", "Persian"],
        rows: [
          ["۲۰", "بیسْت"],
          ["۳۰", "سی"],
          ["۴۰", "چِهِل"],
          ["۵۰", "پَنْجاه"],
          ["۶۰", "شَصْت"],
          ["۷۰", "هَفْتاد"],
          ["۸۰", "هَشْتاد"],
          ["۹۰", "نَوَد"],
          ["۱۰۰", "صَد"],
          ["۲۰۰", "دِویسْت"],
          ["۳۰۰", "سیصَد"],
          ["۴۰۰", "چَهارْصَد"],
          ["۵۰۰", "پانْصَد"],
          ["۱۰۰۰", "هِزار"],
        ],
      },
      {
        type: "text",
        text: "A number makes the noun plural by itself, so the noun takes no plural ending: سه کِتاب. In speech a counting word (a classifier) comes in between. **تا** works for things and for people: سه تا کِتاب, دُو تا بَرادَر. It is not used after یه (*one*, *a*), and not before a measure of amount or time: دُو کیلو, سه روز, پَنْج دَقیقه. **نَفَر** counts people, in speech and in writing: سه نَفَر, *three people*. The two are not used together. To ask *how many*, say چَنْد تا, or چَنْد نَفَر for people. In Tehran speech شِش (*six*) is usually said شیش.",
      },
      { type: "heading", text: "Core examples" },
      {
        type: "examples",
        items: [
          { fa: "{دُو تا} چایی، لُطْفاً.", written: "{دُو} چای، لُطْفاً.", en: "Two teas, please." },
          { fa: "{سه تا} بَرادَر دارَم.", written: "{سه} بَرادَر دارَم.", en: "I have three brothers." },
          { fa: "{چَنْد نَفَرین}؟", written: "{چَنْد نَفَر} هَسْتید؟", en: "How many of you are there?" },
          {
            fa: "{بیسْت وُ پَنْج} سالَمه.",
            written: "{بیسْت وُ پَنْج} سال دارَم.",
            en: "I'm twenty-five.",
            note: "Speech says سالَمه, literally *it is my year*; writing says *I have twenty-five years*.",
          },
          {
            fa: "{یه کیلو} سیب وُ {دُو تا} نون می‌خوام.",
            written: "{یِک کیلو} سیب وَ {دُو} نان می‌خواهَم.",
            en: "I'd like a kilo of apples and two loaves of bread.",
            note: "No تا with a measure such as کیلو, and none after یه.",
          },
        ],
      },
      { type: "heading", text: "Contrast pair" },
      {
        type: "pair",
        title: "Books, or three books",
        a: { fa: "{کِتابا}", written: "{کِتاب‌ها}", en: "books" },
        b: { fa: "سه تا {کِتاب}", written: "سه {کِتاب}", en: "three books" },
        diff: "Without a number the plural ending says *more than one*. With a number, the number says it, and the noun stays singular.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "A plural after a number",
        text: "English says *three books*. In Persian the noun after a number, or after چَنْد (*how many*, *several*), stays singular.",
        wrong: { fa: "سه تا {کِتابا}", written: "سه {کِتاب‌ها}", en: "(meant: three books)" },
        right: { fa: "سه تا {کِتاب}", written: "سه {کِتاب}", en: "three books" },
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "At a kebab house",
        lines: [
          { who: "Waiter", fa: "{چَنْد نَفَرین}؟", written: "{چَنْد نَفَر} هَسْتید؟", en: "How many are you?" },
          { who: "Guest", fa: "{چَهار نَفَر}.", en: "Four." },
          { who: "Waiter", fa: "بِفَرْمایین. چی مَیل دارین؟", written: "بِفَرْمایید. چه مَیل دارید؟", en: "This way, please. What would you like?" },
          {
            who: "Guest",
            fa: "{دُو تا} کَباب، {یه} جوجه وُ {چَهار تا} نوشابه.",
            written: "{دُو} کَباب، {یِک} جوجه وَ {چَهار} نوشابه.",
            en: "Two kebabs, one chicken kebab and four soft drinks.",
          },
        ],
        note: "نَفَر counts the people at the table; تا counts the dishes. یه جوجه takes no تا. جوجه, literally *chick*, is short for the chicken kebab.",
      },
      {
        type: "quiz",
        questions: [
          { prompt: "Spoken: *three books* (three words).", lang: "fa", answers: ["سه تا کتاب"], explain: "سه تا کِتاب: the counting word تا, and a singular noun." },
          { prompt: "Written: *three books* (two words).", lang: "fa", answers: ["سه کتاب"], explain: "سه کِتاب: writing needs no counting word. The noun is still singular." },
          {
            prompt: "Write *twenty-five* in words (three words).",
            lang: "fa",
            answers: ["بیست و پنج"],
            explain: "بیسْت وُ پَنْج (*bist o panj*): the tens first, then وُ, then the units.",
          },
          { prompt: "Ask *how many people?* (two words).", lang: "fa", answers: ["چند نفر"], explain: "چَنْد نَفَر: نَفَر is the counting word for people." },
          {
            prompt: "Translate: سه تا بَرادَر دارَم.",
            lang: "en",
            answers: ["i have three brothers", "i've got three brothers", "i have got three brothers", "i have 3 brothers"],
            explain: "*se tâ barâdar dâram*: بَرادَر stays singular after the number.",
          },
        ],
      },
    ],
  },
  {
    slug: "time-and-prices",
    title: "Time, days and prices",
    summary: "The time is ساعَت and a number; “at eight” and “on Friday” take no preposition. A price is asked with چَنْده؟ and counted in tomans.",
    register: "both",
    kinds: ["grammar", "culture"],
    source: SOURCE,
    vocab: [
      { fa: "نیم", en: "half", topic: "numbers" },
      { fa: "رُبْع", en: "quarter", topic: "numbers" },
      { fa: "یِکْشَنْبه", en: "Sunday", topic: "time" },
      { fa: "دُوشَنْبه", en: "Monday", topic: "time" },
      { fa: "سه‌شَنْبه", en: "Tuesday", topic: "time" },
      { fa: "چَهارْشَنْبه", en: "Wednesday", topic: "time" },
      { fa: "پَنْجْشَنْبه", en: "Thursday", topic: "time" },
      { fa: "شُروع شُدَن", en: "to start, to begin", topic: "verbs" },
      { fa: "قَیمَت", en: "price", topic: "everyday" },
      { fa: "گِرون", written: "گِران", en: "expensive", topic: "describing" },
      { fa: "تَخْفیف", en: "discount", topic: "everyday" },
      { fa: "قابِلی نَداره", written: "قابِلی نَدارَد", en: "it's nothing (said when naming a price or giving something)", topic: "everyday" },
    ],
    blocks: [
      {
        type: "idea",
        text: "The time is **ساعَت** and a number: ساعَت هَشْته, *it's eight o'clock*. To say *at* a time or *on* a day, Persian uses **no preposition**: ساعَتِ هَشْت, *at eight*; جُمْعه, *on Friday*.",
      },
      {
        type: "text",
        text: "ساعَت is *hour*, *clock* and *o'clock*. To ask the time: ساعَت چَنْده؟ Minutes are added with وُ: هَشْت وُ دَهْ دَقیقه is *ten past eight*, هَشْت وُ نیم is *half past eight*, and هَشْت وُ رُبْع is *quarter past eight*. Before the hour, the minutes come first, with به: یه رُبْع به نُهْ (written یِک رُبْع به نُهْ), *a quarter to nine*. With the ezafe, ساعَتِ هَشْت is the phrase *at eight o'clock*, and ساعَتِ چَنْد؟ asks *at what time?*",
      },
      {
        type: "table",
        caption: "The days of the week",
        headers: ["Persian", "English"],
        rows: [
          ["شَنْبه", "Saturday"],
          ["یِکْشَنْبه", "Sunday"],
          ["دُوشَنْبه", "Monday"],
          ["سه‌شَنْبه", "Tuesday"],
          ["چَهارْشَنْبه", "Wednesday"],
          ["پَنْجْشَنْبه", "Thursday"],
          ["جُمْعه", "Friday"],
        ],
      },
      {
        type: "text",
        text: "The Iranian week begins on Saturday, and the days are counted from it: یِکْشَنْبه is *one after Saturday*. In these names the ن before ب is said *m*: *shambe*. Friday is the day off, and Thursday is a half day for many, so the weekend is traditionally Thursday and Friday. For a price, point and ask این چَنْده؟, *how much is this?*; for a total, چَنْد می‌شه؟, *how much does it come to?*",
      },
      { type: "heading", text: "Core examples" },
      {
        type: "examples",
        items: [
          { fa: "ساعَت {چَنْده}؟", written: "ساعَت {چَنْد اَسْت}؟", en: "What time is it?" },
          { fa: "ساعَت {هَشْت وُ نیمه}.", written: "ساعَت {هَشْت وُ نیم اَسْت}.", en: "It's half past eight." },
          { fa: "کِلاس {ساعَتِ نُهْ} شُروع می‌شه.", written: "کِلاس {ساعَتِ نُهْ} شُروع می‌شَوَد.", en: "Class starts at nine." },
          { fa: "{پَنْجْشَنْبه} میام.", written: "{پَنْجْشَنْبه} می‌آیَم.", en: "I'm coming on Thursday." },
          { fa: "این {چَنْده}؟", written: "قَیمَتِ این {چَنْد اَسْت}؟", en: "How much is this?" },
        ],
      },
      { type: "heading", text: "Contrast pair" },
      {
        type: "pair",
        title: "It's eight, or at eight",
        a: { fa: "{ساعَت} هَشْته.", written: "{ساعَت} هَشْت اَسْت.", en: "It's eight o'clock." },
        b: { fa: "{ساعَتِ} هَشْت میام.", written: "{ساعَتِ} هَشْت می‌آیَم.", en: "I'm coming at eight." },
        diff: "Without the ezafe, ساعَت is the subject: *the hour is eight*. With it, ساعَتِ هَشْت is one phrase, *at eight*, and it needs no preposition.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "A preposition before a day or a time",
        text: "English needs *on* Monday and *at* eight. In everyday Persian the day or the time stands alone. Formal writing sometimes puts دَر before them, but speech never does.",
        wrong: { fa: "{تو} دُوشَنْبه میام.", written: "{دَر} دُوشَنْبه می‌آیَم.", en: "(meant: I'm coming on Monday)" },
        right: { fa: "{دُوشَنْبه} میام.", written: "{دُوشَنْبه} می‌آیَم.", en: "I'm coming on Monday." },
      },
      {
        type: "callout",
        kind: "culture",
        title: "Tomans and rials",
        text: "The official currency is the rial, and banknotes are printed in rials. But prices are spoken, and mostly written, in **tomans**: in everyday use one toman is ten rials. In speech people often leave the thousands out as well, so پَنْجاه تُومَن can mean fifty thousand tomans. When a price sounds far too low, ask.",
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "Buying a shirt",
        lines: [
          { who: "Customer", fa: "این پیرْهَن {چَنْده}؟", written: "این پیراهَن {چَنْد اَسْت}؟", en: "How much is this shirt?" },
          {
            who: "Seller",
            fa: "قابِلی نَداره. {پانْصَد هِزار} تُومَن.",
            written: "قابِلی نَدارَد. {پانْصَد هِزار} تُومان.",
            en: "Really, it's nothing. Five hundred thousand tomans.",
          },
          {
            who: "Customer",
            fa: "خواهِش می‌کُنَم. یه کَم گِرونه. تَخْفیف می‌دین؟",
            written: "خواهِش می‌کُنَم. کَمی گِران اَسْت. تَخْفیف می‌دَهید؟",
            en: "That's kind of you. It's a little expensive. Could you give me a discount?",
          },
          { who: "Seller", fa: "بَرایِ شُما، {چَهارْصَد وُ پَنْجاه}.", en: "For you, four hundred and fifty." },
        ],
        note: "قابِلی نَداره, literally *it isn't worthy of you*, offers the thing as a gift. It is ta'ârof: nobody takes it up; you thank the seller and pay. In the last line هِزار تُومَن is left out, because the thousands are understood.",
      },
      {
        type: "quiz",
        questions: [
          { prompt: "Spoken: ask *what time is it?* (two words).", lang: "fa", answers: ["ساعت چنده"], explain: "ساعَت چَنْده؟; written ساعَت چَنْد اَسْت؟" },
          {
            prompt: "Write *half past eight*, without ساعَت (three words).",
            lang: "fa",
            answers: ["هشت و نیم"],
            explain: "هَشْت وُ نیم (*hasht o nim*): the hour, then وُ, then the half.",
          },
          { prompt: "Write *Monday* (one word).", lang: "fa", answers: ["دوشنبه"], explain: "دُوشَنْبه: *two after Saturday*." },
          {
            prompt: "Write *at nine o'clock* (two words; no preposition).",
            lang: "fa",
            answers: ["ساعت نه"],
            explain: "ساعَتِ نُهْ (*sâ'at-e noh*): the ezafe makes it *at nine*, and it is not written.",
          },
          {
            prompt: "Translate: این چَنْده؟",
            lang: "en",
            answers: ["how much is this", "how much is it", "how much does this cost", "what does this cost", "how much is this one", "how much does it cost", "what's the price of this"],
            explain: "*in chande?*: چَنْد, *how much*, with the spoken *is*.",
          },
        ],
      },
    ],
  },
  {
    slug: "comparing",
    title: "Comparing: ـتَر, ـتَرین and اَز",
    summary: "ـتَر makes “-er” and ـتَرین makes “-est”; “than” is اَز: بُزُرْگ‌تَر اَز, bigger than.",
    register: "both",
    kinds: ["grammar", "suffixes", "spelling"],
    source: SOURCE,
    vocab: [
      { fa: "بِهْتَرین", en: "the best", topic: "describing" },
      { fa: "کَمْتَر", en: "less, fewer", topic: "describing" },
      { fa: "زیاد", en: "much, many, a lot", topic: "describing" },
      { fa: "آروم", written: "آرام", en: "slow, calm, quiet", topic: "describing" },
      { fa: "مُهِم", en: "important", topic: "describing" },
      { fa: "ساکِت", en: "quiet, silent", topic: "describing" },
      { fa: "آپارْتِمان", en: "flat, apartment", topic: "home" },
      { fa: "اَز هَمه", en: "of all, than all", topic: "everyday" },
      { fa: "هَمه", en: "all, everyone", topic: "everyday" },
      { fa: "دُوُّم", en: "second", topic: "numbers" },
      { fa: "گِرون", written: "گِران", en: "expensive", topic: "describing" },
    ],
    blocks: [
      {
        type: "idea",
        text: "Add **ـتَر** to a describing word for *-er* and **ـتَرین** for *-est*; *than* is **اَز**: بُزُرْگ‌تَر, *bigger*; بُزُرْگ‌تَرین, *the biggest*.",
      },
      {
        type: "text",
        text: "The ـتَر form is the **comparative** (صِفَتِ بَرْتَر, *sefat-e bartar*) and the ـتَرین form the **superlative** (صِفَتِ بَرْتَرین). The two endings go on any describing word, long or short: گِران‌تَر is *more expensive*. They are joined with a half-space (lesson 3.2), except in a few fixed words that are written as one; the everyday ones are بِهْتَر, بیشْتَر, کَمْتَر. After a letter that does not join, nothing is needed: بَدْتَر, زودْتَر. Two of the fixed words do not come from the everyday word. *Better* is بِهْتَر, from the old word بِهْ (*good*), not from خوب. *More* is بیشْتَر, from بیش, and serves for زیاد. کَمْتَر (*less*) is simply کَم with ـتَر. In a comparison the thing you compare with usually comes first, with اَز, and the ـتَر word after it: اَز شیراز بُزُرْگ‌تَر, *bigger than Shiraz*. The other order, بُزُرْگ‌تَر اَز شیراز, is also correct, and common in writing.",
      },
      {
        type: "table",
        caption: "More and most",
        headers: ["Word", "-er", "-est"],
        rows: [
          ["بُزُرْگ (*big*)", "بُزُرْگ‌تَر", "بُزُرْگ‌تَرین"],
          ["کوچَک (*small*)", "کوچَک‌تَر", "کوچَک‌تَرین"],
          ["اَرْزان (*cheap*)", "اَرْزان‌تَر", "اَرْزان‌تَرین"],
          ["گِران (*expensive*)", "گِران‌تَر", "گِران‌تَرین"],
          ["خوب (*good*)", "بِهْتَر", "بِهْتَرین"],
          ["زیاد (*much*)", "بیشْتَر", "بیشْتَرین"],
          ["کَم (*little*)", "کَمْتَر", "کَمْتَرین"],
        ],
      },
      {
        type: "text",
        text: "The two forms sit in different places. A ـتَر word describing a noun follows it, with the ezafe, like any describer: یه خونهٔ بُزُرْگ‌تَر, *a bigger house*. A ـتَرین word goes **before** the noun, with no ezafe: بُزُرْگ‌تَرین شَهْر, *the biggest city*. Speech often makes its *-est* with اَز هَمه (*than all*) and ـتَر: اَز هَمه بِهْتَر, *best of all*.",
      },
      { type: "heading", text: "Core examples" },
      {
        type: "examples",
        items: [
          { fa: "تِهْرون اَز شیراز {بُزُرْگ‌تَره}.", written: "تِهْران اَز شیراز {بُزُرْگ‌تَر اَسْت}.", en: "Tehran is bigger than Shiraz." },
          { fa: "این {اَرْزون‌تَره}.", written: "این {اَرْزان‌تَر اَسْت}.", en: "This one is cheaper." },
          {
            fa: "فارْسیِ تُو اَز مَن {بِهْتَره}.",
            written: "فارْسیِ تُو اَز مَن {بِهْتَر اَسْت}.",
            en: "Your Persian is better than mine.",
            note: "اَز مَن is short for اَز فارْسیِ مَن, *than my Persian*.",
          },
          {
            fa: "{بُزُرْگ‌تَرین} شَهْرِ ایران تِهْرونه.",
            written: "{بُزُرْگ‌تَرین} شَهْرِ ایران تِهْران اَسْت.",
            en: "The biggest city in Iran is Tehran.",
          },
          {
            fa: "یه کَم {آروم‌تَر} حَرْف بِزَن، لُطْفاً.",
            written: "کَمی {آرام‌تَر} حَرْف بِزَن، لُطْفاً.",
            en: "Speak a little more slowly, please.",
          },
        ],
      },
      { type: "heading", text: "Contrast pair" },
      {
        type: "pair",
        title: "Better, and the best",
        a: { fa: "یه ماشینِ {بِهْتَر}", written: "یِک ماشینِ {بِهْتَر}", en: "a better car" },
        b: { fa: "{بِهْتَرین} ماشین", en: "the best car" },
        diff: "The ـتَر word follows the noun, linked by the ezafe. The ـتَرین word comes before the noun, and there is no ezafe between them.",
      },
      { type: "heading", text: "Common mistake" },
      {
        type: "callout",
        kind: "mistake",
        title: "بیشْتَر in front, as in “more expensive”",
        text: "English puts *more* in front of long words. Persian does not: every describing word takes ـتَر itself, and *better* is the one word بِهْتَر.",
        wrong: { fa: "این کِتاب {بیشْتَر گِرونه}.", written: "این کِتاب {بیشْتَر گِران اَسْت}.", en: "(meant: this book is more expensive)" },
        right: { fa: "این کِتاب {گِرون‌تَره}.", written: "این کِتاب {گِران‌تَر اَسْت}.", en: "This book is more expensive." },
      },
      { type: "heading", text: "In real conversation" },
      {
        type: "dialogue",
        title: "Two flats",
        lines: [
          { who: "Mona", fa: "کُدوم آپارْتِمان {بِهْتَره}؟", written: "کُدام آپارْتِمان {بِهْتَر اَسْت}؟", en: "Which flat is better?" },
          {
            who: "Kian",
            fa: "اَوَّلی {بُزُرْگ‌تَره}، وَلی دُوُّمی {اَرْزون‌تَره}.",
            written: "اَوَّلی {بُزُرْگ‌تَر اَسْت}، وَلی دُوُّمی {اَرْزان‌تَر اَسْت}.",
            en: "The first one is bigger, but the second is cheaper.",
          },
          { who: "Mona", fa: "کُدوم به مِتْرُو {نَزْدیک‌تَره}؟", written: "کُدام به مِتْرُو {نَزْدیک‌تَر اَسْت}؟", en: "Which is closer to the metro?" },
          { who: "Kian", fa: "دُوُّمی. اَز هَمه {مُهِم‌تَر}، {ساکِت‌تَر} هَم هَسْت.", en: "The second. Most important of all, it's quieter too." },
        ],
        note: "اَوَّلی and دُوُّمی are *the first one* and *the second one*. نَزْدیک takes به: *close to*. اَز هَمه مُهِم‌تَر is the spoken *-est*: *more important than all*.",
      },
      {
        type: "quiz",
        questions: [
          {
            prompt: "Written: *cheaper* (one word, with a half-space).",
            lang: "fa",
            answers: ["ارزان‌تر"],
            explain: "اَرْزان‌تَر: ـتَر after a half-space. Spoken: اَرْزون‌تَر.",
          },
          { prompt: "Write *less* (one word).", lang: "fa", answers: ["کمتر"], explain: "کَمْتَر: کَم with ـتَر, one of the few written as one word with no half-space." },
          {
            prompt: "Write *the best book* (two words).",
            lang: "fa",
            answers: ["بهترین کتاب"],
            explain: "بِهْتَرین کِتاب: the ـتَرین word goes before the noun, with no ezafe.",
          },
          { prompt: "Type the word for *than*.", lang: "fa", answers: ["از"], explain: "اَز, the same word as *from*: اَز شیراز بُزُرْگ‌تَر." },
          {
            prompt: "Translate: تِهْرون اَز شیراز بُزُرْگ‌تَره.",
            lang: "en",
            answers: ["tehran is bigger than shiraz", "tehran is larger than shiraz", "tehran's bigger than shiraz"],
            explain: "*tehrun az shirâz bozorgtare*: اَز شیراز, *than Shiraz*, usually comes before the ـتَر word.",
          },
        ],
      },
    ],
  },
];
