import type { CommonWord } from "./types";

export const BATCH_A: CommonWord[] = [
  { fa: "چه", spoken: "چی", en: "what", topic: "grammar" },
  { fa: "هَم", en: "also, too", topic: "grammar" },
  { fa: "فِکْر", en: "thought, idea", topic: "ideas" },
  { fa: "نیسْت", en: "is not, isn't", topic: "grammar" },
  { fa: "خُب", en: "well, OK (spoken)", topic: "everyday" },
  { fa: "فَقَط", en: "only, just", topic: "grammar" },
  { fa: "چیزی", en: "something; (with a negative) nothing", topic: "grammar" },
  { fa: "حالا", en: "now; well then", topic: "time" },
  { fa: "هَر", en: "every, each", topic: "grammar" },
  { fa: "یا", en: "or", topic: "grammar" },
  { fa: "هَسْت", en: "there is; is (emphatic)", topic: "grammar" },
  { fa: "مِثْلِ", en: "like, as", topic: "grammar" },
  { fa: "هیچ", en: "no, none; (with a negative) any at all", topic: "grammar" },
  { fa: "واقِعاً", en: "really", topic: "grammar" },
  { fa: "را", en: "(marks a specific direct object; spoken رو, ـو)", topic: "grammar" },
  { fa: "اَنْجام دادَن", en: "to do, to carry out", topic: "verbs" },
  { fa: "دُرُسْت", en: "right, correct; exactly", topic: "describing" },
  { fa: "رویِ", spoken: "رو", en: "on, on top of", topic: "grammar" },
  { fa: "زِنْدِگی", en: "life", topic: "ideas" },
  { fa: "اَسْت", en: "is (written)", topic: "grammar" },
  { fa: "مَورِد", en: "case, instance; item", topic: "ideas" },
  { fa: "مَمْنون", en: "thanks; grateful", topic: "everyday" },
  { fa: "کُمَک", en: "help", topic: "everyday" },
  { fa: "دوباره", en: "again", topic: "time" },
  { fa: "حَتّیٰ", en: "even", topic: "grammar" },
  { fa: "آدَم", en: "person, human being", topic: "people" },
  { fa: "نِگاه کَرْدَن", spoken: "نِگا کَرْدَن", en: "to look", topic: "verbs" },
  { fa: "پِسَر", en: "boy; son", topic: "people" },
  { fa: "گوش", en: "ear", topic: "body" },
  { fa: "گوش دادَن", en: "to listen", topic: "verbs" },
  { fa: "صُحْبَت کَرْدَن", en: "to talk, to speak (polite)", topic: "verbs" },
  { fa: "قَبْل", en: "before", topic: "time" },
  { fa: "قَرار", en: "arrangement, plan; a date (to meet)", topic: "everyday" },
  { fa: "دَرْبارهٔ", en: "about, concerning", topic: "grammar" },
  { fa: "هَمان", spoken: "هَمون", en: "that same, the very same", topic: "grammar" },
  { fa: "به خاطِرِ", en: "because of; for the sake of", topic: "grammar" },
  { fa: "اَصْلاً", en: "(with a negative) not at all; basically, in fact; (in questions) anyway", topic: "grammar" },
  { fa: "وُجود", en: "existence", topic: "ideas" },
  { fa: "وُجود داشْتَن", en: "to exist", topic: "verbs" },
  { fa: "قُرْبان", spoken: "قُرْبون", en: "sir (respectful); sacrifice", topic: "people" },
  { fa: "مَرْدُم", en: "people", topic: "people" },
  { fa: "اِسْتِفاده کَرْدَن", en: "to use", topic: "verbs" },
  { fa: "یَعْنی", en: "that is, I mean", topic: "grammar" },
  { fa: "اَلْبَتّه", en: "of course", topic: "grammar" },
  { fa: "مَگَر", spoken: "مَگه", en: "unless; (in questions) surely not…?", topic: "grammar" },
  { fa: "باز", en: "open; again", topic: "describing" },
  { fa: "آماده", en: "ready", topic: "describing" },
  { fa: "سَعْی کَرْدَن", en: "to try", topic: "verbs" },
  { fa: "خُوش", en: "pleasant, happy (in compounds)", topic: "describing" },
  { fa: "دُنْبالِ", en: "after; looking for", topic: "grammar" },
  { fa: "زَنْگ", en: "bell; ring, (phone) call; break (at school)", topic: "things" },
  { fa: "زِنْده", en: "alive", topic: "describing" },
  { fa: "نیاز", en: "need", topic: "ideas" },
  { fa: "هیچی", en: "nothing (spoken)", topic: "grammar" },
  { fa: "اِتِّفاق", en: "event, incident", topic: "ideas" },
  { fa: "اِتِّفاق اُفْتادَن", en: "to happen", topic: "verbs" },
  { fa: "خَبَر", en: "news", topic: "society" },
  { fa: "پُلیس", en: "police", topic: "society" },
  { fa: "دُنْیا", en: "world", topic: "places" },
  { fa: "باعِث شُدَن", en: "to cause", topic: "verbs" },
  { fa: "طَرَف", en: "side; party; (spoken) the person, the guy", topic: "people" },
  { fa: "اِجازه", en: "permission", topic: "everyday" },
  { fa: "پایین", en: "down, below; the bottom", topic: "places" },
  { fa: "مَنْظور", en: "meaning, intention", topic: "ideas" },
  { fa: "نِشان دادَن", spoken: "نِشون دادَن", en: "to show", topic: "verbs" },
  { fa: "مُرْده", en: "dead", topic: "describing" },
  { fa: "کامِلاً", en: "completely", topic: "grammar" },
  { fa: "هَمْچین", en: "such, like that (spoken)", topic: "grammar" },
  { fa: "جَواب", en: "answer", topic: "learning" },
  { fa: "اَوَّلین", en: "the first", topic: "numbers" },
  { fa: "رَفیق", en: "friend, mate", topic: "people" },
  { fa: "خون", en: "blood", topic: "body" },
  { fa: "فِرار کَرْدَن", en: "to escape, to run away", topic: "verbs" },
  { fa: "نِجات دادَن", en: "to save, to rescue", topic: "verbs" },
  { fa: "بَقیّه", en: "the rest", topic: "grammar" },
  { fa: "باوَر کَرْدَن", en: "to believe", topic: "verbs" },
  { fa: "اِحْساس", en: "feeling", topic: "feelings" },
  { fa: "دَقیقاً", en: "exactly", topic: "grammar" },
  { fa: "سَمْت", en: "direction, side", topic: "places" },
  { fa: "نِگَران", en: "worried", topic: "feelings" },
  { fa: "اِشْتِباه", en: "mistake; wrong", topic: "ideas" },
  { fa: "وارِد شُدَن", en: "to enter", topic: "verbs" },
  { fa: "اِنْتِخاب کَرْدَن", en: "to choose", topic: "verbs" },
  { fa: "اِزْدِواج", en: "marriage", topic: "people" },
  { fa: "اِزْدِواج کَرْدَن", en: "to marry", topic: "verbs" },
  { fa: "آخَرین", en: "the last", topic: "numbers" },
  { fa: "بَرْنامه", en: "plan; programme", topic: "everyday" },
  { fa: "حَرَکَت", en: "movement; departure", topic: "everyday" },
  { fa: "حَق", en: "right; truth", topic: "ideas" },
  { fa: "اَنْدازه", en: "size, amount", topic: "describing" },
  { fa: "حَمْله", en: "attack", topic: "society" },
  { fa: "مَرْگ", en: "death", topic: "ideas" },
  { fa: "مُتَوَجِّه شُدَن", en: "to notice, to realise", topic: "verbs" },
  { fa: "مُطْمَئِن", en: "sure, certain", topic: "feelings" },
  { fa: "حَقیقَت", en: "truth", topic: "ideas" },
  { fa: "عَوَض کَرْدَن", en: "to change, to swap", topic: "verbs" },
  { fa: "نَقْشه", en: "map; plan", topic: "things" },
  { fa: "اِعْتِماد", en: "trust", topic: "feelings" },
  { fa: "قُول", en: "promise", topic: "ideas" },
  { fa: "قُول دادَن", en: "to promise", topic: "verbs" },
  { fa: "حِس", en: "sense, feeling", topic: "feelings" },
  { fa: "جَنْگ", en: "war", topic: "society" },
  { fa: "قَضیّه", en: "matter, affair", topic: "ideas" },
  { fa: "اُفْتادَن", en: "to fall", topic: "verbs" },
  { fa: "تَماس", en: "contact; a call", topic: "everyday" },
  { fa: "شِلیک", en: "shot, firing", topic: "society" },
  { fa: "اِنْگار", en: "as if", topic: "grammar" },
  { fa: "دُروغ", en: "lie", topic: "ideas" },
  { fa: "دُروغ گُفْتَن", en: "to lie", topic: "verbs" },
  { fa: "شَبیهْ", en: "similar, like", topic: "describing" },
  { fa: "لِباس", en: "clothes; a dress", topic: "things" },
  { fa: "بَعْضی", en: "some", topic: "grammar" },
  { fa: "جور", en: "kind, sort", topic: "grammar" },
  { fa: "هَرْگِز", en: "never (written)", topic: "time" },
  { fa: "مَوضوع", en: "subject, topic", topic: "ideas" },
  { fa: "قَبول کَرْدَن", en: "to accept", topic: "verbs" },
  { fa: "عُنْوان", en: "title", topic: "learning" },
  { fa: "غَیرِ", en: "other than, except", topic: "grammar" },
  { fa: "واقِعی", en: "real", topic: "describing" },
  { fa: "مَجْبور", en: "forced, obliged", topic: "describing" },
  { fa: "کافی", en: "enough", topic: "describing" },
  { fa: "شُماره", en: "number (of a phone, a house)", topic: "numbers" },
  { fa: "سَریع", en: "fast, quick", topic: "describing" },
  { fa: "گُروه", en: "group", topic: "people" },
  { fa: "اِحْتِمالاً", en: "probably", topic: "grammar" },
  { fa: "عاشِق", en: "in love; lover", topic: "feelings" },
  { fa: "اینْقَدْر", en: "this much, so", topic: "grammar" },
  { fa: "اَحْمَق", en: "stupid; idiot", topic: "describing" },
  { fa: "دیوانه", spoken: "دیوونه", en: "crazy, mad", topic: "describing" },
  { fa: "تَصْمیم", en: "decision", topic: "ideas" },
  { fa: "تَصْمیم گِرِفْتَن", en: "to decide", topic: "verbs" },
  { fa: "گُذَشْته", en: "the past; past, last", topic: "time" },
  { fa: "پَرْوَنْده", en: "file, case", topic: "society" },
  { fa: "تیم", en: "team", topic: "society" },
  { fa: "تَغْییر", en: "change", topic: "ideas" },
  { fa: "بُلَنْد", en: "tall; long; loud", topic: "describing" },
  { fa: "داسْتان", en: "story", topic: "learning" },
  { fa: "عَقَب", en: "back, behind", topic: "places" },
  { fa: "مُدَّت", en: "period, length of time", topic: "time" },
  { fa: "تَرْک کَرْدَن", en: "to leave, to quit", topic: "verbs" },
  { fa: "یارو", en: "that guy (slang)", topic: "people" },
  { fa: "فَراموش کَرْدَن", en: "to forget", topic: "verbs" },
  { fa: "راسْت", en: "right (side); true, straight", topic: "describing" },
  { fa: "دُلار", en: "dollar", topic: "numbers" },
  { fa: "خارِج", en: "outside; abroad", topic: "places" },
  { fa: "جُدا", en: "separate", topic: "describing" },
  { fa: "بی‌خیال", en: "never mind; carefree", topic: "everyday" },
  { fa: "شِرْکَت", en: "company", topic: "society" },
  { fa: "بَخْش", en: "part, section", topic: "things" },
  { fa: "راجِع به", en: "about, concerning (less formal than دَرْبارهٔ)", topic: "grammar" },
  { fa: "کُنْتُرُل", en: "control", topic: "society" },
  { fa: "صورَت", en: "face", topic: "body" },
  { fa: "تَوَسُّطِ", en: "by (in writing, after a passive)", topic: "grammar" },
  { fa: "آخَر", en: "end; last", topic: "time" },
  { fa: "طول", en: "length", topic: "describing" },
  { fa: "اَفْراد", en: "individuals, people (plural of فَرْد)", topic: "people" },
  { fa: "قُدْرَت", en: "power", topic: "society" },
  { fa: "دَلیل", en: "reason", topic: "ideas" },
  { fa: "اِحْتیاج", en: "need", topic: "ideas" },
  { fa: "هَمْدیگَر", spoken: "هَمْدیگه", en: "each other", topic: "grammar" },
  { fa: "دَرْک کَرْدَن", en: "to understand, to grasp", topic: "verbs" },
  { fa: "بَس", en: "enough", topic: "grammar" },
  { fa: "شانْس", en: "luck, chance", topic: "ideas" },
  { fa: "تَقْریباً", en: "almost, about", topic: "grammar" },
  { fa: "مُراقِب", en: "careful; looking after", topic: "describing" },
  { fa: "آیَنْده", en: "future", topic: "time" },
  { fa: "طُور", en: "way, manner", topic: "grammar" },
  { fa: "تَبْدیل شُدَن", en: "to turn into, to become", topic: "verbs" },
  { fa: "مُوَفَّق", en: "successful", topic: "describing" },
  { fa: "مُبارِزه", en: "fight, struggle", topic: "society" },
  { fa: "کوچولو", en: "little, tiny (affectionate)", topic: "describing" },
  { fa: "قَتْل", en: "murder", topic: "society" },
  { fa: "اِنْسان", en: "human being", topic: "people" },
  { fa: "تَوَجُّه", en: "attention", topic: "ideas" },
  { fa: "مُحافِظَت", en: "protection", topic: "society" },
  { fa: "اِطِّلاعات", en: "information", topic: "learning" },
  { fa: "پیشْنَهاد", en: "suggestion, offer", topic: "ideas" },
  { fa: "مُلاقات", en: "meeting, visit", topic: "people" },
  { fa: "مَخْفی", en: "hidden, secret", topic: "describing" },
  { fa: "رابِطه", en: "relationship", topic: "people" },
  { fa: "شِکَسْت", en: "defeat, failure", topic: "ideas" },
  { fa: "شوخی", en: "joke", topic: "everyday" },
  { fa: "بَعْدی", en: "next", topic: "time" },
  { fa: "زِنْدان", spoken: "زِنْدون", en: "prison", topic: "society" },
  { fa: "رَفْتار", en: "behaviour", topic: "ideas" },
  { fa: "مَعْذِرَت", en: "apology", topic: "everyday" },
  { fa: "اِفْتِخار", en: "honour, pride", topic: "feelings" },
  { fa: "بیدار", en: "awake", topic: "describing" },
  { fa: "قِسْمَت", en: "part; episode; fate", topic: "things" },
  { fa: "هَدَف", en: "goal, aim", topic: "ideas" },
  { fa: "عَلاقه", en: "interest, fondness", topic: "feelings" },
  { fa: "آمْریکا", en: "America", topic: "places" },
  { fa: "نابود", en: "destroyed", topic: "describing" },
  { fa: "کامِل", en: "complete", topic: "describing" },
  { fa: "آزاد", en: "free", topic: "describing" },
  { fa: "تَوضیح", en: "explanation", topic: "learning" },
  { fa: "تَوضیح دادَن", en: "to explain", topic: "verbs" },
  { fa: "اَوضاع", en: "the situation, how things are", topic: "ideas" },
  { fa: "عَجَله", en: "hurry", topic: "everyday" },
  { fa: "مَسْخَره", en: "ridiculous; mockery", topic: "describing" },
  { fa: "پَرْواز", en: "flight", topic: "everyday" },
  { fa: "کِشْوَر", en: "country", topic: "places" },
  { fa: "عَمَل", en: "action; operation (surgery)", topic: "everyday" },
  { fa: "خَط", en: "line; script, handwriting", topic: "learning" },
  { fa: "پادِشاه", en: "king", topic: "people" },
  { fa: "قانون", en: "law", topic: "society" },
  { fa: "فُرْصَت", en: "opportunity", topic: "ideas" },
  { fa: "خَطَر", en: "danger", topic: "ideas" },
  { fa: "اَهَمّیَّت", en: "importance", topic: "ideas" },
  { fa: "سَوار شُدَن", en: "to get on (a vehicle), to ride", topic: "verbs" },
  { fa: "دَسْتور", en: "order, command; grammar", topic: "learning" },
  { fa: "لِذَّت", en: "pleasure", topic: "feelings" },
  { fa: "تَلاش", en: "effort", topic: "ideas" },
  { fa: "عَجیب", en: "strange", topic: "describing" },
  { fa: "هَمْراه", en: "together with; companion", topic: "people" },
  { fa: "شَرْمَنْده", en: "ashamed; sorry (polite)", topic: "feelings" },
  { fa: "فِشار", en: "pressure", topic: "ideas" },
  { fa: "خیال", en: "imagination, thought", topic: "ideas" },
  { fa: "گُزارِش", en: "report", topic: "society" },
  { fa: "میلیون", en: "million", topic: "numbers" },
  { fa: "قَوی", en: "strong", topic: "describing" },
  { fa: "آسیب", en: "harm, injury", topic: "body" },
  { fa: "روح", en: "spirit, soul", topic: "ideas" },
  { fa: "حَدْس", en: "guess", topic: "ideas" },
  { fa: "حَدْس زَدَن", en: "to guess", topic: "verbs" },
  { fa: "تَنْگ", en: "tight; narrow", topic: "describing" },
  { fa: "باقی", en: "remaining, the rest", topic: "grammar" },
  { fa: "مَأْمور", en: "officer, agent", topic: "society" },
  { fa: "ناراحَت", en: "upset, sad", topic: "feelings" },
  { fa: "مُعامِله", en: "deal, transaction", topic: "society" },
  { fa: "عَصَبانی", en: "angry", topic: "feelings" },
  { fa: "حَل کَرْدَن", en: "to solve", topic: "verbs" },
  { fa: "نَفَس", en: "breath", topic: "body" },
  { fa: "بَرَنْده", en: "winner", topic: "society" },
  { fa: "وِل کَرْدَن", en: "to let go", topic: "verbs" },
  { fa: "قاتِل", en: "murderer", topic: "society" },
  { fa: "اَرْزِش", en: "value, worth", topic: "ideas" },
  { fa: "سَفَر", en: "journey, trip", topic: "everyday" },
  { fa: "تَقْصیر", en: "fault, blame", topic: "ideas" },
  { fa: "مُواظِب", en: "careful", topic: "describing" },
  { fa: "جَشْن", en: "celebration, party", topic: "everyday" },
  { fa: "شَرْط", en: "condition; bet", topic: "ideas" },
  { fa: "بَرَّسی", en: "examination, review", topic: "society" },
  { fa: "خالی", en: "empty", topic: "describing" },
  { fa: "مَنْطَقه", en: "region, area", topic: "places" },
  { fa: "سیسْتِم", en: "system", topic: "things" },
  { fa: "قَطْع کَرْدَن", en: "to cut off", topic: "verbs" },
  { fa: "وَسَط", en: "middle", topic: "places" },
  { fa: "صَدَمه", en: "injury, damage", topic: "body" },
  { fa: "مُسابِقه", en: "competition, match", topic: "society" },
  { fa: "ساده", en: "simple", topic: "describing" },
  { fa: "طَبَقه", en: "floor, storey; class", topic: "home" },
];
