import type { CommonWord } from "./types";

export const BATCH_B: CommonWord[] = [
  { fa: "دَریافْت کَرْدَن", en: "to receive", topic: "verbs" },
  { fa: "اَرْتِش", en: "army", topic: "society" },
  { fa: "سَم", en: "poison", topic: "things" },
  { fa: "جُز", en: "except", topic: "grammar" },
  { fa: "ایده", en: "idea", topic: "ideas" },
  { fa: "داداش", en: "brother (affectionate, spoken)", topic: "people" },
  { fa: "تِکّه", spoken: "تیکه", en: "piece", topic: "things" },
  { fa: "نَمایِش", en: "show, display", topic: "everyday" },
  { fa: "گِریه", en: "crying", topic: "feelings" },
  { fa: "گِریه کَرْدَن", en: "to cry", topic: "verbs" },
  { fa: "چُنین", en: "such (written)", topic: "grammar" },
  { fa: "دَرْخواسْت", en: "request", topic: "everyday" },
  { fa: "دَفْتَر", en: "notebook; office", topic: "things" },
  { fa: "قَسَم", en: "oath", topic: "ideas" },
  { fa: "قَسَم خُورْدَن", en: "to swear (an oath)", topic: "verbs" },
  { fa: "بابَتِ", en: "for, on account of", topic: "grammar" },
  { fa: "مُراقِبَت", en: "care", topic: "everyday" },
  { fa: "قَدَم", en: "step", topic: "everyday" },
  { fa: "ضَرْبه", en: "blow, hit", topic: "everyday" },
  { fa: "مَراسِم", en: "ceremony", topic: "society" },
  { fa: "جَرَیان", en: "flow; what is going on", topic: "ideas" },
  { fa: "اِداره", en: "office, department; running, management", topic: "society" },
  { fa: "وَضْعیَّت", en: "situation, condition", topic: "ideas" },
  { fa: "آشْنا", en: "acquainted; an acquaintance", topic: "people" },
  { fa: "مَوقِعیَّت", en: "position, situation", topic: "ideas" },
  { fa: "خَنْده", en: "laughter", topic: "feelings" },
  { fa: "خَنْدیدَن", en: "to laugh", topic: "verbs" },
  { fa: "تَصَوُّر", en: "imagination", topic: "ideas" },
  { fa: "مَحَل", en: "place, location", topic: "places" },
  { fa: "ذَرّه", en: "particle, bit", topic: "things" },
  { fa: "عَجَب", en: "what a…!; how strange", topic: "everyday" },
  { fa: "مَسیر", en: "route, way", topic: "places" },
  { fa: "فَرْمانْده", en: "commander", topic: "society" },
  { fa: "صَحْنه", en: "scene; stage", topic: "everyday" },
  { fa: "جَناب", en: "sir; the honourable (before a name, very formal)", topic: "people" },
  { fa: "اِمْکان", en: "possibility", topic: "ideas" },
  { fa: "اِحْتِرام", en: "respect", topic: "feelings" },
  { fa: "دَسْتْگاه", en: "device, machine", topic: "things" },
  { fa: "تَشَکُّر", en: "thanks", topic: "everyday" },
  { fa: "تَشَکُّر کَرْدَن", en: "to thank", topic: "verbs" },
  { fa: "آزْمایِش", en: "test, experiment", topic: "learning" },
  { fa: "نَتیجه", en: "result", topic: "ideas" },
  { fa: "بُمْب", en: "bomb", topic: "society" },
  { fa: "مَلِکه", en: "queen", topic: "people" },
  { fa: "شَک", en: "doubt", topic: "ideas" },
  { fa: "کَلّه", en: "head (informal)", topic: "body" },
  { fa: "مَرْکَز", en: "centre", topic: "places" },
  { fa: "بَرابَر", en: "equal; (دَر بَرابَرِ) in front of, against", topic: "describing" },
  { fa: "سازْمان", en: "organisation", topic: "society" },
  { fa: "بَحْث", en: "discussion, argument", topic: "ideas" },
  { fa: "پاک", en: "clean, pure", topic: "describing" },
  { fa: "حَد", en: "limit", topic: "ideas" },
  { fa: "سالِم", en: "healthy", topic: "describing" },
  { fa: "نَوع", en: "type, kind", topic: "grammar" },
  { fa: "تَمْرین", en: "exercise, practice", topic: "learning" },
  { fa: "اَطْراف", en: "surroundings, around", topic: "places" },
  { fa: "اِرْتِباط", en: "connection", topic: "ideas" },
  { fa: "دادْگاه", en: "court (of law)", topic: "society" },
  { fa: "فاصِله", en: "distance; gap", topic: "places" },
  { fa: "گُلوله", en: "bullet; ball (of yarn, snow)", topic: "things" },
  { fa: "نوشیدَنی", en: "a drink", topic: "food" },
  { fa: "تیر", en: "shot; arrow; beam; Tir (4th month)", topic: "things" },
  { fa: "مَرْبوط", en: "related", topic: "describing" },
  { fa: "دَرْدِسَر", en: "trouble, hassle", topic: "ideas" },
  { fa: "مِقْدار", en: "amount", topic: "numbers" },
  { fa: "اَمْنیَّت", en: "security, safety", topic: "society" },
  { fa: "قَهْرَمان", en: "hero; champion", topic: "people" },
  { fa: "حِسابی", en: "proper, thorough; properly", topic: "describing" },
  { fa: "تاریخ", en: "history; date", topic: "time" },
  { fa: "قُرْبانی", en: "victim; sacrifice", topic: "people" },
  { fa: "بو", en: "smell", topic: "everyday" },
  { fa: "تَحَمُّل", en: "tolerance, endurance", topic: "ideas" },
  { fa: "دورْبین", en: "camera", topic: "things" },
  { fa: "اَمْن", en: "safe", topic: "describing" },
  { fa: "مَکان", en: "place", topic: "places" },
  { fa: "پَخْش", en: "broadcast; distribution", topic: "society" },
  { fa: "جَهَنَّم", en: "hell", topic: "ideas" },
  { fa: "نِسْبَت", en: "relation; ratio", topic: "ideas" },
  { fa: "جَهان", en: "world", topic: "places" },
  { fa: "شَرایِط", en: "conditions, circumstances", topic: "ideas" },
  { fa: "ایجاد کَرْدَن", en: "to create", topic: "verbs" },
  { fa: "هَمْچُنین", en: "also, likewise (written)", topic: "grammar" },
  { fa: "جادّه", en: "road (between towns)", topic: "places" },
  { fa: "سُرْعَت", en: "speed", topic: "describing" },
  { fa: "سِتاره", en: "star", topic: "nature" },
  { fa: "شِکْل", en: "shape", topic: "describing" },
  { fa: "شَخْصی", en: "personal, private", topic: "describing" },
  { fa: "هَواپَیما", en: "aeroplane", topic: "things" },
  { fa: "هَمِگی", en: "all (of us, of them)", topic: "grammar" },
  { fa: "تُفَنْگ", en: "rifle, gun", topic: "things" },
  { fa: "خیانَت", en: "betrayal", topic: "ideas" },
  { fa: "سُراغ", en: "(go) to see; looking for", topic: "grammar" },
  { fa: "بیماری", en: "illness", topic: "body" },
  { fa: "جَلَسه", en: "meeting, session", topic: "society" },
  { fa: "زیبا", en: "beautiful", topic: "describing" },
  { fa: "حُدودِ", en: "about, approximately", topic: "numbers" },
  { fa: "هُتِل", en: "hotel", topic: "places" },
  { fa: "شَیطان", spoken: "شَیطون", en: "devil, Satan; (spoken) naughty, mischievous", topic: "ideas" },
  { fa: "لیسْت", en: "list", topic: "things" },
  { fa: "جَعْبه", en: "box", topic: "things" },
  { fa: "دَسْتْگیر کَرْدَن", en: "to arrest", topic: "verbs" },
  { fa: "تَرْجیح دادَن", en: "to prefer", topic: "verbs" },
  { fa: "دَولَت", en: "government", topic: "society" },
  { fa: "رَقْص", en: "dance", topic: "everyday" },
  { fa: "رَقْصیدَن", en: "to dance", topic: "verbs" },
  { fa: "فَرْق", en: "difference", topic: "ideas" },
  { fa: "دیوار", en: "wall", topic: "home" },
  { fa: "خُوشْگِل", en: "pretty, good-looking", topic: "describing" },
  { fa: "عَزیز", en: "dear", topic: "feelings" },
  { fa: "چَپ", en: "left (side)", topic: "places" },
  { fa: "تَمیز", en: "clean", topic: "describing" },
  { fa: "جَوان", spoken: "جَوون", en: "young; a young person", topic: "people" },
  { fa: "قایِق", en: "boat", topic: "things" },
  { fa: "مُتَوَقِّف کَرْدَن", en: "to stop (something)", topic: "verbs" },
  { fa: "دَعْوَت", en: "invitation", topic: "everyday" },
  { fa: "دَعْوَت کَرْدَن", en: "to invite", topic: "verbs" },
  { fa: "اَثَر", en: "effect; a work (of art)", topic: "ideas" },
  { fa: "سینه", en: "chest", topic: "body" },
  { fa: "مُشْت", en: "fist; a handful", topic: "body" },
  { fa: "زِنْدانی", en: "prisoner", topic: "society" },
  { fa: "شاه", en: "king, shah", topic: "people" },
  { fa: "تَرْس", en: "fear", topic: "feelings" },
  { fa: "تَرْسیدَن", en: "to be afraid", topic: "verbs" },
  { fa: "جَزیره", en: "island", topic: "nature" },
  { fa: "شُغْل", en: "job", topic: "society" },
  { fa: "دُشْمَن", en: "enemy", topic: "people" },
  { fa: "تَجْرُبه", en: "experience", topic: "ideas" },
  { fa: "دَرْمان", en: "treatment", topic: "body" },
  { fa: "آزادی", en: "freedom", topic: "society" },
  { fa: "وَکیل", en: "lawyer", topic: "society" },
  { fa: "نِصْف", en: "half", topic: "numbers" },
  { fa: "جُرْم", en: "crime", topic: "society" },
  { fa: "قانونی", en: "legal", topic: "society" },
  { fa: "ظاهِراً", en: "apparently", topic: "grammar" },
  { fa: "روزْنامه", en: "newspaper", topic: "society" },
  { fa: "پوسْت", en: "skin", topic: "body" },
  { fa: "خِدْمَت", en: "service", topic: "society" },
  { fa: "جالِب", en: "interesting", topic: "describing" },
  { fa: "گُنْده", en: "huge (informal)", topic: "describing" },
  { fa: "هَمْسَر", en: "spouse, husband or wife", topic: "people" },
  { fa: "اِشاره", en: "pointing; a reference", topic: "everyday" },
  { fa: "کاش", en: "if only, I wish", topic: "grammar" },
  { fa: "هَیَجان", en: "excitement", topic: "feelings" },
  { fa: "مَعْمولاً", en: "usually", topic: "time" },
  { fa: "حَلْقه", en: "ring; circle", topic: "things" },
  { fa: "مَسْئول", en: "responsible; the person in charge", topic: "society" },
  { fa: "عادی", en: "normal, ordinary", topic: "describing" },
  { fa: "مُحْکَم", en: "firm, tight", topic: "describing" },
  { fa: "اِضافه", en: "extra", topic: "describing" },
  { fa: "خاص", en: "special, particular", topic: "describing" },
  { fa: "سَرْباز", en: "soldier", topic: "society" },
  { fa: "قَطْعاً", en: "definitely", topic: "grammar" },
  { fa: "واقِعیَّت", en: "reality", topic: "ideas" },
  { fa: "شاهْزاده", en: "prince", topic: "people" },
  { fa: "گاز", en: "gas; a bite", topic: "things" },
  { fa: "وَسیله", en: "means; device; (plural) belongings", topic: "things" },
  { fa: "دُزْدی", en: "theft", topic: "society" },
  { fa: "تَسْلیم", en: "surrender", topic: "society" },
  { fa: "اِجْرا", en: "performance; carrying out", topic: "everyday" },
  { fa: "تَعْریف", en: "description; praise", topic: "ideas" },
  { fa: "تَعْریف کَرْدَن", en: "to tell (a story); to praise", topic: "verbs" },
  { fa: "دَرَجه", en: "degree", topic: "numbers" },
  { fa: "ویژه", en: "special", topic: "describing" },
  { fa: "بَلْکه", en: "but rather", topic: "grammar" },
  { fa: "موسیقی", en: "music", topic: "everyday" },
  { fa: "اِنْگِلیسی", en: "English", topic: "learning" },
  { fa: "مَأْموریَّت", en: "mission", topic: "society" },
  { fa: "شِکَر", en: "sugar", topic: "food" },
  { fa: "وَظیفه", en: "duty", topic: "society" },
  { fa: "اِعْتِراف", en: "confession", topic: "ideas" },
  { fa: "جَسَد", en: "corpse", topic: "body" },
  { fa: "تَهْدید", en: "threat", topic: "society" },
  { fa: "دَسْته", en: "group; handle", topic: "things" },
  { fa: "اَنْگیزه", en: "motive, motivation", topic: "ideas" },
  { fa: "مُقَدَّس", en: "holy", topic: "ideas" },
  { fa: "سِلاح", en: "weapon", topic: "society" },
  { fa: "نَمونه", en: "sample, example", topic: "learning" },
  { fa: "دُعا", en: "prayer", topic: "ideas" },
  { fa: "پَرْداخْت", en: "payment", topic: "society" },
  { fa: "رانَنْدِگی", en: "driving", topic: "everyday" },
  { fa: "مُعَرِّفی کَرْدَن", en: "to introduce", topic: "verbs" },
  { fa: "مُسْتَقیم", en: "straight, direct", topic: "describing" },
  { fa: "کُلاه", en: "hat", topic: "things" },
  { fa: "نُقْطه", en: "point, dot", topic: "things" },
  { fa: "بَرْخُورْد", en: "encounter; collision; attitude", topic: "ideas" },
  { fa: "تَبْریک", en: "congratulations", topic: "everyday" },
  { fa: "سِن", en: "age", topic: "people" },
  { fa: "مَغْز", en: "brain", topic: "body" },
  { fa: "تَرْتیب", en: "order, arrangement", topic: "ideas" },
  { fa: "مُدیر", en: "manager, head", topic: "society" },
  { fa: "تَکْرار", en: "repetition", topic: "learning" },
  { fa: "حِفْظ کَرْدَن", en: "to preserve; to learn by heart", topic: "verbs" },
  { fa: "فَرْد", en: "individual, person", topic: "people" },
  { fa: "پَرَنْده", en: "bird", topic: "animals" },
  { fa: "تَأْثیر", en: "effect, influence", topic: "ideas" },
  { fa: "حِرْفه", en: "profession", topic: "society" },
  { fa: "خاموش", en: "off, out (of a light); silent", topic: "describing" },
  { fa: "تاریکی", en: "darkness", topic: "nature" },
  { fa: "اِعْتِقاد", en: "belief", topic: "ideas" },
  { fa: "تَحْویل", en: "delivery, handing over", topic: "everyday" },
  { fa: "شَخْص", en: "person", topic: "people" },
  { fa: "اِطْمینان", en: "confidence, assurance", topic: "feelings" },
  { fa: "دَعْوا", en: "quarrel, fight", topic: "everyday" },
  { fa: "دَوره", en: "period; course", topic: "time" },
  { fa: "پَیغام", en: "message", topic: "everyday" },
  { fa: "حِمایَت", en: "support", topic: "society" },
  { fa: "شَوهَر", en: "husband", topic: "people" },
  { fa: "رَوانی", en: "mental; (informal) crazy", topic: "describing" },
  { fa: "بیچاره", en: "poor (to be pitied)", topic: "feelings" },
  { fa: "مُتَأَسِّفانه", en: "unfortunately", topic: "grammar" },
  { fa: "شَراب", en: "wine", topic: "food" },
  { fa: "ساحِل", en: "shore, beach", topic: "nature" },
  { fa: "اِعْلام", en: "announcement", topic: "society" },
  { fa: "ناپَدید", en: "vanished", topic: "describing" },
  { fa: "سیگار", en: "cigarette", topic: "things" },
  { fa: "قَدْر", en: "worth, value", topic: "ideas" },
  { fa: "کوتاه", en: "short", topic: "describing" },
  { fa: "زیرْنِویس", en: "subtitle", topic: "learning" },
  { fa: "عَصْر", en: "late afternoon; era", topic: "time" },
  { fa: "آفَرین", en: "well done!", topic: "everyday" },
  { fa: "نیمه", en: "half", topic: "numbers" },
  { fa: "عادَت", en: "habit", topic: "ideas" },
  { fa: "گَرْدَن", en: "neck", topic: "body" },
  { fa: "اَفْسَر", en: "officer", topic: "society" },
  { fa: "خَیر", en: "no (polite); good, charity", topic: "everyday" },
  { fa: "آموزِش", en: "education, training", topic: "learning" },
  { fa: "شِناسایی", en: "identification", topic: "society" },
  { fa: "قُفْل", en: "lock", topic: "things" },
  { fa: "گُناه", en: "sin", topic: "ideas" },
  { fa: "تَعْقیب", en: "pursuit, chase", topic: "society" },
  { fa: "حَواس", en: "attention; senses", topic: "ideas" },
  { fa: "شِکار", en: "hunting; prey", topic: "animals" },
  { fa: "سَرْزَمین", en: "land, country", topic: "places" },
  { fa: "مُشَخَّص", en: "clear, specific", topic: "describing" },
  { fa: "مُنْفَجِر شُدَن", en: "to explode", topic: "verbs" },
  { fa: "تُخْم", en: "seed; egg (of a bird; an egg to eat is تُخْمِ مُرْغ)", topic: "food" },
  { fa: "مُرْغ", en: "hen, chicken", topic: "animals" },
  { fa: "آرامِش", en: "calm, peace of mind", topic: "feelings" },
  { fa: "صاحِب", en: "owner", topic: "people" },
  { fa: "مَعْمولی", en: "ordinary", topic: "describing" },
  { fa: "اِمْضا", en: "signature", topic: "society" },
  { fa: "شَمْشیر", en: "sword", topic: "things" },
  { fa: "دَرون", en: "inside (written)", topic: "places" },
  { fa: "تَمَرْکُز", en: "concentration", topic: "ideas" },
  { fa: "هُشْدار", en: "warning", topic: "society" },
  { fa: "نَوبَت", en: "turn (in a queue)", topic: "everyday" },
  { fa: "باهوش", en: "clever", topic: "describing" },
  { fa: "کَیک", en: "cake", topic: "food" },
  { fa: "عُضْو", en: "member", topic: "society" },
  { fa: "ماجَرا", en: "adventure; what happened", topic: "ideas" },
  { fa: "شاهِد", en: "witness", topic: "society" },
  { fa: "خُداوَنْد", en: "God, the Lord", topic: "ideas" },
  { fa: "جایِزه", en: "prize", topic: "everyday" },
  { fa: "رَها کَرْدَن", en: "to let go, to abandon", topic: "verbs" },
  { fa: "تَعْداد", en: "number (how many)", topic: "numbers" },
  { fa: "واحِد", en: "unit; flat (in a building)", topic: "things" },
  { fa: "نِظامی", en: "military", topic: "society" },
  { fa: "فُروش", en: "sale, selling", topic: "society" },
  { fa: "خاک", en: "soil, dust", topic: "nature" },
  { fa: "قیافه", en: "looks, appearance", topic: "body" },
  { fa: "کِلیسا", en: "church", topic: "places" },
  { fa: "مَصْرَف", en: "consumption, use", topic: "society" },
  { fa: "تِلِویزیون", en: "television", topic: "things" },
  { fa: "سِوُّم", en: "third", topic: "numbers" },
  { fa: "سِرْویس", en: "service; a set; school bus", topic: "things" },
  { fa: "ثَبْت", en: "registration", topic: "society" },
  { fa: "کَثیف", en: "dirty", topic: "describing" },
  { fa: "نِگَهْبان", en: "guard", topic: "people" },
  { fa: "مُناسِب", en: "suitable", topic: "describing" },
  { fa: "راحَتی", en: "comfort, ease", topic: "feelings" },
  { fa: "پُل", en: "bridge", topic: "places" },
  { fa: "دَسْتْشویی", en: "toilet; washbasin", topic: "home" },
  { fa: "چوب", en: "wood; stick", topic: "things" },
  { fa: "راسْتی", en: "by the way; truthfulness", topic: "everyday" },
  { fa: "تَصادُف", en: "accident, crash; coincidence", topic: "everyday" },
  { fa: "شِکَسْته", en: "broken", topic: "describing" },
  { fa: "هَزینه", en: "cost", topic: "society" },
  { fa: "پیچیده", en: "complicated", topic: "describing" },
  { fa: "دَرْصَد", en: "percent", topic: "numbers" },
  { fa: "چِهْره", en: "face", topic: "body" },
  { fa: "سَرْنِوِشْت", en: "fate", topic: "ideas" },
  { fa: "چاقو", en: "knife", topic: "things" },
  { fa: "گاهی", en: "sometimes", topic: "time" },
  { fa: "مَدْرَک", en: "document; evidence; degree", topic: "society" },
  { fa: "بامَزه", en: "funny; cute", topic: "describing" },
  { fa: "بیمار", en: "ill; a patient", topic: "body" },
  { fa: "حُقوق", en: "salary; rights; law (as a subject)", topic: "society" },
  { fa: "خُصوصی", en: "private", topic: "describing" },
  { fa: "هَمْکاری", en: "cooperation", topic: "society" },
];
