import type { CommonWord } from "./types";

export const BATCH_C: CommonWord[] = [
  { fa: "دَسْتْرَسی", en: "access", topic: "ideas" },
  { fa: "سوراخ", en: "hole", topic: "things" },
  { fa: "اِنْتِقام", en: "revenge", topic: "ideas" },
  { fa: "عَصَبی", en: "irritable, on edge, upset; nervous (of the nerves)", topic: "feelings" },
  { fa: "شیشه", en: "glass (the material); bottle, jar", topic: "things" },
  { fa: "نِشانه", en: "sign, indication; aim, target", topic: "ideas" },
  { fa: "آرِزو", en: "wish", topic: "feelings" },
  { fa: "اِنِرْژی", en: "energy", topic: "ideas" },
  { fa: "مُدِل", en: "model; style", topic: "things" },
  { fa: "خِجالَت", en: "shyness, embarrassment", topic: "feelings" },
  { fa: "خِجالَت کِشیدَن", en: "to be shy, to be embarrassed", topic: "verbs" },
  { fa: "صُلْح", en: "peace", topic: "society" },
  { fa: "تَهْ", en: "bottom, end", topic: "places" },
  { fa: "زیبایی", en: "beauty", topic: "ideas" },
  { fa: "جُنوب", en: "south", topic: "places" },
  { fa: "فایِده", en: "use, benefit", topic: "ideas" },
  { fa: "فِرِشْته", en: "angel", topic: "ideas" },
  { fa: "راز", en: "secret", topic: "ideas" },
  { fa: "سُقوط", en: "fall, crash", topic: "everyday" },
  { fa: "خَرْج", en: "expense", topic: "society" },
  { fa: "وَحْشی", en: "wild", topic: "describing" },
  { fa: "عَلامَت", en: "sign, mark, symbol; symptom", topic: "things" },
  { fa: "باحال", en: "cool, fun (slang)", topic: "describing" },
  { fa: "دَرْوازه", en: "gate", topic: "places" },
  { fa: "گوشی", en: "(phone) receiver; mobile phone", topic: "things" },
  { fa: "اِخْراج", en: "dismissal, expulsion", topic: "society" },
  { fa: "اِحْتِمال", en: "probability, chance", topic: "ideas" },
  { fa: "فَرْض", en: "assumption", topic: "ideas" },
  { fa: "سَطْح", en: "level; surface", topic: "ideas" },
  { fa: "ایمان", en: "faith", topic: "ideas" },
  { fa: "خَطَرْناک", en: "dangerous", topic: "describing" },
  { fa: "راضی", en: "satisfied", topic: "feelings" },
  { fa: "اَذیَّت", en: "bother, annoyance", topic: "feelings" },
  { fa: "اَذیَّت کَرْدَن", en: "to bother, to tease", topic: "verbs" },
  { fa: "تَشْخیص", en: "diagnosis; telling apart", topic: "ideas" },
  { fa: "مَوجود", en: "existing, available; a creature", topic: "describing" },
  { fa: "غَریبه", en: "stranger", topic: "people" },
  { fa: "غَرْق", en: "drowned; sunk; absorbed", topic: "describing" },
  { fa: "زَخْم", en: "wound", topic: "body" },
  { fa: "نُکْته", en: "point, tip", topic: "ideas" },
  { fa: "تَأْیید", en: "confirmation, approval", topic: "society" },
  { fa: "موش", en: "mouse", topic: "animals" },
  { fa: "فَصْل", en: "season; chapter", topic: "time" },
  { fa: "رَأْی", en: "vote; opinion", topic: "society" },
  { fa: "کُت", en: "jacket (of a suit), blazer", topic: "things" },
  { fa: "تَحْقیق", en: "research", topic: "learning" },
  { fa: "رانَنْده", en: "driver", topic: "people" },
  { fa: "شَخْصیَّت", en: "personality; character", topic: "ideas" },
  { fa: "اَفْسانه", en: "legend", topic: "learning" },
  { fa: "تَعَجُّب", en: "surprise", topic: "feelings" },
  { fa: "وَحْشَتْناک", en: "terrible", topic: "describing" },
  { fa: "عُبور", en: "crossing, passing", topic: "everyday" },
  { fa: "پاره", en: "torn", topic: "describing" },
  { fa: "گُرْگ", en: "wolf", topic: "animals" },
  { fa: "صَفْحه", en: "page; screen", topic: "things" },
  { fa: "مِلّی", en: "national", topic: "society" },
  { fa: "مَسْئولیَّت", en: "responsibility", topic: "society" },
  { fa: "دُزْد", en: "thief", topic: "people" },
  { fa: "دُزْدیدَن", en: "to steal", topic: "verbs" },
  { fa: "تَماشا کَرْدَن", en: "to watch", topic: "verbs" },
  { fa: "طَبیعی", en: "natural", topic: "describing" },
  { fa: "دین", en: "religion", topic: "society" },
  { fa: "سَیّاره", en: "planet", topic: "nature" },
  { fa: "دانِش", en: "knowledge", topic: "learning" },
  { fa: "فیل", en: "elephant", topic: "animals" },
  { fa: "مُوَفَّقیَّت", en: "success", topic: "ideas" },
  { fa: "اَنْگُشْت", en: "finger", topic: "body" },
  { fa: "مَزه", en: "taste, flavour", topic: "food" },
  { fa: "خوک", en: "pig", topic: "animals" },
  { fa: "زَخْمی", en: "wounded", topic: "describing" },
  { fa: "اَصْل", en: "origin; principle", topic: "ideas" },
  { fa: "مَخْصوص", en: "special; meant for", topic: "describing" },
  { fa: "مَشْغول", en: "busy, occupied", topic: "describing" },
  { fa: "آزْمایِشْگاه", en: "laboratory", topic: "places" },
  { fa: "مَرْتَبه", en: "time (once, twice); level", topic: "numbers" },
  { fa: "تَوانایی", en: "ability", topic: "ideas" },
  { fa: "سایه", en: "shadow, shade", topic: "nature" },
  { fa: "بَسْتِگی داشْتَن", en: "to depend (on)", topic: "verbs" },
  { fa: "مالی", en: "financial", topic: "society" },
  { fa: "بِهِشْت", en: "paradise", topic: "ideas" },
  { fa: "گُرُسْنه", spoken: "گُشْنه", en: "hungry", topic: "feelings" },
  { fa: "نِگَرانی", en: "worry", topic: "feelings" },
  { fa: "پِنْهان", en: "hidden", topic: "describing" },
  { fa: "آبْجو", en: "beer", topic: "food" },
  { fa: "حُکْم", en: "ruling, sentence (of a court)", topic: "society" },
  { fa: "حامِله", en: "pregnant", topic: "body" },
  { fa: "شَبَکه", en: "network; (TV) channel", topic: "things" },
  { fa: "مَرْحَله", en: "stage, phase", topic: "ideas" },
  { fa: "پوشِش", en: "covering; clothing", topic: "things" },
  { fa: "مُتَفاوِت", en: "different", topic: "describing" },
  { fa: "دوسْتی", en: "friendship", topic: "people" },
  { fa: "کامیون", en: "lorry, truck", topic: "things" },
  { fa: "چینی", en: "Chinese; china (porcelain)", topic: "places" },
  { fa: "تَولید", en: "production", topic: "society" },
  { fa: "گیج", en: "confused, dizzy", topic: "feelings" },
  { fa: "کَفْش", en: "shoe", topic: "things" },
  { fa: "جُمْله", en: "sentence", topic: "learning" },
  { fa: "اِطِّلاع", en: "information, notice", topic: "learning" },
  { fa: "قاضی", en: "judge", topic: "society" },
  { fa: "هَمْسایه", en: "neighbour", topic: "people" },
  { fa: "پیشْرَفْت", en: "progress", topic: "ideas" },
  { fa: "مُشْتَری", en: "customer", topic: "society" },
  { fa: "خاطِره", en: "memory (of an event)", topic: "feelings" },
  { fa: "دیگَران", en: "others", topic: "grammar" },
  { fa: "مُتَّهَم", en: "accused", topic: "society" },
  { fa: "وَزیر", en: "minister", topic: "society" },
  { fa: "حادِثه", en: "accident, incident", topic: "society" },
  { fa: "جادوگَر", en: "witch, wizard", topic: "people" },
  { fa: "فَرانْسَوی", en: "French", topic: "places" },
  { fa: "وَصْل", en: "connected", topic: "describing" },
  { fa: "اِخْتیار", en: "authority; choice", topic: "ideas" },
  { fa: "قَلْعه", en: "castle, fort", topic: "places" },
  { fa: "فُروشْگاه", en: "store, shop", topic: "places" },
  { fa: "چاره", en: "remedy, way out", topic: "ideas" },
  { fa: "دِقَّت", en: "care, precision", topic: "ideas" },
  { fa: "لوله", en: "pipe, tube", topic: "things" },
  { fa: "عُمْر", en: "lifetime", topic: "time" },
  { fa: "پیروزی", en: "victory", topic: "society" },
  { fa: "وَحْشَت", en: "terror", topic: "feelings" },
  { fa: "گوشه", en: "corner", topic: "places" },
  { fa: "روبه‌رو", en: "opposite, facing", topic: "places" },
  { fa: "کارْتون", en: "cartoon; cardboard box", topic: "things" },
  { fa: "فَعّال", en: "active", topic: "describing" },
  { fa: "عُمومی", en: "public, general", topic: "society" },
  { fa: "مُوتُور", en: "engine; motorbike", topic: "things" },
  { fa: "مُصاحِبه", en: "interview", topic: "society" },
  { fa: "پُرُوژه", en: "project", topic: "society" },
  { fa: "دَهان", spoken: "دَهَن", en: "mouth", topic: "body" },
  { fa: "نَو", en: "new", topic: "describing" },
  { fa: "شَریک", en: "partner", topic: "people" },
  { fa: "دِراز", en: "long", topic: "describing" },
  { fa: "اَنْبار", en: "storeroom, warehouse", topic: "places" },
  { fa: "تَوافُق", en: "agreement", topic: "society" },
  { fa: "تَله", en: "trap", topic: "things" },
  { fa: "عَقْل", en: "reason, sense", topic: "ideas" },
  { fa: "صَنْدوق", en: "box, chest; till; fund", topic: "things" },
  { fa: "ضَبْط", en: "recording; (car) stereo", topic: "things" },
  { fa: "نِهایَت", en: "the end, the utmost", topic: "ideas" },
  { fa: "جادو", en: "magic", topic: "ideas" },
  { fa: "جُرْئَت", en: "courage, daring", topic: "feelings" },
  { fa: "جَرّاحی", en: "surgery", topic: "body" },
  { fa: "مَحَلّی", en: "local", topic: "describing" },
  { fa: "شُمالی", en: "northern", topic: "places" },
  { fa: "تاریک", en: "dark", topic: "describing" },
  { fa: "مَزْرَعه", en: "farm, field", topic: "places" },
  { fa: "عَمیق", en: "deep", topic: "describing" },
  { fa: "سابِقه", en: "record, background", topic: "society" },
  { fa: "طَرّاحی", en: "design", topic: "society" },
  { fa: "مُقاوِمَت", en: "resistance", topic: "society" },
  { fa: "قَبْلی", en: "previous", topic: "time" },
  { fa: "آزْمون", en: "exam, test", topic: "learning" },
  { fa: "سُخَنْرانی", en: "speech, lecture", topic: "learning" },
  { fa: "هَیولا", en: "monster", topic: "ideas" },
  { fa: "واضِح", en: "clear, obvious", topic: "describing" },
  { fa: "قَرْض", en: "loan, debt", topic: "society" },
  { fa: "جامِعه", en: "society", topic: "society" },
  { fa: "تَصْویر", en: "image, picture", topic: "things" },
  { fa: "آغاز", en: "beginning", topic: "time" },
  { fa: "سابِق", en: "former", topic: "time" },
  { fa: "پَرَسْتار", en: "nurse", topic: "people" },
  { fa: "پِلّه", en: "step, stair", topic: "home" },
  { fa: "قُرْص", en: "pill, tablet", topic: "body" },
  { fa: "ویروس", en: "virus", topic: "body" },
  { fa: "خُشْک", en: "dry", topic: "describing" },
  { fa: "کَف", en: "floor; palm (of the hand); foam", topic: "home" },
  { fa: "بُرْج", en: "tower", topic: "places" },
  { fa: "اِنْفِجار", en: "explosion", topic: "society" },
  { fa: "کَشْف", en: "discovery", topic: "learning" },
  { fa: "کیسه", en: "bag (plastic, paper)", topic: "things" },
  { fa: "رُشْد", en: "growth", topic: "ideas" },
  { fa: "مَحَلّه", en: "neighbourhood", topic: "places" },
  { fa: "پایْگاه", en: "base", topic: "places" },
  { fa: "شیرینی", en: "pastry, sweets", topic: "food" },
  { fa: "طوفان", en: "storm", topic: "weather" },
  { fa: "ظاهِر", en: "appearance", topic: "ideas" },
  { fa: "شِدَّت", en: "intensity", topic: "ideas" },
  { fa: "خُداحافِظی", en: "farewell, saying goodbye", topic: "everyday" },
  { fa: "فَراری", en: "fugitive, runaway", topic: "people" },
  { fa: "مادّه", en: "material, substance; (in a law) article", topic: "things" },
  { fa: "مانَنْدِ", en: "like (written)", topic: "grammar" },
  { fa: "اِنْتِقال", en: "transfer", topic: "society" },
  { fa: "اِنْسانی", en: "human (adj.)", topic: "describing" },
  { fa: "فَضایی", en: "space (adj.); alien (informal)", topic: "describing" },
  { fa: "رَنْج", en: "suffering", topic: "feelings" },
  { fa: "مُزاحِم", en: "nuisance; disturbing", topic: "describing" },
  { fa: "مُخْتَلِف", en: "various, different", topic: "describing" },
  { fa: "سِریال", en: "(TV) series", topic: "things" },
  { fa: "شِکایَت", en: "complaint", topic: "society" },
  { fa: "سَرَطان", en: "cancer", topic: "body" },
  { fa: "بَرْداشْت", en: "impression; harvest; withdrawal", topic: "ideas" },
  { fa: "دَبیرِسْتان", en: "secondary school", topic: "learning" },
  { fa: "نُسْخه", en: "copy; prescription", topic: "things" },
  { fa: "مُجازات", en: "punishment", topic: "society" },
  { fa: "جَذّاب", en: "attractive", topic: "describing" },
  { fa: "تَعْطیلات", en: "holidays", topic: "time" },
  { fa: "حَیْوان", spoken: "حَیْوون", en: "animal", topic: "animals" },
  { fa: "کُد", en: "code", topic: "things" },
  { fa: "حِفاظَت", en: "protection", topic: "society" },
  { fa: "روزه", en: "fasting", topic: "ideas" },
  { fa: "بَغَل", en: "side; a hug", topic: "body" },
  { fa: "خَر", en: "donkey", topic: "animals" },
  { fa: "گاو", en: "cow", topic: "animals" },
  { fa: "مُعْجِزه", en: "miracle", topic: "ideas" },
  { fa: "اَفْزایِش", en: "increase", topic: "numbers" },
  { fa: "عِدالَت", en: "justice", topic: "society" },
  { fa: "نَبَرْد", en: "battle", topic: "society" },
  { fa: "رودْخانه", spoken: "رودْخونه", en: "river", topic: "nature" },
  { fa: "هوش", en: "intelligence", topic: "ideas" },
  { fa: "اِجاره", en: "rent", topic: "home" },
  { fa: "اِمْتیاز", en: "point, score; privilege", topic: "numbers" },
  { fa: "تَهیّه", en: "preparation", topic: "everyday" },
  { fa: "زَمینه", en: "background; field", topic: "ideas" },
  { fa: "آفْتاب", en: "sunshine, the sun", topic: "weather" },
  { fa: "آلْمانی", en: "German", topic: "places" },
  { fa: "مَنْطِقی", en: "logical", topic: "describing" },
  { fa: "کامْپیوتِر", en: "computer", topic: "things" },
  { fa: "قِضاوَت", en: "judgement", topic: "ideas" },
  { fa: "قَرْن", en: "century", topic: "time" },
  { fa: "نَوار", en: "tape; strip", topic: "things" },
  { fa: "هَسْته", en: "core; seed, stone (of fruit); nuclear", topic: "things" },
  { fa: "مُتَعَلِّق", en: "belonging (to)", topic: "describing" },
  { fa: "رَهْبَر", en: "leader", topic: "society" },
  { fa: "جُنوبی", en: "southern", topic: "places" },
  { fa: "رَمْز", en: "code, password", topic: "things" },
  { fa: "خارِجی", en: "foreign; foreigner", topic: "places" },
  { fa: "داغ", en: "hot", topic: "describing" },
  { fa: "اَوَّلیّه", en: "initial, basic", topic: "describing" },
  { fa: "جُفْت", en: "pair; even (number)", topic: "numbers" },
  { fa: "هِدایَت", en: "guidance", topic: "ideas" },
  { fa: "آواز", en: "singing", topic: "everyday" },
  { fa: "هَمْکار", en: "colleague", topic: "society" },
  { fa: "مَرْز", en: "border", topic: "places" },
  { fa: "سِلول", en: "cell", topic: "things" },
  { fa: "مَنْبَع", en: "source", topic: "ideas" },
  { fa: "فَضا", en: "space; atmosphere", topic: "nature" },
  { fa: "خُوشْحالی", en: "happiness", topic: "feelings" },
  { fa: "بیمه", en: "insurance", topic: "society" },
  { fa: "تِجارَت", en: "trade, business", topic: "society" },
  { fa: "مُوافِق", en: "agreeing, in favour", topic: "feelings" },
  { fa: "دَنْدان", spoken: "دَنْدون", en: "tooth", topic: "body" },
  { fa: "تَرْسْناک", en: "scary", topic: "describing" },
  { fa: "فَریاد", en: "shout", topic: "everyday" },
  { fa: "حافِظه", en: "memory (the faculty)", topic: "ideas" },
  { fa: "سالُن", en: "hall", topic: "places" },
  { fa: "بُطْری", en: "bottle", topic: "things" },
  { fa: "اَخیراً", en: "recently", topic: "time" },
  { fa: "کانال", en: "channel", topic: "things" },
  { fa: "کاغَذ", en: "paper", topic: "things" },
  { fa: "هِنْد", en: "India", topic: "places" },
  { fa: "طَلاق", en: "divorce", topic: "people" },
  { fa: "اُقْیانوس", en: "ocean", topic: "nature" },
  { fa: "شَهْرْدار", en: "mayor", topic: "society" },
  { fa: "شَلْوار", en: "trousers", topic: "things" },
  { fa: "بال", en: "wing", topic: "animals" },
  { fa: "پایه", en: "base, leg (of furniture); school year", topic: "things" },
  { fa: "مَحْکوم", en: "condemned, sentenced", topic: "society" },
  { fa: "مَظْنون", en: "suspect", topic: "society" },
  { fa: "جیغ", en: "scream", topic: "everyday" },
  { fa: "شَرْقی", en: "eastern", topic: "places" },
  { fa: "داخِلی", en: "internal; domestic", topic: "describing" },
  { fa: "دَفْن", en: "burial", topic: "society" },
  { fa: "جِهَت", en: "direction", topic: "places" },
  { fa: "نابِغه", en: "genius", topic: "people" },
  { fa: "لَب", en: "lip", topic: "body" },
  { fa: "سَبْک", en: "style", topic: "ideas" },
  { fa: "خُشونَت", en: "violence", topic: "society" },
  { fa: "نِویسَنْده", en: "writer", topic: "people" },
  { fa: "مُقَصِّر", en: "to blame, at fault", topic: "describing" },
  { fa: "شِکارْچی", en: "hunter", topic: "people" },
  { fa: "عُذْرْخواهی", en: "apology", topic: "everyday" },
  { fa: "نَسْل", en: "generation", topic: "people" },
  { fa: "دَرْیاچه", en: "lake", topic: "nature" },
  { fa: "مِتْر", en: "metre", topic: "numbers" },
  { fa: "جُزْئیات", en: "details", topic: "ideas" },
  { fa: "تُنْد", en: "fast; spicy; sharp", topic: "describing" },
  { fa: "میمون", en: "monkey", topic: "animals" },
  { fa: "دَسْتی", en: "by hand, manual", topic: "describing" },
  { fa: "جِنْس", en: "material; gender", topic: "things" },
  { fa: "جُبْران", en: "making up for, compensation", topic: "ideas" },
  { fa: "عَرْض", en: "width", topic: "describing" },
];
