import type { CommonWord } from "./types";

export const BATCH_D1: CommonWord[] = [
  { fa: "مُحافِظ", en: "guard, bodyguard", topic: "people" },
  { fa: "اِسْتِعْداد", en: "talent", topic: "ideas" },
  { fa: "خِرْس", en: "bear", topic: "animals" },
  { fa: "زانو", en: "knee", topic: "body" },
  { fa: "نَمایَنْده", en: "representative", topic: "society" },
  { fa: "صورَتی", en: "pink", topic: "colours" },
  { fa: "مُرَبّی", en: "coach, trainer", topic: "people" },
  { fa: "مِهْرَبان", spoken: "مِهْرَبون", en: "kind", topic: "describing" },
  { fa: "دُکْمه", en: "button", topic: "things" },
  { fa: "عِلاوه بَر", en: "in addition to", topic: "grammar" },
  { fa: "طَرْح", en: "design, plan", topic: "ideas" },
  { fa: "وُرودی", en: "entrance; entrance fee", topic: "places" },
  { fa: "غَرْبی", en: "western", topic: "places" },
  { fa: "واکُنِش", en: "reaction", topic: "ideas" },
  { fa: "هُویَّت", en: "identity", topic: "ideas" },
  { fa: "نیرو", en: "force, strength", topic: "ideas" },
  { fa: "تَوهین", en: "insult", topic: "ideas" },
  { fa: "سَنْگین", en: "heavy", topic: "describing" },
  { fa: "شَرْق", en: "east", topic: "places" },
  { fa: "بَلا", en: "disaster, trouble", topic: "ideas" },
  { fa: "گول زَدَن", en: "to fool, to trick", topic: "verbs" },
  { fa: "گور", en: "grave", topic: "places" },
  { fa: "دَهه", en: "decade", topic: "time" },
  { fa: "[جُسْت‌وجو|jostoju]", en: "search", topic: "everyday" },
  { fa: "عَروس", en: "bride; daughter-in-law", topic: "people" },
  { fa: "اَکْنون", en: "now (written)", topic: "time" },
  { fa: "اِضْطِراری", en: "emergency", topic: "describing" },
  { fa: "شُجاع", en: "brave", topic: "describing" },
  { fa: "آلوده", en: "polluted", topic: "describing" },
  { fa: "شاد", en: "happy, cheerful", topic: "feelings" },
  { fa: "سوخْت", en: "fuel", topic: "things" },
  { fa: "مُرَتَّب", en: "tidy; regularly", topic: "describing" },
  { fa: "حُکومَت", en: "government, rule", topic: "society" },
  { fa: "نِفْرین", en: "curse", topic: "ideas" },
  { fa: "مُتَوَلِّد", en: "born", topic: "people" },
  { fa: "شَهْری", en: "urban, of the city", topic: "places" },
  { fa: "مَوج", en: "wave", topic: "nature" },
  { fa: "مُسَلَّح", en: "armed", topic: "society" },
  { fa: "مَحْرَمانه", en: "confidential", topic: "describing" },
  { fa: "مُتَخَصِّص", en: "specialist", topic: "people" },
  { fa: "تَوصیه", en: "recommendation", topic: "ideas" },
  { fa: "کُپی", en: "copy", topic: "things" },
  { fa: "مُتَرْجِم", en: "translator", topic: "people" },
  { fa: "هُنَر", en: "art", topic: "learning" },
  { fa: "اینْتِرْنِت", en: "internet", topic: "things" },
  { fa: "صاف", en: "smooth; straight; clear", topic: "describing" },
  { fa: "سیاسَت", en: "politics; policy", topic: "society" },
  { fa: "اِصْرار", en: "insistence", topic: "ideas" },
  { fa: "مَرْکَزی", en: "central", topic: "places" },
  { fa: "مَجَلّه", en: "magazine", topic: "things" },
  { fa: "اِجْتِماعی", en: "social", topic: "society" },
  { fa: "خُوشی", en: "pleasure, good times", topic: "feelings" },
  { fa: "اِلْتِماس", en: "pleading", topic: "feelings" },
  { fa: "پاسُخ", en: "answer (written)", topic: "learning" },
  { fa: "جِنایَت", en: "crime", topic: "society" },
  { fa: "شَهادَت", en: "testimony; martyrdom", topic: "society" },
  { fa: "[ناامید|nâomid]", en: "disappointed, hopeless", topic: "feelings" },
  { fa: "رَدیف", en: "row", topic: "things" },
  { fa: "گُزینه", en: "option", topic: "ideas" },
  { fa: "تَصادُفی", en: "random, by chance", topic: "describing" },
  { fa: "غول", en: "giant", topic: "people" },
  { fa: "سِکّه", en: "coin", topic: "things" },
  { fa: "عَمّه", en: "aunt (father's sister)", topic: "people" },
  { fa: "مَقاله", en: "article (in the press)", topic: "learning" },
  { fa: "دَخالَت", en: "interference", topic: "ideas" },
  { fa: "جِلُوگیری", en: "prevention", topic: "ideas" },
  { fa: "مُطالِعه", en: "study, reading", topic: "learning" },
  { fa: "پَرْده", en: "curtain", topic: "home" },
  { fa: "نیز", en: "also (written)", topic: "grammar" },
  { fa: "ماهْواره", en: "satellite", topic: "things" },
  { fa: "شُکُلات", en: "chocolate", topic: "food" },
  { fa: "بازیگَر", en: "actor", topic: "people" },
  { fa: "مار", en: "snake", topic: "animals" },
  { fa: "طَناب", en: "rope", topic: "things" },
  { fa: "جُمْهوری", en: "republic", topic: "society" },
  { fa: "پیرْمَرْد", en: "old man", topic: "people" },
  { fa: "پولْدار", en: "rich", topic: "describing" },
  { fa: "نامْزَد", en: "fiancé, fiancée; candidate", topic: "people" },
  { fa: "رُؤْیا", en: "dream (a hope); vision", topic: "ideas" },
  { fa: "چاق", en: "fat", topic: "describing" },
  { fa: "چَهارُم", en: "fourth", topic: "numbers" },
  { fa: "قادِر", en: "able", topic: "describing" },
  { fa: "مُعاوِن", en: "deputy", topic: "society" },
  { fa: "جَمْعیَّت", en: "population; crowd", topic: "society" },
  { fa: "طَلایی", en: "golden", topic: "colours" },
  { fa: "مُشْتَرَک", en: "shared, joint", topic: "describing" },
  { fa: "گُروگان", en: "hostage", topic: "society" },
  { fa: "تَپّه", en: "hill", topic: "nature" },
  { fa: "سِرْقَت", en: "robbery", topic: "society" },
  { fa: "مَهارَت", en: "skill", topic: "ideas" },
  { fa: "جاسوس", en: "spy", topic: "people" },
  { fa: "نَظَریّه", en: "theory", topic: "learning" },
  { fa: "فَریب", en: "deception", topic: "ideas" },
  { fa: "راهْنَمایی", en: "guidance; directions", topic: "everyday" },
  { fa: "سایْت", en: "website", topic: "things" },
  { fa: "کِرْم", en: "worm; cream (for the skin)", topic: "things" },
  { fa: "مُذاکِره", en: "negotiation", topic: "society" },
  { fa: "صَحیح", en: "correct", topic: "describing" },
  { fa: "مِلَّت", en: "nation", topic: "society" },
  { fa: "ماسْک", en: "mask", topic: "things" },
  { fa: "بَدْبَخْت", en: "miserable, unlucky", topic: "feelings" },
  { fa: "کور", en: "blind", topic: "describing" },
  { fa: "سَقْف", en: "ceiling; roof", topic: "home" },
  { fa: "[رادیو|râdiyo]", en: "radio", topic: "things" },
  { fa: "فَعّالیَّت", en: "activity", topic: "everyday" },
  { fa: "چَرْخ", en: "wheel", topic: "things" },
  { fa: "لَمْس", en: "touch", topic: "everyday" },
  { fa: "دَرّه", en: "valley", topic: "nature" },
  { fa: "زِشْت", en: "ugly", topic: "describing" },
  { fa: "آهَن", en: "iron", topic: "things" },
  { fa: "وَزْن", en: "weight", topic: "describing" },
  { fa: "طَبیعَت", en: "nature", topic: "nature" },
  { fa: "مَجْلِس", en: "parliament", topic: "society" },
  { fa: "فَرْمان", en: "command; steering wheel", topic: "society" },
  { fa: "مُتَّحِد", en: "united", topic: "society" },
  { fa: "روسیه", en: "Russia", topic: "places" },
  { fa: "مُشاوِر", en: "adviser", topic: "people" },
  { fa: "تونِل", en: "tunnel", topic: "places" },
  { fa: "تَضْمین", en: "guarantee", topic: "ideas" },
  { fa: "دود", en: "smoke", topic: "nature" },
  { fa: "باشْگاه", en: "club; gym", topic: "places" },
  { fa: "صَف", en: "queue, line", topic: "everyday" },
  { fa: "بازَنْده", en: "loser", topic: "people" },
  { fa: "اِحْتیاط", en: "caution", topic: "ideas" },
  { fa: "سود", en: "profit", topic: "society" },
  { fa: "بَسْتَنی", en: "ice cream", topic: "food" },
  { fa: "نُقْره", en: "silver", topic: "things" },
  { fa: "اِمْسال", en: "this year", topic: "time" },
  { fa: "تِکْنُولُوژی", en: "technology", topic: "things" },
  { fa: "مَنْفی", en: "negative", topic: "describing" },
  { fa: "کارْخانه", spoken: "کارْخونه", en: "factory", topic: "places" },
  { fa: "خَشْم", en: "anger", topic: "feelings" },
  { fa: "چِگونه", en: "how (written)", topic: "grammar" },
  { fa: "سیاسی", en: "political", topic: "society" },
  { fa: "اِنْگِلِسْتان", en: "England", topic: "places" },
  { fa: "ایمِیْل", en: "email", topic: "things" },
  { fa: "سُکوت", en: "silence", topic: "everyday" },
  { fa: "خَلَبان", en: "pilot", topic: "people" },
  { fa: "کیلومِتْر", en: "kilometre", topic: "numbers" },
  { fa: "مُرَخَّصی", en: "leave (time off work)", topic: "society" },
  { fa: "عَذاب", en: "torment", topic: "feelings" },
  { fa: "خیس", en: "wet", topic: "describing" },
  { fa: "یادْداشْت", en: "note", topic: "learning" },
  { fa: "نِگَهْداری", en: "keeping, looking after", topic: "everyday" },
  { fa: "نِفْرَت", en: "hatred", topic: "feelings" },
  { fa: "خِدْمَتْکار", en: "servant", topic: "people" },
  { fa: "مَقام", en: "position, rank; official", topic: "society" },
  { fa: "مُحاکِمه", en: "trial", topic: "society" },
  { fa: "سَلامَت", en: "health", topic: "body" },
  { fa: "عَروسَک", en: "doll", topic: "things" },
  { fa: "آزار", en: "harassment, harm", topic: "ideas" },
  { fa: "مَشْهور", en: "famous", topic: "describing" },
  { fa: "سانْدْویچ", en: "sandwich", topic: "food" },
  { fa: "اِثْبات", en: "proof", topic: "ideas" },
  { fa: "دوچَرْخه", en: "bicycle", topic: "things" },
  { fa: "آمْبولانْس", en: "ambulance", topic: "things" },
  { fa: "جیب", en: "pocket", topic: "things" },
  { fa: "اِدِّعا", en: "claim", topic: "ideas" },
  { fa: "ضَعْف", en: "weakness", topic: "ideas" },
  { fa: "رَقابَت", en: "competition, rivalry", topic: "society" },
  { fa: "مانِع", en: "obstacle", topic: "ideas" },
  { fa: "اِخْطار", en: "warning", topic: "society" },
  { fa: "مُجَوِّز", en: "permit, licence", topic: "society" },
  { fa: "بوسه", spoken: "بوس", en: "kiss", topic: "feelings" },
  { fa: "پَناه", en: "refuge, shelter", topic: "places" },
  { fa: "قُدْرَتْمَنْد", en: "powerful", topic: "describing" },
  { fa: "مُجْرِم", en: "criminal", topic: "people" },
  { fa: "حَوصِله", en: "patience; being in the mood", topic: "feelings" },
  { fa: "اِصْلاح", en: "correction; (a) haircut, shave", topic: "everyday" },
  { fa: "عِلْمی", en: "scientific", topic: "learning" },
  { fa: "بَرْگه", en: "sheet (of paper), form", topic: "things" },
  { fa: "دَسْتْیار", en: "assistant", topic: "people" },
  { fa: "اُروپا", en: "Europe", topic: "places" },
  { fa: "خانِوادِگی", en: "family (adj.)", topic: "people" },
  { fa: "پِزِشْک", en: "physician, doctor", topic: "people" },
  { fa: "تَخْته", en: "board, plank; blackboard", topic: "things" },
  { fa: "خَطا", en: "error; foul", topic: "ideas" },
  { fa: "ژاپُنی", en: "Japanese", topic: "places" },
  { fa: "لیاقَت", en: "merit, worthiness", topic: "ideas" },
  { fa: "عاشِقانه", en: "romantic", topic: "feelings" },
  { fa: "کابوس", en: "nightmare", topic: "feelings" },
  { fa: "ذَخیره", en: "storage, saving", topic: "things" },
  { fa: "بَرْعَکْس", en: "on the contrary; the other way round", topic: "grammar" },
  { fa: "بِنْزین", en: "petrol", topic: "things" },
  { fa: "صادِق", en: "honest", topic: "describing" },
  { fa: "تَعْمیر", en: "repair", topic: "everyday" },
  { fa: "اَلْماس", en: "diamond", topic: "things" },
  { fa: "اَساسی", en: "basic, fundamental", topic: "describing" },
  { fa: "خوانَنْده", en: "singer; reader", topic: "people" },
  { fa: "[توالِت|tuvâlet]", en: "toilet", topic: "home" },
  { fa: "مُحیط", en: "environment; surroundings", topic: "nature" },
  { fa: "زَوج", en: "couple; even (number)", topic: "people" },
  { fa: "طَرَفْدار", en: "fan, supporter", topic: "people" },
  { fa: "بازْگَشْت", en: "return", topic: "everyday" },
  { fa: "خُروجی", en: "way out; output", topic: "places" },
  { fa: "تَفاوُت", en: "difference", topic: "ideas" },
  { fa: "بازیکُن", en: "player", topic: "people" },
  { fa: "دیدار", en: "meeting, visit", topic: "people" },
  { fa: "مَجّانی", en: "free (of charge)", topic: "describing" },
  { fa: "جایْگُزین", en: "replacement", topic: "ideas" },
  { fa: "غُروب", en: "sunset", topic: "time" },
  { fa: "والِدَین", en: "parents", topic: "people" },
  { fa: "وَفاداری", en: "loyalty", topic: "feelings" },
  { fa: "مُثْبَت", en: "positive", topic: "describing" },
  { fa: "خَدَمات", en: "services", topic: "society" },
  { fa: "شَرْم", en: "shame", topic: "feelings" },
  { fa: "مالیات", en: "tax", topic: "society" },
  { fa: "نَمَک", en: "salt", topic: "food" },
  { fa: "سَرْگَرْمی", en: "hobby, pastime", topic: "everyday" },
  { fa: "غَلَط", en: "wrong; a mistake", topic: "describing" },
  { fa: "کاهِش", en: "decrease", topic: "numbers" },
  { fa: "اَلْکُل", en: "alcohol", topic: "things" },
  { fa: "مَذْهَبی", en: "religious", topic: "society" },
  { fa: "فَرْزَنْد", en: "child (son or daughter)", topic: "people" },
  { fa: "زیرْزَمین", en: "basement", topic: "home" },
  { fa: "فاجِعه", en: "disaster", topic: "society" },
  { fa: "بازْرِسی", en: "inspection", topic: "society" },
  { fa: "مُحاصِره", en: "siege", topic: "society" },
  { fa: "مُدیریَّت", en: "management", topic: "society" },
  { fa: "آشْنایی", en: "acquaintance, getting to know", topic: "people" },
  { fa: "خائِن", en: "traitor", topic: "people" },
  { fa: "عَرَق", en: "sweat; arak (a spirit)", topic: "body" },
  { fa: "مَطْلَب", en: "matter; content", topic: "ideas" },
  { fa: "رَسانه", en: "medium; (plural) the media", topic: "society" },
  { fa: "آسانْسُور", en: "lift, elevator", topic: "home" },
  { fa: "حَذْف", en: "removal", topic: "ideas" },
  { fa: "اِلْهام", en: "inspiration", topic: "ideas" },
  { fa: "اُسْتُخوان", spoken: "اُسْتُخون", en: "bone", topic: "body" },
  { fa: "خُلاصه", en: "summary; in short", topic: "learning" },
  { fa: "قَد", en: "height (of a person)", topic: "body" },
  { fa: "مُنْتَشِر", en: "published; spread", topic: "describing" },
  { fa: "مُجَسَّمه", en: "statue", topic: "things" },
  { fa: "شِکَم", en: "belly, stomach", topic: "body" },
  { fa: "دُرود", en: "greetings (formal)", topic: "everyday" },
  { fa: "چاپ", en: "printing, print", topic: "things" },
  { fa: "اِطاعَت", en: "obedience", topic: "ideas" },
  { fa: "عَیب", en: "fault, defect", topic: "ideas" },
  { fa: "شُجاعَت", en: "courage", topic: "ideas" },
  { fa: "نَوِه", en: "grandchild", topic: "people" },
  { fa: "تَحْسین", en: "admiration", topic: "feelings" },
  { fa: "اُکْسیژِن", en: "oxygen", topic: "nature" },
  { fa: "مُقایِسه", en: "comparison", topic: "ideas" },
  { fa: "اِضافی", en: "extra, spare", topic: "describing" },
  { fa: "تَرْکیب", en: "combination", topic: "ideas" },
  { fa: "خُوشْبَخْتَم", en: "pleased to meet you", topic: "everyday" },
  { fa: "دایِره", en: "circle", topic: "things" },
  { fa: "نَقْص", en: "defect, flaw", topic: "ideas" },
  { fa: "خَرْگوش", en: "rabbit", topic: "animals" },
  { fa: "اِسْتِرِس", en: "stress", topic: "feelings" },
  { fa: "رِشْته", en: "field (of study); string, thread", topic: "learning" },
  { fa: "شایِعه", en: "rumour", topic: "ideas" },
  { fa: "اَگَرْچه", en: "although", topic: "grammar" },
  { fa: "خالْکوبی", en: "tattoo", topic: "things" },
  { fa: "رَبْط", en: "connection, relevance", topic: "ideas" },
  { fa: "دَرْگیری", en: "conflict, clash", topic: "society" },
  { fa: "طُلوع", en: "sunrise", topic: "time" },
  { fa: "اِنْتِخابات", en: "election", topic: "society" },
  { fa: "سَهْم", en: "share", topic: "society" },
  { fa: "مَشْکوک", en: "suspicious", topic: "describing" },
  { fa: "اِرْتِفاع", en: "height, altitude", topic: "describing" },
  { fa: "ریه", en: "lung", topic: "body" },
  { fa: "تَرْسو", en: "coward; cowardly", topic: "describing" },
  { fa: "بَدْبَخْتی", en: "misery", topic: "feelings" },
  { fa: "دَولَتی", en: "state-run, governmental", topic: "society" },
  { fa: "بیهوش", en: "unconscious", topic: "body" },
  { fa: "فاسِد", en: "corrupt; rotten", topic: "describing" },
  { fa: "مُسافِرَت", en: "travel, a trip", topic: "everyday" },
  { fa: "مَجْموعه", en: "collection, set", topic: "things" },
  { fa: "شَبانه", en: "nightly, at night", topic: "time" },
  { fa: "بَشَر", en: "humankind", topic: "people" },
  { fa: "نِظارَت", en: "supervision", topic: "society" },
  { fa: "فَوری", en: "urgent", topic: "describing" },
  { fa: "مَعْدَن", en: "mine", topic: "places" },
  { fa: "رَوابِط", en: "relations", topic: "society" },
  { fa: "تَشْویق", en: "encouragement", topic: "ideas" },
  { fa: "خَنْجَر", en: "dagger", topic: "things" },
  { fa: "دُروغْگو", en: "liar", topic: "people" },
  { fa: "گِرْد", en: "round", topic: "describing" },
];
