import type { CommonWord } from "./types";

export const BATCH_D2: CommonWord[] = [
  { fa: "پَیمان", en: "pact", topic: "society" },
  { fa: "قَبْر", en: "grave", topic: "places" },
  { fa: "بی‌گُناه", en: "innocent", topic: "describing" },
  { fa: "اِسْپانیایی", en: "Spanish", topic: "places" },
  { fa: "میزان", en: "level, amount", topic: "numbers" },
  { fa: "مُدام", en: "constantly", topic: "time" },
  { fa: "مُخالِف", en: "opposed, against", topic: "ideas" },
  { fa: "مِهْ", en: "fog", topic: "weather" },
  { fa: "هِلیکُوپْتِر", en: "helicopter", topic: "things" },
  { fa: "راهْرُو", en: "corridor", topic: "home" },
  { fa: "سِپَس", en: "then, afterwards (written)", topic: "time" },
  { fa: "اَشْک", en: "tear (from the eye)", topic: "body" },
  { fa: "تَنْبیهْ", en: "punishment", topic: "ideas" },
  { fa: "تَجْهیزات", en: "equipment", topic: "things" },
  { fa: "رُوشَنایی", en: "light, brightness", topic: "nature" },
  { fa: "کافه", en: "café", topic: "places" },
  { fa: "سِفْت", en: "hard, tight", topic: "describing" },
  { fa: "پَیْوَنْد", en: "link, bond; transplant, graft", topic: "ideas" },
  { fa: "بَرْخی", en: "some (written)", topic: "grammar" },
  { fa: "روحی", en: "mental, emotional", topic: "describing" },
  { fa: "اَعْصاب", en: "nerves", topic: "body" },
  { fa: "سادِگی", en: "simplicity", topic: "ideas" },
  { fa: "رَسْم", en: "custom; drawing", topic: "ideas" },
  { fa: "اِعْتِراض", en: "protest, objection", topic: "society" },
  { fa: "وِزارَت", en: "ministry", topic: "society" },
  { fa: "پَرْچَم", en: "flag", topic: "things" },
  { fa: "بَرْگ", en: "leaf; sheet", topic: "nature" },
  { fa: "اِقْدام", en: "action, measure", topic: "society" },
  { fa: "اِنْکار", en: "denial", topic: "ideas" },
  { fa: "گُناهْکار", en: "sinner; guilty", topic: "people" },
  { fa: "فَنّی", en: "technical", topic: "describing" },
  { fa: "دانِشْکَده", en: "faculty (of a university)", topic: "learning" },
  { fa: "رِشْوه", en: "bribe", topic: "society" },
  { fa: "ایتالیایی", en: "Italian", topic: "places" },
  { fa: "فُرْم", en: "form (to fill in); shape", topic: "things" },
  { fa: "عُفونَت", en: "infection", topic: "body" },
  { fa: "هَماهَنْگ", en: "coordinated", topic: "describing" },
  { fa: "نَصیحَت", en: "advice", topic: "ideas" },
  { fa: "بیگانه", en: "foreign, alien", topic: "people" },
  { fa: "قَدیم", en: "old times, the past", topic: "time" },
  { fa: "مُفید", en: "useful", topic: "describing" },
  { fa: "حِزْب", en: "(political) party", topic: "society" },
  { fa: "شُوک", en: "shock", topic: "feelings" },
  { fa: "موزه", en: "museum", topic: "places" },
  { fa: "قَفَسه", en: "shelf", topic: "home" },
  { fa: "تَب", en: "fever", topic: "body" },
  { fa: "وَفادار", en: "loyal", topic: "describing" },
  { fa: "لَغْو", en: "cancellation", topic: "society" },
  { fa: "مَصْنوعی", en: "artificial", topic: "describing" },
  { fa: "وابَسْته", en: "dependent; attaché", topic: "describing" },
  { fa: "کُنْفِرانْس", en: "conference", topic: "society" },
  { fa: "گِره", en: "knot", topic: "things" },
  { fa: "هِنْگام", en: "time, moment; (هِنْگامِ …) at the time of (written)", topic: "time" },
  { fa: "ساک", en: "holdall, bag", topic: "things" },
  { fa: "مُنْشی", en: "secretary", topic: "people" },
  { fa: "فایْل", en: "file", topic: "things" },
  { fa: "عامِل", en: "factor; agent", topic: "ideas" },
  { fa: "ریشه", en: "root", topic: "nature" },
  { fa: "داوْطَلَب", en: "volunteer", topic: "people" },
  { fa: "عِلَّت", en: "cause", topic: "ideas" },
  { fa: "فیزیکی", en: "physical", topic: "describing" },
  { fa: "ضَرَبان", en: "beat (of the heart)", topic: "body" },
  { fa: "دَنْده", en: "rib; gear", topic: "things" },
  { fa: "اِعْتِبار", en: "credit; validity", topic: "society" },
  { fa: "ناحیه", en: "area, region", topic: "places" },
  { fa: "لَگَد", en: "kick", topic: "everyday" },
  { fa: "کُلْیه", en: "kidney", topic: "body" },
  { fa: "کوهِسْتان", en: "mountains, mountain region", topic: "nature" },
  { fa: "شایِسْته", en: "worthy", topic: "describing" },
  { fa: "رُوغَن", en: "oil (for cooking)", topic: "food" },
  { fa: "سَرْما", en: "cold, the cold (weather)", topic: "weather" },
  { fa: "هَمیشِگی", en: "usual, constant, lasting", topic: "describing" },
  { fa: "رِزِرْو", en: "reservation", topic: "everyday" },
  { fa: "اِخْتِراع", en: "invention", topic: "ideas" },
  { fa: "نُمْره", en: "mark, grade; size (of shoes)", topic: "learning" },
  { fa: "رَگ", en: "vein", topic: "body" },
  { fa: "دارایی", en: "assets, property", topic: "society" },
  { fa: "سُس", en: "sauce", topic: "food" },
  { fa: "یَواش", en: "slowly; quietly", topic: "describing" },
  { fa: "عَقیده", en: "opinion, belief", topic: "ideas" },
  { fa: "قَفَس", en: "cage", topic: "things" },
  { fa: "شُعْله", en: "flame", topic: "nature" },
  { fa: "ناگَهانی", en: "sudden", topic: "describing" },
  { fa: "ناشِناس", en: "unknown, anonymous", topic: "describing" },
  { fa: "مُعْتاد", en: "addict; addicted", topic: "people" },
  { fa: "سَکْته", en: "stroke; heart attack", topic: "body" },
  { fa: "پارْکینْگ", en: "car park", topic: "places" },
  { fa: "اَکْثَر", en: "most", topic: "grammar" },
  { fa: "هَمْزَمان", en: "simultaneous", topic: "time" },
  { fa: "صَخْره", en: "rock, cliff", topic: "nature" },
  { fa: "گُرُسْنِگی", en: "hunger", topic: "body" },
  { fa: "بَهانه", en: "excuse", topic: "ideas" },
  { fa: "اَبْزار", en: "tool", topic: "things" },
  { fa: "خُوشْبَخْتانه", en: "fortunately", topic: "grammar" },
  { fa: "کُمُد", en: "wardrobe, cupboard", topic: "home" },
  { fa: "سَطْل", en: "bucket; bin", topic: "home" },
  { fa: "قَبیله", en: "tribe", topic: "people" },
  { fa: "مَحْبوب", en: "popular; beloved", topic: "describing" },
  { fa: "نَخَیر", en: "no (emphatic)", topic: "everyday" },
  { fa: "اَسیر", en: "captive", topic: "people" },
  { fa: "شیمیایی", en: "chemical", topic: "describing" },
  { fa: "گیاه", en: "plant", topic: "nature" },
  { fa: "اِتِّهام", en: "accusation", topic: "society" },
  { fa: "سُتون", en: "column", topic: "things" },
  { fa: "نِژاد", en: "race (of people)", topic: "people" },
  { fa: "کارْمَنْد", en: "employee", topic: "people" },
  { fa: "دوسْتانه", en: "friendly", topic: "describing" },
  { fa: "کاسه", en: "bowl", topic: "home" },
  { fa: "کوسه", en: "shark", topic: "animals" },
  { fa: "دَسْتْمال", en: "handkerchief, tissue; cloth", topic: "things" },
  { fa: "وَعْده", en: "promise; a meal", topic: "ideas" },
  { fa: "وام", en: "loan", topic: "society" },
  { fa: "اَغْلَب", en: "often; most", topic: "time" },
  { fa: "لَبه", en: "edge", topic: "places" },
  { fa: "تَفْریح", en: "recreation, fun", topic: "everyday" },
  { fa: "کُلْبه", en: "hut, cottage", topic: "home" },
  { fa: "خُوشْبَخْت", en: "happy, fortunate", topic: "feelings" },
  { fa: "نَظْم", en: "order, discipline", topic: "ideas" },
  { fa: "چَکُش", en: "hammer", topic: "things" },
  { fa: "ضَروری", en: "necessary", topic: "describing" },
  { fa: "ایمِنی", en: "safety", topic: "society" },
  { fa: "آشْکار", en: "obvious, apparent", topic: "describing" },
  { fa: "رَوَنْد", en: "process, trend", topic: "ideas" },
  { fa: "پاداش", en: "reward", topic: "ideas" },
  { fa: "پَرْوانه", en: "butterfly; licence", topic: "animals" },
  { fa: "زَنْجیر", en: "chain", topic: "things" },
  { fa: "ریش", en: "beard", topic: "body" },
  { fa: "مَعْمول", en: "usual", topic: "describing" },
  { fa: "بُحْران", en: "crisis", topic: "society" },
  { fa: "کِتابْخانه", spoken: "کِتابْخونه", en: "library", topic: "places" },
  { fa: "فُروشَنْده", en: "seller, shop assistant", topic: "people" },
  { fa: "مُکالِمه", en: "conversation", topic: "learning" },
  { fa: "عَظیم", en: "huge", topic: "describing" },
  { fa: "ماهیگیری", en: "fishing", topic: "everyday" },
  { fa: "غار", en: "cave", topic: "nature" },
  { fa: "لَکّه", en: "stain, spot", topic: "things" },
  { fa: "نُوک", en: "tip, point; beak", topic: "things" },
  { fa: "آشْپَز", en: "cook, chef", topic: "people" },
  { fa: "تِرافیک", en: "traffic", topic: "everyday" },
  { fa: "فِنْجان", spoken: "فِنْجون", en: "cup", topic: "home" },
  { fa: "کُهْنه", en: "old, worn", topic: "describing" },
  { fa: "بودْجه", en: "budget", topic: "society" },
  { fa: "گَرْدِش", en: "outing, walk; circulation", topic: "everyday" },
  { fa: "یَتیم", en: "orphan", topic: "people" },
  { fa: "مُؤَسِّسه", en: "institute", topic: "society" },
  { fa: "پَنْجه", en: "paw; fingers (of the hand); toes", topic: "body" },
  { fa: "رِضایَت", en: "satisfaction; consent", topic: "feelings" },
  { fa: "قاچاق", en: "smuggling", topic: "society" },
  { fa: "مِدال", en: "medal", topic: "things" },
  { fa: "نَفْت", en: "oil (petroleum)", topic: "things" },
  { fa: "اَدَب", en: "politeness, manners", topic: "ideas" },
  { fa: "دایی", en: "uncle (mother's brother)", topic: "people" },
  { fa: "تابْلُو", en: "sign; painting", topic: "things" },
  { fa: "دَرْآمَد", en: "income", topic: "society" },
  { fa: "خَیریه", en: "charity", topic: "society" },
  { fa: "اِفْتِضاح", en: "awful; a disgrace", topic: "describing" },
  { fa: "گَنْج", en: "treasure", topic: "things" },
  { fa: "مُحْتَرَم", en: "respected, respectable", topic: "describing" },
  { fa: "دَسْتْبَنْد", en: "bracelet; handcuffs", topic: "things" },
  { fa: "حَسّاس", en: "sensitive", topic: "describing" },
  { fa: "نَصْب", en: "installation", topic: "everyday" },
  { fa: "گِرِفْتار", en: "caught up, busy; in trouble", topic: "describing" },
  { fa: "مُهْر", en: "stamp, seal; prayer stone", topic: "things" },
  { fa: "اِتِّحاد", en: "union, unity", topic: "society" },
  { fa: "حَشَره", en: "insect", topic: "animals" },
  { fa: "شَهْرْوَنْد", en: "citizen", topic: "people" },
  { fa: "اِراده", en: "will, willpower", topic: "ideas" },
  { fa: "شاخ", en: "horn", topic: "animals" },
  { fa: "مُشْتاق", en: "eager", topic: "feelings" },
  { fa: "جِگَر", en: "liver", topic: "body" },
  { fa: "نَخ", en: "thread", topic: "things" },
  { fa: "اَوْلَویَّت", en: "priority", topic: "ideas" },
  { fa: "بِهْبود", en: "improvement, recovery", topic: "ideas" },
  { fa: "خُنَک", en: "cool", topic: "weather" },
  { fa: "آرایِش", en: "make-up", topic: "things" },
  { fa: "تِئاتْر", en: "theatre", topic: "places" },
  { fa: "میلیارْد", en: "billion", topic: "numbers" },
  { fa: "حَقیقی", en: "real, true", topic: "describing" },
  { fa: "مایِع", en: "liquid", topic: "things" },
  { fa: "مَحْصول", en: "product; crop", topic: "society" },
  { fa: "سوزَن", en: "needle", topic: "things" },
  { fa: "شیوه", en: "method, way", topic: "ideas" },
  { fa: "شُهْرَت", en: "fame", topic: "ideas" },
  { fa: "غُرور", en: "pride", topic: "feelings" },
  { fa: "دانِشْمَنْد", en: "scientist", topic: "people" },
  { fa: "یَخْچال", en: "fridge", topic: "home" },
  { fa: "قَطْره", en: "drop", topic: "things" },
  { fa: "اِنْقِلاب", en: "revolution", topic: "society" },
  { fa: "کارْگَر", en: "worker", topic: "people" },
  { fa: "خُوشْبَخْتی", en: "happiness, good fortune", topic: "feelings" },
  { fa: "بازْنِشَسْته", en: "retired", topic: "people" },
  { fa: "شاخه", en: "branch", topic: "nature" },
  { fa: "تیز", en: "sharp", topic: "describing" },
  { fa: "تُوسِعه", en: "development", topic: "society" },
  { fa: "اِرْث", en: "inheritance", topic: "society" },
  { fa: "سَفیر", en: "ambassador", topic: "society" },
  { fa: "خونْسَرْد", en: "calm, cool-headed", topic: "describing" },
  { fa: "مَتْن", en: "text", topic: "learning" },
  { fa: "مُشابِهْ", en: "similar", topic: "describing" },
  { fa: "لایه", en: "layer", topic: "things" },
  { fa: "تِشْنه", en: "thirsty", topic: "feelings" },
  { fa: "اِقامَت", en: "residence, stay", topic: "society" },
  { fa: "پَذیرایی", en: "hospitality; living room", topic: "home" },
  { fa: "وَرْزِشی", en: "sports (adj.)", topic: "everyday" },
  { fa: "سوت", en: "whistle", topic: "things" },
  { fa: "اِسْپانیا", en: "Spain", topic: "places" },
  { fa: "قَلَم", en: "pen", topic: "things" },
  { fa: "اِقْتِصادی", en: "economic", topic: "society" },
  { fa: "ایتالیا", en: "Italy", topic: "places" },
  { fa: "جِسْم", en: "body (physical)", topic: "body" },
  { fa: "تاریخی", en: "historical", topic: "learning" },
  { fa: "فَرْهَنْگ", en: "culture; dictionary", topic: "learning" },
  { fa: "سُنَّتی", en: "traditional", topic: "describing" },
  { fa: "بَهار", en: "spring (the season)", topic: "time" },
  { fa: "حوله", en: "towel", topic: "home" },
  { fa: "چادُر", en: "chador; tent", topic: "things" },
  { fa: "پارْچه", en: "fabric, cloth", topic: "things" },
  { fa: "غَمْگین", en: "sad", topic: "feelings" },
  { fa: "فیزیک", en: "physics", topic: "learning" },
  { fa: "خاکِسْتَری", en: "grey", topic: "colours" },
  { fa: "بُزُرْگْراه", en: "motorway", topic: "places" },
  { fa: "مَقْصَد", en: "destination", topic: "places" },
  { fa: "بَنْدَر", en: "port", topic: "places" },
  { fa: "مِعْده", en: "stomach", topic: "body" },
  { fa: "مَفْهوم", en: "concept, meaning", topic: "ideas" },
  { fa: "طَعْم", en: "taste", topic: "food" },
  { fa: "قوطی", en: "can, tin; small box", topic: "things" },
  { fa: "خَلیج", en: "gulf", topic: "places" },
  { fa: "بیوه", en: "widow, widower", topic: "people" },
  { fa: "تَقْدیر", en: "destiny; appreciation", topic: "ideas" },
  { fa: "لَهْجه", en: "accent, dialect", topic: "learning" },
  { fa: "مُحَبَّت", en: "affection, kindness", topic: "feelings" },
  { fa: "باتْری", en: "battery", topic: "things" },
  { fa: "بینی", en: "nose (more formal)", topic: "body" },
  { fa: "روزانه", en: "daily", topic: "time" },
  { fa: "پایْتَخْت", en: "capital (city)", topic: "places" },
  { fa: "چاه", en: "well (for water)", topic: "places" },
  { fa: "حَسودی", en: "jealousy", topic: "feelings" },
  { fa: "زاویه", en: "angle", topic: "things" },
  { fa: "کَمْبود", en: "shortage", topic: "ideas" },
  { fa: "کودَک", en: "child (written)", topic: "people" },
  { fa: "کِرایه", en: "fare; rent", topic: "everyday" },
  { fa: "مَنْزِل", en: "home (formal)", topic: "home" },
  { fa: "پیشْخِدْمَت", en: "waiter", topic: "people" },
  { fa: "یونانی", en: "Greek", topic: "places" },
  { fa: "تَوَقُّع", en: "expectation", topic: "ideas" },
  { fa: "چالِش", en: "challenge", topic: "ideas" },
  { fa: "ثَرْوَتْمَنْد", en: "wealthy", topic: "describing" },
  { fa: "آهِسْته", en: "slowly; quietly", topic: "describing" },
  { fa: "یونان", en: "Greece", topic: "places" },
  { fa: "شاگِرْد", en: "pupil; apprentice", topic: "people" },
  { fa: "مُجَرَّد", en: "single (unmarried)", topic: "people" },
  { fa: "اُرْدَک", en: "duck", topic: "animals" },
  { fa: "هُنَرْمَنْد", en: "artist", topic: "people" },
  { fa: "خَلْوَت", en: "quiet, not crowded", topic: "describing" },
  { fa: "بُز", en: "goat", topic: "animals" },
  { fa: "ریاضی", en: "mathematics", topic: "learning" },
  { fa: "مُچ", en: "wrist; ankle", topic: "body" },
  { fa: "فامیل", en: "relatives; (in Iran) surname", topic: "people" },
  { fa: "فَقیر", en: "poor", topic: "describing" },
  { fa: "داماد", en: "bridegroom; son-in-law", topic: "people" },
  { fa: "جَرّاح", en: "surgeon", topic: "people" },
  { fa: "وُجْدان", en: "conscience", topic: "ideas" },
  { fa: "کَمَرْبَنْد", en: "belt", topic: "things" },
  { fa: "نَمایِشْگاه", en: "exhibition", topic: "places" },
  { fa: "گَرْما", en: "heat", topic: "weather" },
  { fa: "سِفارَت", en: "embassy", topic: "places" },
  { fa: "رَنْگی", en: "coloured", topic: "colours" },
  { fa: "دَسْتْکِش", en: "glove", topic: "things" },
  { fa: "جَریمه", en: "fine (a penalty)", topic: "society" },
  { fa: "مُهَنْدِس", en: "engineer", topic: "people" },
  { fa: "کُنْجْکاو", en: "curious", topic: "describing" },
  { fa: "آگَهی", en: "advertisement", topic: "society" },
  { fa: "تُرْمُز", en: "brake", topic: "things" },
  { fa: "دَماغ", en: "nose", topic: "body" },
];
