import type { CommonWord } from "./types";

export const BATCH_E: CommonWord[] = [
  { fa: "اَفْغانِسْتان", en: "Afghanistan", topic: "places" },
  { fa: "اَفْغان", en: "Afghan (a person from Afghanistan; also adj.)", topic: "places" },
  { fa: "اَفْغانِسْتانی", en: "Afghan, from Afghanistan", topic: "places" },
  { fa: "کابُل", en: "Kabul", topic: "places" },
  { fa: "هِرات", en: "Herat", topic: "places" },
  { fa: "قَنْدَهار", en: "Kandahar", topic: "places" },
  { fa: "بَلْخ", en: "Balkh", topic: "places" },
  { fa: "تاجیکِسْتان", en: "Tajikistan", topic: "places" },
  { fa: "تاجیک", en: "Tajik", topic: "places" },
  { fa: "پاکِسْتان", en: "Pakistan", topic: "places" },
  { fa: "عِراق", en: "Iraq", topic: "places" },
  { fa: "تُرْکیه", en: "Turkey", topic: "places" },
  { fa: "تُرْک", en: "Turk; (in Iran) an Azerbaijani, a Turkic speaker", topic: "places" },
  { fa: "کُرْد", en: "Kurd", topic: "places" },
  { fa: "بَلوچ", en: "Baloch", topic: "places" },
  { fa: "عَرَبِسْتان", en: "Saudi Arabia (short for عَرَبِسْتانِ سَعودی)", topic: "places" },
  { fa: "سوریه", en: "Syria", topic: "places" },
  { fa: "مِصْر", en: "Egypt", topic: "places" },
  { fa: "کانادا", en: "Canada", topic: "places" },
  { fa: "آسیا", en: "Asia", topic: "places" },
  { fa: "آفْریقا", en: "Africa", topic: "places" },
  { fa: "اِصْفَهان", en: "Isfahan", topic: "places" },
  { fa: "شیراز", en: "Shiraz", topic: "places" },
  { fa: "مَشْهَد", en: "Mashhad", topic: "places" },
  { fa: "تَبْریز", en: "Tabriz", topic: "places" },
  { fa: "یَزْد", en: "Yazd", topic: "places" },
  { fa: "کِرْمان", en: "Kerman", topic: "places" },
  { fa: "رَشْت", en: "Rasht", topic: "places" },
  { fa: "اَهْواز", en: "Ahvaz", topic: "places" },
  { fa: "لَنْدَن", en: "London", topic: "places" },
  { fa: "پاریس", en: "Paris", topic: "places" },
  { fa: "اِسْتانْبُول", en: "Istanbul", topic: "places" },
  { fa: "آمْریکایی", en: "American", topic: "places" },
  { fa: "روسی", en: "Russian", topic: "places" },
  { fa: "هِنْدی", en: "Indian; Hindi", topic: "places" },
  { fa: "تُرْکی", en: "Turkish; (in Iran) Azerbaijani Turkish", topic: "places" },
  { fa: "عَرَبی", en: "Arabic", topic: "places" },
  { fa: "دَری", en: "Dari (the Persian of Afghanistan)", topic: "places" },
  { fa: "پَشْتُو", en: "Pashto", topic: "places" },
  { fa: "تاجیکی", en: "Tajik (language)", topic: "places" },
  { fa: "کُرْدی", en: "Kurdish", topic: "places" },
  { fa: "خَلیجِ فارْس", en: "the Persian Gulf", topic: "places" },
  { fa: "دَرْیایِ خَزَر", en: "the Caspian Sea", topic: "places" },
  { fa: "زِمِسْتان", spoken: "زِمِسْتون", en: "winter", topic: "time" },
  { fa: "بِرِنْج", en: "rice", topic: "food" },
  { fa: "گُوجه‌فَرَنْگی", spoken: "گُوجه", en: "tomato", topic: "food" },
  { fa: "سیب‌زَمینی", en: "potato", topic: "food" },
  { fa: "پیاز", en: "onion", topic: "food" },
  { fa: "هَویج", en: "carrot", topic: "food" },
  { fa: "پُرْتِقال", en: "orange (the fruit)", topic: "food" },
  { fa: "موز", en: "banana", topic: "food" },
  { fa: "اَنْگور", en: "grape", topic: "food" },
  { fa: "ماسْت", en: "yoghurt", topic: "food" },
  { fa: "کَره", en: "butter", topic: "food" },
  { fa: "فِلْفِل", en: "pepper", topic: "food" },
  { fa: "تُخْمِ مُرْغ", en: "egg (hen's egg)", topic: "food" },
  { fa: "نارِنْجی", en: "orange (colour)", topic: "colours" },
  { fa: "بَنَفْش", en: "purple", topic: "colours" },
  { fa: "جوراب", en: "sock", topic: "things" },
  { fa: "دامَن", en: "skirt", topic: "things" },
  { fa: "فَرْش", en: "carpet, rug", topic: "home" },
  { fa: "کَمَر", en: "waist; lower back", topic: "body" },
  { fa: "بازو", en: "upper arm", topic: "body" },
  { fa: "چین", en: "China", topic: "places" },
  { fa: "فَرانْسه", en: "France", topic: "places" },
  { fa: "تُرْکَمَنِسْتان", en: "Turkmenistan", topic: "places" },
  { fa: "آذَرْبایْجان", en: "Azerbaijan (the country; also the region of north-west Iran)", topic: "places" },
  { fa: "اَرْمَنِسْتان", en: "Armenia", topic: "places" },
  { fa: "مَزارِ شَریف", en: "Mazar-i-Sharif", topic: "places" },
  { fa: "قُم", en: "Qom", topic: "places" },
  { fa: "کِرْمانْشاه", en: "Kermanshah", topic: "places" },
  { fa: "پَشْتون", en: "Pashtun", topic: "places" },
  { fa: "هَزاره", en: "Hazara", topic: "places" },
  { fa: "اُزْبَک", en: "Uzbek", topic: "places" },
];
